### ISSUE TITLE
Milestones / release schedule?

### ISSUE THREAD

**Issue by pkieltyka** [grpc/grpc-go#1113]
Hey all,

Thanks very much for the work on gRPC. Personally I am very bullish on the architecture of the product and I really want to adopt it more heavily. However, is there a roadmap or milestone available? as well, it would be nice to see the roadmap outline the progression of the different language implementations, ie. Go, Node, Java, Python, etc.

**Comment by hsaliak** [comment]
@pkieltyka We do a few different things but a good place to look at the long term features being planned for the project is at the grpc/proposal repo. Big changes in behaviour or new features do need an accepted gRFC. The grpc-go and grpc project are also using projects to track items for the upcoming release. We release on a fixed release cycle. The grpc-java project uses milestones, since that's worked well for them in the past. 

Is there any specific feature or functionality you are looking for?
