### ISSUE TITLE
error from Server.processUnaryRPC is left uncaught

### ISSUE THREAD

**Issue by zensh** [grpc/grpc-go#1184]
Code: https://github.com/grpc/grpc-go/blob/master/server.go#L955

error from Server.processUnaryRPC is left uncaught, there is no way to handle it.

such as appErr: https://github.com/grpc/grpc-go/blob/master/server.go#L768

**Comment by MakMukhi** [comment]
When an error occurs in processUnaryRPC a status is written on the user stream. The returning of error from that function is only so that stats handling in defer can take place. This could have been avoided by creating a local err variable. We might make such a refactoring in the future but aren't actively working on it.
Thanks for bringing this to attention.
