### ISSUE TITLE
Server leaks goroutines and stops processing some of the requests

### ISSUE THREAD

**Issue by utrack** [grpc/grpc-go#1201]
Using Go 1.8.1, gRPC 1.0.5/1.2.1, linux x86_64 on CentOS.

Hi!
Under load server randomly starts leaking goroutines and stops processing some percent of requests made.

Issue is reproduceable on gRPC 1.2.1, but I didn't catch the stack yet - providing 1.0.5 stack for now.

Leak and top3 goroutines' stacks:
```
goroutine profile: total 13753

13435 @ 0x431dfa 0x441389 0x44017c 0x746376 0x73fff0 0x5140bd 0x5152fa 0x517054 0x51d07b 0x462d31
#   0x746375    search_api/vendor/google.golang.org/grpc/transport.wait+0x445           /go/src/search_api/vendor/google.golang.org/grpc/transport/transport.go:586
#   0x73ffef    search_api/vendor/google.golang.org/grpc/transport.(*http2Server).Write+0x1bf   /go/src/search_api/vendor/google.golang.org/grpc/transport/http2_server.go:646
#   0x5140bc    search_api/vendor/google.golang.org/grpc.(*Server).sendResponse+0x14c       /go/src/search_api/vendor/google.golang.org/grpc/server.go:583
#   0x5152f9    search_api/vendor/google.golang.org/grpc.(*Server).processUnaryRPC+0x1029   /go/src/search_api/vendor/google.golang.org/grpc/server.go:733
#   0x517053    search_api/vendor/google.golang.org/grpc.(*Server).handleStream+0x6a3       /go/src/search_api/vendor/google.golang.org/grpc/server.go:892
#   0x51d07a    search_api/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1+0xaa    /go/src/search_api/vendor/google.golang.org/grpc/server.go:468

84 @ 0x431dfa 0x441389 0x44017c 0x5fe4bd 0x462d31
#   0x5fe4bc    net/http.(*persistConn).writeLoop+0x3bc /usr/local/go/src/net/http/transport.go:1646
79 @ 0x431dfa 0x42c6eb 0x42be49 0x6cae68 0x6caed4 0x6cc711 0x6dd7a0 0x5fbcf4 0x79501c 0x795202 0x5fc911 0x462d31
#   0x42be48    net.runtime_pollWait+0x58       /usr/local/go/src/runtime/netpoll.go:160
#   0x6cae67    net.(*pollDesc).wait+0x37       /usr/local/go/src/net/fd_poll_runtime.go:73
#   0x6caed3    net.(*pollDesc).waitRead+0x33       /usr/local/go/src/net/fd_poll_runtime.go:78
#   0x6cc710    net.(*netFD).Read+0x1a0         /usr/local/go/src/net/fd_unix.go:243
#   0x6dd79f    net.(*conn).Read+0x6f           /usr/local/go/src/net/net.go:173
#   0x5fbcf3    net/http.(*persistConn).Read+0x153  /usr/local/go/src/net/http/transport.go:1261
#   0x79501b    bufio.(*Reader).fill+0x10b      /usr/local/go/src/bufio/bufio.go:97
#   0x795201    bufio.(*Reader).Peek+0x61       /usr/local/go/src/bufio/bufio.go:129
#   0x5fc910    net/http.(*persistConn).readLoop+0x1a0  /usr/local/go/src/net/http/transport.go:1418

51 @ 0x431dfa 0x441389 0x44017c 0x746376 0x73ff83 0x5140bd 0x5152fa 0x517054 0x51d07b 0x462d31
#   0x746375    search_api/vendor/google.golang.org/grpc/transport.wait+0x445           /go/src/search_api/vendor/google.golang.org/grpc/transport/transport.go:586
#   0x73ff82    search_api/vendor/google.golang.org/grpc/transport.(*http2Server).Write+0x152   /go/src/search_api/vendor/google.golang.org/grpc/transport/http2_server.go:641
#   0x5140bc    search_api/vendor/google.golang.org/grpc.(*Server).sendResponse+0x14c       /go/src/search_api/vendor/google.golang.org/grpc/server.go:583
#   0x5152f9    search_api/vendor/google.golang.org/grpc.(*Server).processUnaryRPC+0x1029   /go/src/search_api/vendor/google.golang.org/grpc/server.go:733
#   0x517053    search_api/vendor/google.golang.org/grpc.(*Server).handleStream+0x6a3       /go/src/search_api/vendor/google.golang.org/grpc/server.go:892
#   0x51d07a    search_api/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1+0xaa    /go/src/search_api/vendor/google.golang.org/grpc/server.go:468
```

**Comment by utrack** [comment]
OK, so it seems that it happens if pre-1.7 `x/net/context` is vendored and some requests are canceled in-flight.
See https://github.com/utrack/grpc-go-poc-1201 , stable reproduce

**Comment by dfawley** [comment]
Thanks for the repro case.  Usage of the standard library context isn't supported by grpc-go, but I may be able to make a change here that will avoid this particular panic.

**Comment by dfawley** [comment]
As for the main issue reported here, my guess about what's happening:

The client is panicking after starting the RPC, which means the client-side code in grpc to manage the stream for the RPC is being aborted unexpectedly.  Because of this:

1. the server never gets the context cancellation, and
2. the connection's flow control is never updated after the server's response is sent.

That would explain why the server stops processing requests on that connection.  If a new connection is established, I would expect it to be handled correctly.

Not panicking should eliminate the problem.

Looking at the output from your repro case, though (with #1258 applied), it seems like client-side cancellation may not be getting propagated to the server, or flow control still ends up getting blocked even with proper error handling.  We still ended up with 73 goroutines on the server, and when I quit it, it spammed errors like this:

grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
grpc: Server.processUnaryRPC failed to write status stream error: code = Canceled desc = "context canceled"

**Comment by dfawley** [comment]
It looks like the client's implementation is to NOT cancel RPCs after the first 500.  At that point, the RPCs wait until completion, which is why the server has 73 goroutines running.  There should be ~67 server handlers in flight at any time (1 sent per 15ms, 1s per request), and there are a handful of other goroutines running.  So I think there is nothing else left to do on this issue.  Thank you for the report and repro code.
