### ISSUE TITLE
methods for adding google.rpc.details to gRPC status 

### ISSUE THREAD

**Issue by ghasemloo** [grpc/grpc-go#1233]
[google.rpc.status](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) has a details field of type proto Any which is very useful for APIs with google.rpc's [error_details](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto)

Right now gRPC [status](https://github.com/grpc/grpc-go/blob/master/status/status.go) package has no easy way of adding or reading details (one has to convert to and from proto to be able to do this).

I think simple Details() and SetDetails() methods would solve the issue. An alternative which would maintain immutability of status is to add new NewWithDetails() in place of SetDetails. 

I can write them and send a pull request if this seems reasonable.

**Comment by dfawley** [comment]
What is the exact API you are proposing, so I can better understand your intentions?  Status should be immutable, so a `WithDetails` is preferred over `SetDetails`.

**Comment by ghasemloo** [comment]
I was thinking this:
```
func (s *Status) Details() *apb.Any

func NewWithDetails(c codes.Code, msg string, details *apb.Any) *Status
```

Maybe also 
```
func ErrorWithDetails(c codes.Code, msg string, details *apb.Any) error
```

**Comment by dfawley** [comment]
`Details()` is redundant with `s.Proto().Details`.  But then again, `Message()` is redundant with `s.Proto().Message`.  I'd be OK with having this accessor for convenience and consistency.  (Note that `Details` is actually a slice of `Any`s.)

The reason I abandoned a constructor that takes details and went with `FromProto`/`ErrorProto` was because of the `Newf`/`Errorf` variants.  Given this, I am still inclined to require the use of `ErrorProto` for users that want to return details in the error.  There's not really much convenience or utility that this kind of constructor would provide.  If we could also perform `ptypes.MarshalAny` and fill in the Details field for the user according to best practices, that could be nice, but then `ErrorWithDetails()` would have to return `(error, error)`, which would be awkward and maybe not all that convenient after all.

**Comment by ghasemloo** [comment]
I see your point. Maybe we should look at use cases. Let me give two that I have in mind. Example 1:

In the following I am simplifying things. Say we have a resource Book and a Library API which has a Get method. A caller has written

```
req := GetBookRequest{Name: "books/The Go Programming Language"}
book, err := libClient.GetBook(ctx, req)
```

In my server I have to call the API for another system, e.g. let's say that the data for books are stored in a table called "books" in a database that the caller has configured and owns. I call the API for database to read from the table.

```
req := GetTableRequest{Name: "table/books"}
table, err := dbClient.GetTable(ctx, req)
```

When I get a NotFound status error it means the table does not exist on the database. I want to let the caller know that the table does not exist. But errors are scoped to the resource of the method. I want to use error detail ResourceInfo to say that it is the table that is missing. How can I do that?

Right now I would have to write something like this:

```
d := edpb.ResourceInfo{
  ResourceType: "DB Table",
  ResourceName: "table/books",
  Owner: "project:xyz",
}
detail, _ := MarshalAny(d)
// We can add error handling but it is almost impossible for MarshalAny to fail.
p := status.New(Codes.FAILED_PRECONDITION, "the table books does not exist on the database").Proto()
p.Details = append(p.Details, detail)
return nil, status.ErrorProto(p)
```

Or I can just go for google.rpc.status proto and google.rpc.codes proto and ignore the gRPC status object except for ErrorProto part:

```
d := edpb.ResourceInfo{
  ResourceType: "DB Table",
  ResourceName: "table/books",
  Owner: "project:xyz",
}
detail, _ := MarshalAny(d)
// We can add error handling but it is almost impossible for MarshalAny to fail.
p := spb.Status{
  Code: cpb.FAILED_PRECONDITION, 
  Message: "the table books does not exist on the database",
}
p.Details = append(p.Details, detail)
return nil, status.ErrorProto(p)
```

Now I can write this and it is fine, but it essentially ignores most of gRPC's status package.

I think a better way might be this:

The error_details are quite standard, it is not going to change much. So we can make them first class objects like gRPC status. We have an ErrorDetail interface, a type for each error detail in the error_details.proto (not sure if we need a new for them). We then add a status.AddDetail() function to gRPC status package. We then write something like this:

```
detail := ed.ResourceInfo{
  ResourceType: "DB Table",
  ResourceName: "table/books",
  Owner: "project:xyz",
}
s := status.New(
  Code: cpb.FAILED_PRECONDITION, 
  Message: "the table books does not exist on the database",
)
s = status.AddDetail(s, detail)
return nil, s.Error()
```

What do you think?

**Comment by dfawley** [comment]
Yes, because of [Un]MarshalAny, we will need to pass errors back to the caller.  I hadn't noticed the `DynamicAny` type that can be passed to `UnmarshalAny`, so I think we _can_ decode the any messages for the user.

How about this API?

```go
// WithDetails returns a new status with the provided details messages appended to the status.
// If any errors are encountered, it returns nil and the first error encountered.
func (s *Status) WithDetails(...proto.Message) (s, error)

// Details returns a slice of details messages attached to the status.
// If any errors are encountered, it returns nil and the first error encountered.
func (s *Status) Details() ([]proto.Message, error)
```

I think this would be useful because it hides both the Status and Any proto types from the user.

`WithDetails` is a little more Java/builder style, but it is more convenient to use than `status.AddDetails(s, ...)`.  Usage would be:

```go
// setting:
err, _ := status.New(codes.Unavailable, "msg").WithDetails(m1, m2).Err()
return err

// getting:
ds, _ := s.Details()
for d := range ds {
  switch m := d.(type) {
    case ed.RetryInfo:
      // ...
  }
}
```

**Comment by ghasemloo** [comment]
I like the idea of WithDetails. It seems cleaner.

I am not sure the code sample you have would work though, I think go would complain that we are using Err() on the pair (s, err) returned from WithDetails method.

Maybe we can have a details.go package that hides the error_details.proto messages inside (like status.go does with status proto) to avoid marshalling/unmarshalling errors. If we created the object we can make sure no error will happen for marshaling/unmarshalling when using them with WithDeatils I think.

**Comment by dfawley** [comment]
> I am not sure the code sample you have would work though, I think go would
> complain that we are using Err() on the pair (s, err) returned from WithDetails method.

Yes, you're right.  Also, Err() only returns one value.  You'd have to do this instead:

```go
s, _ := status.New(codes.Unavailable, "msg").WithDetails(m1, m2)
return s.Err()
```

I'd rather not have a package that deals with `error_details.proto` messages in grpc itself -- this would introduce an unnecessary dependency, and even create a wrapper library for it.  It should be straightforward to construct the necessary error_details protos and serialize them using an API that works with all protos.  If simple convenience wrappers are helpful for an application, those could be implemented either in the same package that needs them or in a separate library.  Also, I believe the marshal/unmarshal errors will always be technically possible (e.g. if the message is too big).

The Details/WithDetails functions would be useful for everyone using gRPC that wants to attach/read error details, so if you are interested in adding those, we would appreciate the contribution.  Thanks!

**Comment by ghasemloo** [comment]
I see, not wanting to introducing a new dependency for this is understandable. sgtm. Hopefully will send a pull request next week. Thank you. :)

**Comment by ghasemloo** [comment]
Sorry for not getting this done yet, will send the pull request by next week.

**Comment by c4milo** [comment]
@ghasemloo any update?

**Comment by ghasemloo** [comment]
Working on it. When I try to switch over the type of the error detail from Details() I get DynamicAny type in place of the actual type of error so switch as we discussed doesn't work. I am looking to see if there is a way to solve the issue so we can still do 

```go
switch m := d.(type) {
    case ed.RetryInfo:
      // ...
  }
```

**Comment by ghasemloo** [comment]
Here is the draft:
https://github.com/ghasemloo/grpc-go/commit/f7d5e1c74f959a61cce005617e48077d2f7c1b17

Please have a look, if it looks good to you I will add a few more tests to have better test coverage and then send a pull request.

**Comment by dfawley** [comment]
I had a few small comments that I made on that commit, but it looks great overall, thanks!

Regarding the tests, the success cases are plenty (maybe even too many?), so maybe add a few tests for the various places where errors can occur.  Also, I might recommend expressing them a little differently for that purpose:

```go
	m1 := &epb.ResourceInfo{ResourceType: "book"}
	...

	tests := []struct {
		s *Status
		want proto.Message
		wantErr string // or just a bool?
	}{
		s: New(codes.OK, "ok").WithDetails(m1),
		want: m1
	}, {
		s: nil
		wantErr: "..."
	}, {
		s: New(codes.OK, "ok").WithDetails(nil),
		wantErr: "..."
...
```

Thanks again!

**Comment by ghasemloo** [comment]
Thanks, will do today.

A question: regarding returning error on nil input, no other function in the package returns a separate error, I am wondering if it would be more consistent with the rest of the functions if we return a bool in place of an error as in the FromError function.

**Comment by dfawley** [comment]
> A question: regarding returning error on nil input, no other function in the package returns a separate error, I am wondering if it would be more consistent with the rest of the functions if we return a bool in place of an error as in the FromError function.

An error here makes more sense, so the user can see the error produced by MarshalAny.  We just need to return a special error in this case.  That error should basically never happen unless the user does something very wrong.  (For FromError(), a bool is sufficient, because the error either *is* or *is not* a status type.)

> ps: I cannot do s: New(...).WithDetails(...), because WithDetails returns two values.

Derp.  You would need to wrap it in a closure that does not return an error (and obviously don't give it any invalid input as I did in the 3rd case -- t.Fatal instead if there is an error.)

**Comment by ghasemloo** [comment]
One more question: right now we have two status that represent OK: if you create a status using New the proto inside will never be nil, if we create it however using FromProto with nil, we get a status with proto that is nil. Should I be concerned that WithDetails on an OK status will depend on how that OK is represented? Doesn't feel good that it behaves differently based on internal representation. 

Should I file a bug to make the FromStatus actually create a non-nil status proto so we never have to deal with a status that has nil status proto inside it? The assumption that the internal status proto inside Status object is never nil would also simplify the rest of the code. However it can be a breaking change since someone might be relying on FromProto(p).Proto() == p.

**Comment by dfawley** [comment]
Lots of good points.

`status.FromProto(p).Proto() != p`, actually (because that's a pointer comparison), just things that `proto.Equal()`.  Right now, `FromProto(nil).Proto() == nil`, but that's not something anyone *should* be relying upon.  So changing `status.FromProto()` like that doesn't seem unreasonable.

However...  `WithDetails()` doesn't really make sense on an OK status, either -- OK statuses get converted into a pure-nil error in `Err()` before they are handed over to grpc, so the details will be lost then.  So we could make `WithDetails()` error *any time* `s.Code() == codes.OK`.  That would help prevent the misconception that the details of an OK status can be sent to the client from the server.  What do you think?

**Comment by ghasemloo** [comment]
Sounds logical to me that OK shouldn't have error details and go treats it as nil error as you said however is it documented as such on google.rpc.status? If not I think we should also file a bug with the folks responsible for google.rpc.status so that people don't try to depend on the fields of google.rpc.status when code is OK.

**Comment by dfawley** [comment]
No, the proto message itself doesn't document that status of `OK` with details is nonsensical.  The best it does is call them "error details" in the documentation, and an "OK" status logically isn't an error (and the comments in google.rpc.code states this, too).  So while the type itself doesn't document them explicitly that way, I think it's fine for gRPC's helpers to not be able to generate an OK status with details, since the details will be lost when converted into an error.

**Comment by ghasemloo** [comment]
Btw, I think it would be also helpful to have a Is method to check the code of an error so one doesn't need to convert to state and then check the code:

```go
// Is checks the error code of a status error.
func Is(err error, code codes.Code) bool {
	if s, ok := status.FromError(err); ok {
		return s.Code() == code
	}
	return false
}
```

Then we can have simple error handling like:

```go
resp, err := client.RPC(ctx, req)
if status.Is(err, codes.NotFound) {
    ...
}
```

I can include that in this pull request or open a separate bug for it.

**Comment by menghanl** [comment]
It seems clearer to do the `Is` change in another PR, if we decide to have it.

@dfawley is out this week and will be back next Monday. Let's wait and get his input on the `Is` function.

**Comment by ghasemloo** [comment]
sgtm. :)

**Comment by dfawley** [comment]
With #1754, this last part (`Is`) should be satisfied (via `status.Code(err) == code` instead).
