### ISSUE TITLE
Get an unexpected "context canneled" when server stream.Recv()

### ISSUE THREAD

**Issue by deafwolf** [grpc/grpc-go#1234]
I want my grpc server to know when client disconnected. So I use stream.Recv to solve it.
But I get a "rpc error: code = Canceled desc = context canceled".
I found #1061 but I'm not sure if they are the same problem.

Here is the demo to reproduce this issue
https://github.com/deafwolf/grpc-stream

My enviroment
go version go1.7.1 darwin/amd64
grpc and golang.org/x/net/context is up-to-date

**Comment by menghanl** [comment]
Server indicates the RPC is done by returning from the service handler. When the service handler returns, gRPC cancels this stream because the RPC is done.

So in your handler for RPC `Start`, you need to either call `Recv()` in the same goroutine, or add some synchronization in the service handler to make sure the handler doesn't return until you are done with this RPC.

**Comment by deafwolf** [comment]
@menghanl Thank you very much.

I remove the goroutine in server.Start, it works fine. 

I just need an error when client disconnected, I don't care the real reason such as EOF/canceled. I don't know the Start RPC is done, so I think the client cancel the RPC and server receive an "unexpected" error.
