### ISSUE TITLE
Client does not receive error from bidirectional streaming server

### ISSUE THREAD

**Issue by stub42** [grpc/grpc-go#1319]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.4.1

### What version of Go are you using (`go version`)?

1.8.3

### What operating system (Linux, Windows, …) and version?

Linux

### What did you do?

A bidirectional streaming server handler returned an error

```go
func (srv *Service) Example(stream pb.Eggs_ExampleServer) error {
	err := srv.begin()
	if err != nil {
		return err
	}
}
```

### What did you expect to see?

The informative error from the server returned when the client attempts to Send

### What did you see instead?

client gets an uninformative EOF error

It seems that if a server handler fails, returning an error before sending or receiving any messages, then the error message is lost and the client never sees it.

**Comment by MakMukhi** [comment]
Hey, thanks for reporting the issue. This is actually the expected behavior, the error returned by send is not indicative of the final status of the stream (it only tells the error incurred during that send). The final status of the stream can be retrieved by Recv().
Note: If there's data before the error Recv will first return the data and finally the error.

I've opened a pull request to document this: #1320

**Comment by stub42** [comment]
If Send gets EOF or other unrecoverable stream error, should it automatically call Recv() and return that error instead?

**Comment by MakMukhi** [comment]
There might be data stored in the buffer before the error, so it's
important that the user application code calls Recv and consume the data
and eventually see the error.
