### ISSUE TITLE
Feature Request  Add interceptors after Dial

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-go#1323]
Looking at the API today, there is not a way to add interceptors to a channel or a stub until Dial time.  This conflates two different actions: modifying requests and establishing a connection.   

Would it be possible to add an API to fork a channel or stub with an additional interceptor?  This would allow libraries that wish to add interceptors, but not construct their own channel to do so.

**Comment by dfawley** [comment]
Interceptors should really be `CallOption`s, not `DialOption`s, because they only apply to the calls themselves.  If we added a `CallOption` for interceptors, would that satisfy your needs?

**Comment by carl-mastrangelo** [comment]
@dfawley yes, it would.

**Comment by easwars** [comment]
@erni27 : Would you be interested in taking this one?

**Comment by erni27** [comment]
Hi @easwars, I really appreciate your friendly ping.
I'd like to work on it.
I'm wondering how should I approach this. I'm thinking about creating new `CallOption`s for interceptors with no-op `before` and `after` methods. Then when doing the unary or streaming RPC iterate through passed `opts` and assert `CallOption`s for interceptors. If any, add to the interceptors' chain. I'm not sure if this is a good solution. Seems foolish to do the iteration always when we invoke unary RPC or create a new stream. Any advice? Or is it better to create a PR and discuss there?

**Comment by easwars** [comment]
@erni27 : Thank you for picking this up. I think your approach seems fine to me. I don't see a way to avoid iterating through the list of call options for every RPC because these interceptors are going to be call options, i.e specified per-call, and therefore can be different across RPCs.

I assume we would have to do the following:
- Define new `CallOption`s. This would include one for unary, and one for streaming. And these call options would accept a chain of interceptors just like how our existing dial options do [here](https://pkg.go.dev/google.golang.org/grpc#WithChainUnaryInterceptor) and [here](https://pkg.go.dev/google.golang.org/grpc#WithChainStreamInterceptor). 
- Our preferred method for defining call options is by defining structs which implement the required functionality. See [example](https://pkg.go.dev/google.golang.org/grpc#CompressorCallOption).
- The method on the `ClientConn` which creates a new streaming RPC is [here](https://pkg.go.dev/google.golang.org/grpc#ClientConn.NewStream), and the method which creates a new unary RPC is [here](https://pkg.go.dev/google.golang.org/grpc#ClientConn.Invoke). Both these methods check if interceptors are configured as dial options, and if so, invoke them.
  - Here, we would have to traverse the list of passed in call options, and type assert to the struct which implements our new call option, and add it to the existing list (if any is already configured through dial options).

@dfawley : Any thoughts on the above approach?

@dfawley : I have a couple of questions:
- Should we support the option of appending vs prepending of these interceptors configured via call options, or should it just be one way and clearly documented?
- What would be the ideal behavior if the same call option used to configure interceptors (of one type) is called multiple times? Is overwriting a fine option?

**Comment by easwars** [comment]
> Or is it better to create a PR and discuss there?

I think it would be better to discuss here before starting the work required for the PR.

**Comment by dfawley** [comment]
> Any thoughts on the above approach?

One thought: if possible, replace the implementation of the current dial options with `WithDefaultCallOptions(CallChainUnaryInterceptor(...))`.  This will reduce the things we're tracking inside grpc.

Another random idea: what if we had an interface for combining the two interceptor types so people don't need to specify both every time?  Maybe it's too late for this to be useful?  Or maybe we "deprecate" all the

> Should we support the option of appending vs prepending of these interceptors configured via call options, or should it just be one way and clearly documented?

It seems too complex to support both ways.  I think whatever we do should be good enough for most people, and if it's not, then they can always use a single interceptor and manage the stacking themselves.

> What would be the ideal behavior if the same call option used to configure interceptors (of one type) is called multiple times? Is overwriting a fine option?

I don't think so.  They should stack just like `WithChain*Interceptor`.  Otherwise you run into situations where a library accepts call options and also adds its own, and if both specify interceptors, the behavior becomes unreliable.

**Comment by erni27** [comment]
> One thought: if possible, replace the implementation of the current dial options with WithDefaultCallOptions(CallChainUnaryInterceptor(...)). This will reduce the things we're tracking inside grpc.

It would require changes to the existing logic and postponing interceptors chaining to the time of unary / stream creation instead of doing so when creating a conn. In this scenario explicit interceptors fields in `dialOptions` could be removed. It seems to be fine since they really apply to the calls. One potential blocker preventing us from replacing the current dial options implementation with `WithDefaultCallOptions(CallChainUnaryInterceptor(...))` is that docs for `WithChainUnaryInterceptor` and `WithChainStreamInterceptor` say:

```
// All interceptors added by this method will be chained, and the interceptor
// defined by WithStreamInterceptor will always be prepended to the chain.
```

There is no way to assure that the interceptor defined by `WithStreamInterceptor` or `WithUnaryInterceptor` will always be prepended to the chain since interceptors would be just appended to the `callOptions` and chained later. It could break the applications defining the single interceptor after defining the chain. @dfawley

**Comment by dfawley** [comment]
> It would require changes to the existing logic and postponing interceptors chaining to the time of unary / stream creation instead of doing so when creating a conn

Good point.  Maybe this is not worth doing, then.

**Comment by easwars** [comment]
Closing this one for now until we have users requesting for this feature. There are multiple options (and are not straightforward), and we are not sure which would be the most appropriate one to pick until we have users asking for it.
