### ISSUE TITLE
Support registration of a default interceptor.

### ISSUE THREAD

**Issue by mklencke** [grpc/grpc-go#1325]
Client-side interceptors are currently supported by passing the relevant `DialOption` to `Dial`. This makes it hard to add an interceptor that is executed for all outgoing connections, especially when other libraries are used.

Would it be feasible to add a "default interceptor" or "default `DialOption`" mechanism? This is especially useful for frameworks/middleware. If not, what are some potential issues with such a feature?

**Comment by dfawley** [comment]
This worries me a bit, because it means an import somewhere deep in a dependency tree could install an interceptor without you realizing it, and be able to do anything it wanted to.  Security-related issues aside, we'd probably also need to add support for multiple interceptors, otherwise things would break in hard-to-debug ways as soon as you tried to use more than one of these.

If you wanted this for your project, you could write a grpc-wrapper package that handles registration of `DialOption`s and wraps `grpc.Dial()` using those extra options, but I don't think this is something we want to put in the main grpc libraries at this time.

Closing this request for the above reasons.  If I'm misunderstanding your request, please feel free to comment further.  Thanks for the suggestion!
