### ISSUE TITLE
Triggering MaxSendMsgSize limit on response streaming RPC does not raise exception on client side

### ISSUE THREAD

**Issue by kahuang** [grpc/grpc-go#1334]
For more context: https://github.com/grpc/grpc/issues/11586

The golang server properly sends back an error response for Unary RPC when this limit is exceeded, but for the streaming RPC it does not. The client side hangs until the server finishes its response, and no responses are actually returned client side.

The golang server should send back an error in the streaming RPC case so that clients don't erroneously believe there is no response.

**Comment by lyuxuan** [comment]
User is expected to handle the error returned from Send() and return the error in the handler if it's not nil. In this way, the client is notified immediately and will not hang. 

Because of the potential confusion it may cause, we are planning to implement automatic error sending back for the streaming case.
