### ISSUE TITLE
Dial target format undocumented

### ISSUE THREAD

**Issue by stub42** [grpc/grpc-go#1346]
The target argument to the Dial method has no description about what it accepts.

In particular, I get failures for:

- "[::]:33181"
- "127.0.0.1:46679"

Without knowing what it accepts, it is difficult to reliably transform the output of net.Listen(...).Addr() into a format that a client can use. Or to know if the above should work and I'm tripping over a gRPC bug.

**Comment by lyuxuan** [comment]
"[::]:33181" and "127.0.0.1:46679" are valid address if you don't install you custom resolver, which may have different behavior. 

If you don't use balancer&resolver, the valid input address should be the same as net.Dial. Otherwise, it depends on the resolver implementation.

Do you know what's the error message for the failure, and how we can reproduce it so we could possibly debug the issue? Thanks!

**Comment by stub42** [comment]
Thanks for the clarification. I've tracked down the underlying problem, which was at my end. An atavistic url.Parse was found, which worked ok for names but failed with IP addresses, and the error appeared like it was coming from grpc.Dial.
