### ISSUE TITLE
Access to lower-level marshalling API

### ISSUE THREAD

**Issue by sashabaranov** [grpc/grpc-go#1350]
Consider you store serialised protobuf messages in database and you want to return them via grpc without modifications. Currently you have two options:

1. Read messages from db, unmarshal to Go struct, pass it to grpc to marshal again. (Unnecessary unmarshalling-marshalling happens).

2. Create two response types:

```
message Response {
  repeated MyMessage messages = 1;
}

message ResponseRaw {
  repeated bytes messages = 1;
}
```

The `Response` and `ResponseRaw` would have identical binary representation after marshalling. Therefore rpc can be declared as

```
rpc GetResponse(Request) returns (ResponseRaw) {}
```

And then client can be patched, so it would unmarshal into `Response` instead of `ResponseRaw`.

However, it would be much nicer if RPC can be declared as 
```
rpc GetResponse(Request) returns (Response) {}
```

And if grpc-go could let user to marshal response manually and just return `([]byte, error)` instead of `({}interface, error)`.

PS This case is also summarised here: https://stackoverflow.com/questions/3438376/add-raw-serialized-value-to-a-repeated-field-in-protocol-buffers-protobuf-net/44935871

**Comment by flisky** [comment]
Actually you could. I'd like to share my hack-but-simple way to archive this -

1. edit the `.pb.go` file to change the server interface to return `([]byte, error)`

2. implement custom codecs
```
import "github.com/gogo/protobuf/proto"

type Codec struct{}

func (Codec) Marshal(v interface{}) ([]byte, error) {
        return v.([]byte), nil
}

func (Codec) Unmarshal(data []byte, v interface{}) error {
        return proto.Unmarshal(data, v.(proto.Message))
}

func (Codec) String() string {
        return "no-op-marshal codec"
}
```

3. construct the server with `grpc.CustomCodec`

I was surprised by grpc-go's customizability when I digged into this, so enjoy:)

**Comment by sashabaranov** [comment]
@flisky wow, thanks! But is it possible to do such thing only for some server endpoints?

**Comment by flisky** [comment]
The magic goes to `Codec.Marshal`, and the default codec treats value as `proto.Message`. 
I think you may keep the default codecs and return a specific type with smallest marshal overhead.

**Comment by menghanl** [comment]
It's generally not recommended to modify generated `pb.go` files. Because if you update your proto files and regenerate `pb.go`, you will need to remember to modify them again.
Modifying `pb.go` files can work as workarounds, but not a general solution.

`pb.go` files contain helper functions for proto users (as they are generated from proto files...).
If you don't want proto message in your services, you can call gRPC APIs directly (for example [Server.RegisterService](https://godoc.org/google.golang.org/grpc#Server.RegisterService) on the server side, but that means you also need to handle some other logic like the interceptors.
