### ISSUE TITLE
Stream timeout on server causes client hang

### ISSUE THREAD

**Issue by stub42** [grpc/grpc-go#1386]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.4.2

### What version of Go are you using (`go version`)?

go version go1.8.3 linux/amd64

### What operating system (Linux, Windows, …) and version?

Ubuntu 16.04

### What did you do?

I added a timeout using the InTapHandle server option. See https://gist.github.com/stub42/4aa5e262778334f69ea999e5a195d65f

### What did you expect to see?

An error consistently returned to the client

### What did you see instead?

About half the time, the server fails to get a response to the client and emits an error:

   INFO: 2017/07/24 17:15:38 grpc: Server.processUnaryRPC failed to write status stream error: code = DeadlineExceeded desc = "context deadline exceeded"

The client hangs indefinitely when this happens, waiting for a reply that will never arrive.

The other half of the time, the error response gets sent to the client as expected.

**Comment by dfawley** [comment]
Thanks for the report.  We discussed this and found that the assumption is that a context deadline/cancellation error originates because of the client, so there's no need to notify the client of the error, but in the case of InTapHandle returning a different context, that cannot be safely assumed.

We need to determine what the right error to return is in this case before moving forward.  `DeadlineExceeded` / `Canceled` (conditionally) seem like obvious front-runners, but if the client didn't set a deadline or cancel the RPC, are those appropriate to return?

**Comment by dfawley** [comment]
To fix this, we will remove the s.ctx being passed to the wait() for acquiring the transport's writable channel.  This will ensure that we always write the status even when the context is cancelled.

https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L762

**Comment by dfawley** [comment]
Also, related, it looks like we latch the context before the InTapHandle into the receive buffer, which means that a streaming RPC that is blocked on Recv will block longer than the TapHandler's context (or indefinitely if no deadline is set on the RPC).

**Comment by Zeymo** [comment]
same to me when client base nghttp2 with timeout
if we don't use tapHandle, to quick fix this is remove s.ctx right ? any side effect？ 
@dfawley

**Comment by menghanl** [comment]
@Zeymo Without InTapHandler, the client timeout should be propagated to the server, and the timeout should work as expected.

Can you give more details on what the issue is?

**Comment by Zeymo** [comment]
@menghanl At beginning we use nghttp2 as client without timeout event schedule, when server s.ctx `DeadlineExceeded`/ `Canceled`  as dfawley say not always write the status.  `wait()` with s.ctx maybe not cancel stream util nghttp2 send RST_FRAME since ctx error

now we add timeout even above nghttp2 , also want grpc always write the status to client and cancel stream quikly

**Comment by Zeymo** [comment]
ping @dfawley  
> To fix this, we will remove the s.ctx being passed to the wait() for acquiring the transport's writable channel. This will ensure that we always write the status even when the context is cancelled.

what about this change ? any time schedule?

**Comment by dfawley** [comment]
I am working on this, and assuming all goes well, expect to be done in a day or two.
