### ISSUE TITLE
example->route_guide

### ISSUE THREAD

**Issue by waytai** [grpc/grpc-go#1398]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?  
grpc-go 1.5.1
### What version of Go are you using (`go version`)?
go version go1.7rc6 linux/amd64
### What operating system (Linux, Windows, …) and version?
ubuntu14.04
### What did you do?
If possible, provide a recipe for reproducing the error.
go run server/server.go
go run client/client.go
but nothing result to see.
### What did you expect to see?
go run client/client.go 
should see the result
### What did you see instead?
noting to see

**Comment by waytai** [comment]
go run greeter_server/main.go
go run greeter_client/main.go 

2017/07/28 10:35:38 Greeting: Hello world
this example is ok

**Comment by waytai** [comment]
and I have change to grpc-go-1.4.x
go run server/server.go
go run client/client.go
and it's ok

**Comment by menghanl** [comment]
The problem is, we use `grpclog` in the example, and we changed the behavior of `grpclog` recently.

Please try `GRPC_GO_LOG_SEVERITY_LEVEL=INFO go run client/client.go` and see if that works.

Also, using `grpclog` in the example seems wrong, we should use non-grpclogs directly, like the go `log` package. We have #1395 to fix that.

**Comment by waytai** [comment]
thank you
