### ISSUE TITLE
Errors returned from InTapHandle are lost

### ISSUE THREAD

**Issue by stub42** [grpc/grpc-go#1436]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.5.1

### What version of Go are you using (`go version`)?

1.8.3

### What operating system (Linux, Windows, …) and version?

Ubuntu Linux, 16.04

### What did you do?

Returned a PermissionDenied gRPC error from the server's installed grpc.InTapHandle 

### What did you expect to see?

The returned error sent to the client, or at least an error that might help locate the source of the error.

### What did you see instead?

Client gets sent gibberish:

rpc error: code = Unavailable desc = stream terminated by RST_STREAM with error code: 7

Also, no error is reported on the server either. the Serve() method keeps serving silently.

**Comment by menghanl** [comment]
Returning RPC errors from InTapHandle is not intended. The functionality of InTapHandle is very limited, and the content of the error will be ignored. For your use case, please try interceptors.

The comment for ServerInHandle didn't make this clear. I have filed a PR (#1437) to update that.
Sorry for the confusion.

The behavior of Serve() is expected, though. Because only this one RPC failed, and the server is still serving other RPCs.
