### ISSUE TITLE
Max Age GOAWAY does not close connection if there are already zero streams

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#1462]
I believe the right fix would be to check in the controller, before we give up the mutex ([here](https://github.com/grpc/grpc-go/blob/master/transport/http2_server.go#L1072)), whether the number of active streams is zero.  Then change the if below to `if t.closeConn || noActiveStreams` to decide whether to close the transport.

**Comment by dfawley** [comment]
cc @ejona86

**Comment by bbeaudreault** [comment]
Thanks for tracking this down guys. One comment on the suggested fix at https://github.com/grpc/grpc-java/issues/3378#issuecomment-324776574:

Since it takes time for the goAway to reach the client and for it to process and stop sending new streams, I'd just like to bring up that the proposed fix could possibly cause errors for any streams that may be created in the space between measuring t.activeStreams() and the client getting and processing the goAway.

**Comment by dfawley** [comment]
grpc-go combats this by first sending a GOAWAY with MAX_INT32 as the stream ID.  Upon receiving that, the client should not initiate any new streams.  We know that the client received the first GOAWAY by sending a ping along with the GOAWAY and not triggering the second GOAWAY (or closure if no active streams were created yet) until the ping ack is received.

**Comment by ejona86** [comment]
@bbeaudreault, the code sends two GOAWAYS. The first one [is here](https://github.com/grpc/grpc-go/blob/69abda0/transport/http2_server.go#L1082). We send a PING after the first one and when the PING ACK arrives, we send the second. The second is when we would possibly close the connection.

**Comment by bbeaudreault** [comment]
Gotcha, thanks for the clarification. Sounds good!

**Comment by dfawley** [comment]
As part of this fix, we should see what the Go client is doing in the same situation -- will the client close the transport when it is done with it after having received any GOAWAY, or are we keeping it open until the server closes it?
