### ISSUE TITLE
pick first load balancer

### ISSUE THREAD

**Issue by sigmonsays** [grpc/grpc-go#1504]
### What version of gRPC are you using?
development version (master branch)

### What version of Go are you using (`go version`)?
go version go1.9 linux/amd64

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
Trying to use pick first load balancer with DialOption but there is no pick first balancer

### What did you expect to see?
pick first balancer

### What did you see instead?
missing pick first balancer from the docs https://godoc.org/google.golang.org/grpc

We should have a DialOption for specifying just a resolver or provide a PickFirst balancer exported. I see some pickfirst balancer in the code but its not exported. code is https://github.com/grpc/grpc-go/blob/master/balancer.go#L402

**Comment by menghanl** [comment]
The pickfirst balancer you found in `balancer.go` should work, the reason it's not exported is that we will remove it shortly as we are working on new resolver and balancer APIs (#1388).

With the new APIs, pickfirst will be the default balancer if no balancer is specified by the user, so you can use pickfirst with your own name resolver. We will either not export pickfirst at all, or move pickfirst into another package and export.

The new APIs were added into the repo, but the implementation is still in progress in [my branch](https://github.com/menghanl/grpc-go/tree/bar_new_implementation), and should be finished in a week or two.
(Note that the resolver scheme registration is also not working because of the same reason.)

Before that's available, if you really need a pickfirst balancer, you can have a small patch to export the pickfirst balancer in `balancer.go`.

Sorry for inconvenience.

**Comment by sigmonsays** [comment]
no worries, I have no issue making a pickfirst load balancer.
