### ISSUE TITLE
Use net.Buffers.WriteTo to reduce Syscall and memcopy

### ISSUE THREAD

**Issue by Zeymo** [grpc/grpc-go#1540]
support  +build go1.8

> On certain machines, for certain types of connections, this is
optimized into an OS-specific batch write operation (such as
 "writev")

[1] https://golang.org/pkg/net/#Buffers
[2] golang/go#13451
[3] https://github.com/golang/go/issues/21676

**Comment by dfawley** [comment]
Thanks for filing this.

We looked into `net.Buffers` a month or two ago, and IIRC, we discovered that only `net.TCPConn`s could end up taking advantage of this.  If transport-level security is employed, that's done with [TransportCredentials](https://godoc.org/google.golang.org/grpc/credentials#TransportCredentials), whose handshakers return a _wrapped_ `net.Conn`.  So I think to make this work, we'll need to do something higher-level.  I.e. if the `net.Conn` in use supports <some interface> then call that method for writes.  Then those wrapped `net.Conns` can implement that method and use `net.Buffers.WriteTo` when they write to the raw `net.TCPConn` they (presumably) wrap.

Oh, or we can wait for https://github.com/golang/go/issues/21676, which I just read (thanks for the link). 
 That looks promising.

**Comment by MakMukhi** [comment]
From what I understand the framer reuses it's internal buffer.
[code link 1](https://sourcegraph.com/github.com/golang/net@HEAD/-/blob/http2/frame.go#L286)
[code link 2](https://sourcegraph.com/github.com/golang/net@278c6cf336eb9139d63479da09da0cfb40fdc4c8/-/blob/http2/frame.go#L337)
[code link 3](https://sourcegraph.com/github.com/golang/net@278c6cf336eb9139d63479da09da0cfb40fdc4c8/-/blob/http2/frame.go#L351)

So the writer(a buffer in our case) that the framer writes to must copy the contents of this buffer and not keep a reference to it since it will be invalidated in the next call.

**Comment by dfawley** [comment]
So if we have to copy it at all, then what is happening inside the bufio.Writer is already ~optimal, right?

Maybe this should be a feature request for the http2 package, then, to support net.Buffers?

**Comment by dfawley** [comment]
We talked about this today and agreed that there is no way to make effective use of `net.Buffers.WriteTo()` -- this has to be done internal to the framer.  Note that if you are using any kind of transport encryption, because of your [3], above, the wrapped `net.Conn`'s `writev()` can't be used currently.  Also, with encryption, even once [3] is fixed, you may still need to either encrypt many smaller buffers in the wrapped `writev()` or concatenate them, which would require more `memcpy()`s.

To reduce the number of syscalls, you may take advantage of the new functionality in #1544.  We'll probably be increasing the default to 128KB (from 32KB) as well, as we think this setting will be optimal for most of our users.
