### ISSUE TITLE
Is balancer api v2 stable?

### ISSUE THREAD

**Issue by Civil** [grpc/grpc-go#1579]
I'm trying to write a client-side load balancer for gRPC, but in current version of docs it's a little bit confusing:
1. grpc.WithBalancer marked as deprecated with a comment "use grpc/balancer pkg instead"
2. "grpc/balancer" have almost no documentation about how to use it. And also marked as "Experimental"
3. grpc.WithBalancerBuilder marked as "is for testing only."with a suggestion to use ServiceConfig.
4. ServiceInfo struct marked as "This is EXPERIMENTAL and subject to change."

I'm confused about what should I use.

**Comment by menghanl** [comment]
The new balancer APIs are in progress (#1388).
There are multiple pending PRs (including #1515, #1551 and #1558) in review.

Eventually, users should user service config to pick the balancer to use. But as the work to support service config is still in progress, there needs to be some way to test balancer implementations. And that's what `grpc.WithBalancerBuilder` is for. We don't want users to use this in production (because there should be a way for service owners to switch balancer for its clients), so it's marked as testing only now.

We expect this new balancer APIs to be stable, but we will still mark it as "EXPERIMENTAL" for some time before we are confident enough.

As for what you should use right now:
Please use the new balancer APIs as in the [`balancer`](https://github.com/grpc/grpc-go/blob/master/balancer/balancer.go) package. The [`roundrobin` implementation](https://github.com/grpc/grpc-go/blob/master/balancer/roundrobin/roundrobin.go) and [test](https://github.com/grpc/grpc-go/blob/master/balancer/roundrobin/roundrobin_test.go) can work as an example of how to do it right now.

**Comment by xiang90** [comment]
one related question: how should we provide feedbacks on the new balancer API?

**Comment by Civil** [comment]
Am I right that currently specifying balancer with "ServiceConfig" is not implemented and for now I should use "WithBalancerBuilder" with the aim to switch to ServiceConfig as soon as corresponding PRs will be merged?

**Comment by menghanl** [comment]
@xiang90 You can send comments to the discussion [link](https://groups.google.com/forum/#!topic/grpc-io/rUDN7-cZvz8) for the [gRFC](https://github.com/grpc/proposal/pull/30). Or simply file an issue in our repo.

@Civil Yes.

**Comment by menghanl** [comment]
Closing this issue. Please track the process in #1388.
