### ISSUE TITLE
grpc occur an error using go func(){  // some request }() 

### ISSUE THREAD

**Issue by rookiejin** [grpc/grpc-go#1609]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
```
v 1.7.0 , I install it last week . 
go get -u google.golang.org/grpc
```
### What version of Go are you using (`go version`)?
```
☁  protobuf [master] go version
go version go1.9.1 darwin/amd64
```
### What operating system (Linux, Windows, …) and version?
```
MacOX 10.12.5 (16F73)
```

### What did you do?
I`m using a simple .protoc file like examples . 
after server run , I request from client made in grpc . 
I use 
```
for i := 0 ; i < 200 ; i ++ {
  go func() {
    conn, err := grpc.Dial("localhost:8800", grpc.WithInsecure())
    r, err := c.SetRequest(context.Background(), t)
  }()
}
```
But server received nothing , and client stoped with an error : 
```
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/xiahua/go #gosetup
/usr/local/go/bin/go build -i -o /private/var/folders/yd/yf56byhj0_1d3192f1rrbgxr0000gn/T/___main_go__1_ /Users/xiahua/go/src/protobuf/client/main.go #gosetup
/private/var/folders/yd/yf56byhj0_1d3192f1rrbgxr0000gn/T/___main_go__1_ #gosetup
2017/10/23 23:14:03 rpc error: code = Unavailable desc = all SubConns are in TransientFailure
```

I want to to test my server application with high Concurrent . but this run made error . 
I guess that My program error or grpc can`t support Concurrent ??? 

### What did you expect to see?

I want to see my application with high Concurrent but i test occur an error 

### What did you see instead?

request did`t send and occur an error msg 
```
2017/10/23 23:14:03 rpc error: code = Unavailable desc = all SubConns are in TransientFailure
```

I am puzzled about this . I`m waiting for your answers . Thank you for your help ~~~

**Comment by dfawley** [comment]
How many of these errors do you get?  If it's not many, than one or a few of your clients had an error connecting to the server.  This makes your RPC fail, because "fail fast" is the default behavior for gRPC.  You can fix this by doing `grpc.Dial(..., grpc.WithBlock())`, which will wait until a connection is established before proceeding, or `c.SetRequest(..., grpc.FailFast(false))`, which will make your RPC wait until the connection is ready before failing.  I recommend the latter unless you know you want fail-fast behavior, because if an intermittent problem happens in the middle of the connection, the latter would recover better.

Also, this is creating 200 simultaneous connections to the server.  Do you want this?  You can do many simultaneous streams over a single connection.  I.e.

```go
conn, err := grpc.Dial("localhost:8800", grpc.WithInsecure())
c := pb.New<Something>Client(conn)
for i := 0 ; i < 200 ; i ++ {
  go func() {
    r, err := c.SetRequest(context.Background(), t)
  }()
}
```

Also, I highly recommend setting a deadline on every RPC, always:

```go
ctx, cancel := context.WithTimeout(context.Background(), time.Second)
r, err := c.SetRequest(ctx, ...)
cancel()
```

**Comment by rookiejin** [comment]
Thankyou. only one error occured.  I will try your method tomorrow . It looks helperful .  thanks again . good night。

**Comment by dfawley** [comment]
Also, @MakMukhi noticed that you are also not closing the ClientConn in your example before it leaves scope.  You should make sure you call `ClientConn.Close()` when you are done with the connection, or it will leak resources.
