### ISSUE TITLE
Message level flow control support, similar to grpc-java 

### ISSUE THREAD

**Issue by eldadru** [grpc/grpc-go#1625]
I looked for a message level flow control mechanism in grpc-go, similar to this implementation of grpc-java:
https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/manualflowcontrol/ManualFlowControlServer.java

All I found was the option to configure the stream windows size:
https://github.com/grpc/grpc-go/blob/b3ed81a60ba74672ff49e0ba510b9a0c92e6a0e1/clientconn.go#L125

Am I missing something? do you plan to support this functionality in the future?
Thanks!

**Comment by dfawley** [comment]
I highly recommend not setting any window size options.  These settings are intended for performance tuning only, and are generally not necessary now that we automatically adapt the window size based on the connection's BDP.

This API in Java is an application-level control only, and probably isn't doing what you think it's doing.  It only controls when new messages are delivered to the application's asynchronous callbacks from grpc, and does not directly result in any push back on the server on a per-message basis.  E.g. if handling an RPC involves starting up an expensive background process, then a server may wish to disable auto-inbound flow control to delay the next message from the grpc library until it explicitly signals that it is ready for it, rather than when the stream message handler returns.

grpc-go's streaming API is blocking, so such a mechanism is not necessary.  The application chooses when to receive the messages by calling `Recv()` on the stream when it is ready.

**Comment by dfawley** [comment]
Follow-up to answer your real question:

If you want message-level flow-control with grpc, you will need to implement it yourself via fields in your request/response messages.  I.e. you can have the receiver send explicit "ack" signals back to the sender when it is ready for another message.

**Comment by eldadru** [comment]
@dfawley thanks!
