### ISSUE TITLE
go-grpc binary and memory usage should be lower

### ISSUE THREAD

**Issue by crosbymichael** [grpc/grpc-go#1655]
Simply importing the go-grpc code causes the binary to become much larger and memory usage is much larger than most would expect for a simple service at rest listening on a socket.

If you are running one service this may not seem like it is a big deal but after running 100s simple services they start to eat up memory like no other.

Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.7.2

### What version of Go are you using (`go version`)?
1.9.1

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
If possible, provide a recipe for reproducing the error.

Run the hello world `greeter_server` and look at binary size and memory footprint.

### What did you expect to see?
Smaller binary size and memory footprint for Pss

### What did you see instead?

`11M Nov  7 11:07 greeter_server`

```
Pss: 6324
AnonHugePages: 0
MMUPageSize: 148
Size: 114692
Rss: 7304
Anonymous: 1308
Shared_Hugetlb: 0
Swap: 0
Shared_Clean: 984
Shared_Dirty: 0
Private_Dirty: 6320
Locked: 0
Private_Clean: 0
Referenced: 7304
Private_Hugetlb: 0
SwapPss: 0
KernelPageSize: 148
```

**Comment by dfawley** [comment]
I ran a little experiment to determine whether this is caused by a constant overhead or if it's a per-server problem that will result in poor scaling.  I made the greeter_server accept a parameter for how many servers to run simultaneously ([branch](https://github.com/grpc/grpc-go/compare/master...dfawley:memprof?expand=1)).  Results:

```
$ for i in 1 2 5 10 25 50 100 250 500; do  { ./gs --num_servers=$i & pid=$!; sleep 10; awk 'BEGIN {i=0} /^Pss/ {i=i+$2} END { print "'$i:' ", i }' /proc/$pid/smaps; kill $pid; } 2>/dev/null; done
1:  7853
2:  8051
5:  8231
10:  8400
25:  8441
50:  8875
100:  9615
250:  11037
500:  13835
```

(The output lines represent the number of servers and the total Pss for the greeter_server process.)

This shows that any scaling problems could only happen if you run your services in different binaries.

Looking at all allocations, go's pprof only sees 34kB in greeter_server when a single server is started. This meshes well with the findings above.  I'm not sure where the 7MB is going, but I'm guessing it's entirely about holding the binary in memory.

As far as binary size, our external package dependencies are pretty minimal:

```
$ go list -f '{{ join .Deps "\n" }}' google.golang.org/grpc | grep -v google.golang.org/grpc
```

The only packages not in the standard library are a few things in golang.org/x/ and protobuf.

It looks like pulling in x/net/trace alone into an otherwise-small binary makes it ~10MB.  But even if we remove it (which we've considered doing), pulling in x/net/http2, which we cannot remove, the size goes up to ~8MB.

I don't think there's anything else we can do here.  If you have any other ideas, though, please let us know.
