### ISSUE TITLE
Re-enable coverage reporting

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#1676]
Coverage results should not block merging, as they did before.

Instructions:
https://coveralls.zendesk.com/hc/en-us/articles/201342809-Go

**Comment by easwars** [comment]
Some possibility avenues to look into for code coverage with GitHub Actions:
https://github.com/tj-actions/coverage-badge-go
https://gist.github.com/Harold2017/d98607f242659ca65e731c688cb92707
https://medium.com/synechron/how-to-set-up-a-test-coverage-threshold-in-go-and-github-167f69b940dc
https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/

**Comment by arvindbr8** [comment]
Discussed offline. I've made a few changes since the last push.

We had a cumulative problem of go test --cover only covering unit tests. It did not include coverage from e2e style tests. For this adding coverpkg=./... worked which includes coverage of tests

Since most of the changes are to the main module, it makes sense to limit the scope of presubmit check to only run go test --cover for the main module.

Ignored the following paths in codecov.

"test/"
"benchmark/"
"internal/testutils"
".*.pb.go"
