### ISSUE TITLE
Commit 3 weeks ago regressing dialing behavior

### ISSUE THREAD

**Issue by dzbarsky** [grpc/grpc-go#1760]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

Breaking commit is https://github.com/grpc/grpc-go/commit/ddbb27e5452a71cec377ce0df39daf4170d04a59

### What version of Go are you using (`go version`)?

1.8

### What operating system (Linux, Windows, …) and version?

Ubuntu 16.04

### What did you do?

Running our CI

### What did you expect to see?

Everything working as normal

### What did you see instead?

Some tests time out, there is no indication of data races so my best guess is somehow the change causes client conn to get stuck while dialing, or perhaps connectivity state is not updated properly. Unfortunately the commit is pretty big so I haven't been able to figure out anything else yet, but in any case this is a user-visible breaking change so it should probably be addressed. Any ideas?

@MakMukhi @dfawley

**Comment by dfawley** [comment]
Unless you were relying on the behavior of a client staying connected to an unresponsive server indefinitely, this shouldn't have changed anything user-visible.

Can you provide a pointer to tests that are failing?  Or what your tests are doing when they time out?  I.e. are they stuck in `Dial` or do they time out making RPCs or elsewhere?

**Comment by dzbarsky** [comment]
Unfortunately I can't provide the tests, but the gist of it is the tests bring up a bunch of services, health check them (i.e. send an rpc and get response). tear them down, and bring them up again (to test idempotency).

I doubt we were relying on client staying connected to an unresponsive server indefinitely given that the tests are timing out with this change and completing in time before.

Also this is an intermittent failure that occurs in CI at scale so I haven't spent much time trying to reproduce locally or figure out where exactly they are stuck, since that could take quite a while. I was hoping you folks would have some clues :)

If you have some logging variables I can set I'm happy to run this through our CI again and provide relevant output for failing tests.

**Comment by dfawley** [comment]
Without knowing more specifically what the tests are doing, I'm afraid we can't be of much help.  Even logging output will probably not help without knowing the intent of the test.  If you can dig a little more and provide some details as you discover them, that would be helpful.

That commit did have an intentional and potentially impactful change, which is that the client now kills a connection if the server's HTTP2 preface is not received within 20 seconds (the time scales up on reconnect attempts).  If RPCs were pending on that connection when it was killed, they will fail.

**Comment by dzbarsky** [comment]
Ah, that's promising! what's happening is our "service controller" process creates a health checking client for each service that is brought up, previously the client would continue connecting indefinitely until server came up. So now with this change it will fail permanently after 20 seconds or after some number of retries? 

If the above is correct, is there a way to disable this behavior?

**Comment by dfawley** [comment]
The client will never fail permanently.  RPCs assigned to the connection after the connection is established will fail if the handshake is not completed in time.  The client will then attempt a new connection.  I don't imagine this would be a problem unless you go through a proxy that accepts the connection but doesn't handshake on its own, and whose remote server isn't yet running.

This behavior cannot be disabled.  However, you can do one of two things:

1. Use `grpc.WithWaitForHandshake()` when you call `grpc.Dial`.  This will prevent RPCs from being assigned to the connection until the connection comes up.  If you also use `WithBlock()`, `Dial` will not return until at least one connection has finished handshaking.  Otherwise, you can use the connectivity API to block until the state is `Ready`.
1. Set `grpc.WaitForReady()` when performing calls; this should cause a single transparent retry to be performed, which I believe may be enough if this is indeed the cause.  Otherwise, manually retry this RPC until it succeeds or a timeout occurs.

**Comment by dzbarsky** [comment]
I tried using `grpc.WithWaitForHandshake()` but it did not help (also it is an experimental API so I'd like to avoid using it, we've been burned by these grpc experimental APIs before).  I checked the code and we actually do 3 retries on the healthcheck rpc, so i doubt `grpc.WaitForReady()` will help. Is it possible that there are unintentional impactful changes?

**Comment by dfawley** [comment]
It's always possible a bug was introduced, but note that all of grpc's existing tests passed without any meaningful modification as part of that commit.  To move forward, we really need a better understanding of your tests.  I.e. what operation are they performing that isn't working as expected?

**Comment by dzbarsky** [comment]
Well, we've discovered several times that our test coverage finds things that slip through your test coverage, so I don't necessarily buy the correctness of the change. I probably won't have time to debug this in detail in the foreseeable future, which is why I asked for some logging (so I can easily show you exactly which calls we are making to grpc). We might end up just hacking around this in the interest of time, which means your next release is potentially breaking your consumers.

**Comment by dzbarsky** [comment]
will check if this is fixed by https://github.com/grpc/grpc-go/commit/e975017b473bd9b2a3d5b23428a8549fe20b1153

**Comment by dzbarsky** [comment]
Ok I've got tests passing with some hacks around our own backoff policy. Our distribution for time spent inside backoff/sleep got worse though, especially at high percentiles which hurts even lower percentiles due to test sharding in CI. is there any way to tune the grpc backoff strategy?

**Comment by dfawley** [comment]
If you mean for reconnecting, the only thing you can tune is:

https://godoc.org/google.golang.org/grpc#WithBackoffMaxDelay

There's also [WithBackoffConfig](https://godoc.org/google.golang.org/grpc#WithBackoffConfig), but it only allows you to tweak that one setting.

How much worse is this now, and what do you mean by "high/low percentiles"?

**Comment by dfawley** [comment]
Hi @dzbarsky, have you seen these problems since patching https://github.com/grpc/grpc-go/commit/e975017b473bd9b2a3d5b23428a8549fe20b1153?

**Comment by dfawley** [comment]
@dzbarsky, any update on this?

**Comment by dzbarsky** [comment]
We had already worked around it on our end before your patch landed.
