### ISSUE TITLE
Fallback when load balancer goes down

### ISSUE THREAD

**Issue by slomek** [grpc/grpc-go#1845]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

The latest (from `master` branch).

### What version of Go are you using (`go version`)?

1.9.2

### What operating system (Linux, Windows, …) and version?

Linux

### What did you do?

I have two services (A and B) and a load balancer. When the load balancer goes down, A can still reach B because it remembers what the address is. Then B goes down and up again, starts under another address. Is there a way to configure load balancing so that in this case A uses some fallback and tries to access B using its DNS name? I'm running them inside Kubernetes and have been using service names as addresses beforehand.

If possible, provide a recipe for reproducing the error.

### What did you expect to see?

A to be able to connect to restarted B while load balancer is down.

### What did you see instead?

All SubConns are in Transient Failure, I'm unable to access B.

**Comment by dfawley** [comment]
@slomek,

What are you using for your load balancer?  With [grpclb](https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md#future-work-providing-both-server-and-balancer-results), this feature exists (it's implemented in Go but not other languages, hence the language about "Future Work").

If you're using your own load balancer protocol, you would need to implement this as a feature in your own custom resolver and balancer.  You can do this by having the [resolver](https://godoc.org/google.golang.org/grpc/resolver) emit [Addresses](https://godoc.org/google.golang.org/grpc/resolver#Address) with `Metadata` to indicate whether it's a fallback address.  The [balancer](https://godoc.org/google.golang.org/grpc/balancer) could then make use of this and the connectivity state in order to initiate direct connections to backends when the remote load balancer is unreachable.

Let me know if you have any more questions about this!
