### ISSUE TITLE
grpc-java channel similars in grpc-go

### ISSUE THREAD

**Issue by fengjingchao** [grpc/grpc-go#187]
Hi, @iamqizhao 

Sorry to raise the old issue again. I think I understand the problem better. We actually want something like what grpc-java channel provides:

https://github.com/grpc/grpc-java#channel

This is very useful for framework developers.

Basically, the framework should be agnostic to message definition by user. It needs to  handles the low level details, e.g. creating connection, finding address, flow control.

Ultimately, some generic client method calls is wanted
```
Client.Call( methodName, input message)
```
And interceptor method on server side
```
Intercept( methodName, input )
```

Can you think about it and let me know your thoughts?

**Comment by iamqizhao** [comment]
I still do not understand why you require an interceptor ... It was deliberate to abandon interceptor in our design.

**Comment by fengjingchao** [comment]
NP. Let me try to explain better.

In TCP socket, we send bytes:
```
send(b []byte)
```

Now we have protobuf and grpc, we want to send messages instead.
```
send(msg proto.Message)
```

The send(msg) API is provided by the framework, and message should be defined by user.

I wonder how can we do it efficiently without letting user define msg/rpc on their own?

**Comment by iamqizhao** [comment]
pls tell me how interceptors can help you address this issue?

We typically provide send(b []byte) to users instead of send(proto.Message)
which provides more flexibility and the framework should not care what
users will to transmit.

If you are thinking about the encoding efficiency (e.g., memory alloc and
string copying), I think it is the work of protobuf should take care of.
And I guess it is doable but it does not do because it will introduce
tremendous complexity regarding memory model.

**Comment by iamqizhao** [comment]
I guess calling Invoke(...) directly can fit your needs?
