### ISSUE TITLE
Server transport's context should come from Background() without WithCancel() to avoid lock contention

### ISSUE THREAD

**Issue by MakMukhi** [grpc/grpc-go#1918]
Cancelling a stream level context becomes a source of contention since it needs to clear itself from the parent's list of children.

**Comment by dfawley** [comment]
We can't do this without changing the stats handler API (which we need to do anyway because of an incompatibility with retry).

However, we can avoid this contention by deriving the transport context from `context.Background()` instead (without wrapping in a Cancel/Deadline context).  This will make canceling a child context not recurse into the parent.

**Comment by nvanbenschoten** [comment]
@dfawley can this be closed now that https://github.com/grpc/grpc-go/pull/2930 has merged?

**Comment by dfawley** [comment]
Yes @nvanbenschoten, thanks for catching that!
