### ISSUE TITLE
helloworld example old context "golang.org/x/net/context"

### ISSUE THREAD

**Issue by gertcuykens** [grpc/grpc-go#1949]
( master / Go 1.10 / OSX )

https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_client/main.go#L26

Please update example code to new context import, thx

**Comment by menghanl** [comment]
Since go 1.9, `x/net/context` is a type alias to `context`, so you should not notice any difference when using.

There has been discussion on switching to the new `context` package, see https://github.com/grpc/grpc-go/issues/711.
The short conclusion is, there's currently no plan to make this change, because this is a non-issue with type alias. And the change will cause breakage for people using go versions without type alias.

**Comment by gertcuykens** [comment]
ok thx closing
