### ISSUE TITLE
Possible race sending headers from server while receiving message over size limit

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc-go#1972]
This scenario, while unlikely, could lead to two concurrent calls to WriteHeader, which is not safe due to the unlocked checking and setting of the headerOK variable.

**Comment by a-robinson** [comment]
CockroachDB recently started using grpc-go v1.12.0 and have almost immediately seen this race happen in our race tests (https://github.com/cockroachdb/cockroach/issues/25641, https://github.com/cockroachdb/cockroach/issues/25643). https://github.com/grpc/grpc-go/commit/d0a21a334714105261074d48f3c598b0fa86affd appears to have introduced it, although it seems as though you're already aware.

Do you have a particular fix in mind beyond just re-adding the mutex or using an atomic compare-and-swap?

**Comment by a-robinson** [comment]
I've sent out https://github.com/grpc/grpc-go/pull/2090 as a possible fix, but I'm not at all attached to it if you guys have other plans.

**Comment by MakMukhi** [comment]
Hey @a-robinson, sorry about the regression. I've created a [fix](https://github.com/grpc/grpc-go/pull/2074) for this which is in review. I should've linked it here. I'll have our team prioritize its review.

Thanks for starting out #2090 , but unfortunately the problem is a bit more nuanced.
Since, reader goroutine can `WriteStatus` in parallel to `WriteHeader` happening in writer goroutine it can lead to multiple problems:

1. Race on `headerOk` and header metadata as you know.
2. Potentially sending header after status.

Adding the lock back doesn't have much performance impact(~500ns on 120us that it takes for a unary RPC) since it's a non contended lock.

**Comment by a-robinson** [comment]
Great to hear, thanks @MakMukhi!
