### ISSUE TITLE
SRV lookups with services not named "grpclb"

### ISSUE THREAD

**Issue by Xopherus** [grpc/grpc-go#2000]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.10

### What version of Go are you using (`go version`)?

1.9.3

### What operating system (Linux, Windows, …) and version?

Linux + OSX

### What did you do?

Provide a consul hostname as url to grpc ClientConn (e.g. https://my-service.service.consul)

### What did you expect to see?

I would expect the resolver to perform SRV lookup of the url if it can be parsed as *service._proto.domain* 

### What did you see instead?

The resolver passes "grpclb" as the *service*, "tcp" as *proto*, and uses the url as the *domain* in the call to net.LookupSRV. Why is [grpclb hardcoded as the service name in the lookup](https://github.com/grpc/grpc-go/blob/master/resolver/dns/dns_resolver.go#L197)? I'd like to use SRV lookups internally for multiple grpc projects but hard coding this service name will prevent us from doing so.

**Comment by lyuxuan** [comment]
Our current dns resolver is implemented to have native support for key grpc features like grpclb and service config. And we suggest that you implement your own balancer, which is basically copy and paste current dns resolver implementation and change the SRV lookup func to serve your needs.

**Comment by Xopherus** [comment]
Could you register a new resolver.Builder instead? Looks like we could do that and use [SetDefaultScheme](https://github.com/grpc/grpc-go/blob/master/resolver/resolver.go#L54) to set the custom resolver to be the new default. Alternatively I guess we could override the default dns scheme resolver, right?

Am I on the right track? If so do you have any tips for making a new builder / resolver? There's a lot of stuff under the hood of the dns resolver involving spawning goroutines to periodically resolving the addr that I'm not sure if my use case will require, but I'd rather not create more problems for myself by changing too much.

**Comment by lyuxuan** [comment]
Both options will work for you. However, I don't recommend overriding the default dns scheme resolver, since it's easy to be confusing later when your project gets larger and more complex that you don't know whether you are using the grpc native resolver or you own implementation. I think it's better to keep them separate, and use `SetDefualtScheme` to make your dns resolver to be the default resolver. BTW, our current default resolver is "passthrough", so you still need to `SetDefualtScheme` if you prefer overriding.

Our current implementation will resolve on demand (whenever a transport is down), and every 30mins. You can safely remove the every 30mins part, which is essentially the `freq` field in the builder, and related timer. In our code, timer has been used to trigger the first name resolution, once you remove it, you need to call `ResolveNow()` once to make the first resolution that start the whole proccess. 

Let us know if you have any problem during implementation. We are willing to help. Thanks!

**Comment by Xopherus** [comment]
> However, I don't recommend overriding the default dns scheme resolver, since it's easy to be confusing later when your project gets larger and more complex that you don't know whether you are using the grpc native resolver or you own implementation. I think it's better to keep them separate, and use SetDefualtScheme to make your dns resolver to be the default resolver. BTW, our current default resolver is "passthrough", so you still need to SetDefualtScheme if you prefer overriding.

Agreed @lyuxuan - I just did a deep dive into the resolver package and I think it makes way more sense to just create a new resolver which specifies a new scheme. Reading [naming.md](https://github.com/grpc/grpc/blob/master/doc/naming.md#name-syntax) made things a lot more clear.

I'll get back to you when I come up with a POC, hopefully tomorrow.

**Comment by lyuxuan** [comment]
Please let us know if you have any problem. Closing this now as it seems the original issue has been addressed.
