### ISSUE TITLE
New API: grpc.ContextServerTransportStream(context.Context)

### ISSUE THREAD

**Issue by skipor** [grpc/grpc-go#2016]
### Problem
Needed Header/Trailer sniffing in server interceptor. It could be done by wrapping `ServerTransportStream` and attaching it to the context using `NewContextWithServerTransportStream`. But there is no clear API access to existing `ServerTransportStream`.  There is `serverTransportStreamFromContext` but it's unexported.

Header sniffing `ServerTransportStream` may call `grpc.SetHeader` and e.t.c.  but it seems as hacky workaround.

**Comment by johanbrandhorst** [comment]
This API existed before https://github.com/grpc/grpc-go/pull/1904 and was removed.

**Comment by skipor** [comment]
That was `transport.StreamFromContext(ctx context.Context) (s *transport.Stream, ok bool)`. It was right desition to remove it, because it was using `transport.Stream`, but not new `grpc.ServerTransportStream`

**Comment by dfawley** [comment]
We can export this function, also as a temporary experimental feature, to unbreak you.  Note that I intend to redesign interceptors and stats handlers (#1805) in the next month or two, because of several deficiencies in their design.

**Comment by jhump** [comment]
FWIW, I didn't choose to export this function in the original PR because it was not really necessary.

You can access the methods of the `ServerTransportStream` just using the context in which it is stored, by passing the context into `grpc.SetHeader`, `grpc.SendHeader`, and `grpc.SetTrailer`. The only other method, for the stream name, is indirectly accessible via `grpc.MethodNameFromStream` (by creating a dummy`grpc.ServerStream` implementation whose `Context` method returns the context in question).

While not ideal, it was a way to minimize the exported surface area since it's experimental.
