### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by gertcuykens** [grpc/grpc-go#2029]
Probably 10 lightyears to late but
```
syntax = "proto3";

option go_package = ".../grpc-test";

package grpc_test;

message Response {
    string msg = 1;
}

message Request {
    string msg = 1;
}

service Example {
    rpc HelloWorld (Request) returns (Response) {}
    rpc HelloStream (stream Request) returns (stream Response) {}
}
```
```
type testServer struct{}
func (s testServer) HelloWorld(ctx context.Context, err *pb.Request) (*pb.Response, error) 
func (s *testServer) HelloStream(stream pb.Example_HelloStreamServer) error 
```
This makes my brain go in a dead lock

`Example_HelloStreamServer` vs `ExampleServer`

Is there really no other word then Server and Client for the streaming methods?

For example ...Streamer and ...Receiver or something instead of reuse of ...Server and ...Client naming?

**Comment by dfawley** [comment]
@gertcuykens _Both_ sides of a bi-di stream are Streamers and Receivers.  The type names used here are `<Service>_<Method>{Client,Server}`, because distinct types are needed for the two sides, one used by the client and one by the server.

I wouldn't argue that the names chosen are the best options possible, but it's also not possible to change them without breaking backward compatibility.
