### ISSUE TITLE
TLS failures in blocking Dial calls don't provide useful error messages

### ISSUE THREAD

**Issue by jmillikin-stripe** [grpc/grpc-go#2031]
### What version of gRPC are you using?
v1.9.2, but I've verified the same issue exists at the latest release (v1.11.3).

### What version of Go are you using (`go version`)?
1.10

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
I'm using a blocking Dial (`grpc.DialContext(..., grpc.WithBlock())`) to better account errors to the dial phase vs RPC calls. One of the backends had an unexpected CN in its TLS certificate, so the connection was failing. The error message returned from `DialContext` was only `context deadline exceeded`, and the useful errors were printed out into the info log.

I expected a blocking dial to return some indication of why it had failed, instead of only timing out. In particular, including the most recent transport error in the returned error value would be very useful for reporting connection problems.

Based on the conversation in https://github.com/grpc/grpc-go/pull/1855 it sounds like this behavior is intentional (or, at least, expected). Is there any way to either get access to the transport-layer errors, or somehow propagate them up into the returned error value?

The very useful error printed to the logs:
`W0427 21:43:33.738993   35711 clientconn.go:1167] grpc: addrConn.createTransport failed to connect to {badname.example.com 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for goodname.example.com, not badname.example.com". Reconnecting...`

The not very useful error returned from `DialContext`:
`W0427 21:43:33.773061   35711 handlers.go:180] Error dialing backend "badname.example.com": context deadline exceeded`

**Comment by jmillikin-stripe** [comment]
Also, https://github.com/grpc/grpc-go/issues/1917 documents that RPCs with fail-fast behavior will somehow get access to the underlying connection error. My system isn't using fail-fast because we want the gRPC library to retry past transient network issues.

**Comment by dfawley** [comment]
> I expected a blocking dial to return some indication of why it had failed, instead of only timing out. In particular, including the most recent transport error in the returned error value would be very useful for reporting connection problems.

The trouble is that this isn't really a "Dial" function, per se, despite the name.  `grpc.Dial` creates a `ClientConn` containing a managed pool of connections.  The blocking behavior of `Dial` is essentially to start up this pool and wait until a connection is established to one, or the deadline is met.  Authentication problems could be a misconfiguration of a server *or* a client, and they could resolve themselves transparently to the client (e.g. if the server restarts and receives new certs).  For this reason, we do not give up when authentication problems are encountered; we keep trying until the deadline is reached.

Changing the returned error may be possible, but it would be a behavior change.  Anyone checking for `Dial` returning `context.DeadlineExceeded` could be broken by that change, because `context.DeadlineExceeded` is a value and not an interface, so it cannot be extended.

The longer-term plan is to deprecate `Dial` and replace it with a `NewClient` that is both clearer in its behavior, and can have the semantics we prefer.

> My system isn't using fail-fast because we want the gRPC library to retry past transient network issues.

The difference between fail-fast (the default) and wait-for-ready RPCs is that WFR will remain *pending* through connection establishment errors.  Once they are assigned to a connection, RPCs that encounter transient network errors will still result in failures.  Auth failures are considered connection errors, so all your WFR RPCs will deadline exceed when this happens and you can't connect to any backend.

Note that our implementation of fail-fast used to be wrong ~5 months ago: it would not block when the client was in a "connecting" state, it would just fail.  Now that that is resolved, it may be suitable for your use case.

**Comment by dfawley** [comment]
No.  In that case, you'd want to do a non-blocking dial, and then poll connectivity state* until you get either `TransientFailure` or `Connected` (or some deadline).  On `TransientFailure`, we could then add a method to our connectivity state API similar to what Java has** to provide the relevant connection error.

*: https://godoc.org/google.golang.org/grpc#ClientConn.GetState and https://godoc.org/google.golang.org/grpc#ClientConn.WaitForStateChange
**: https://grpc.io/grpc-java/javadoc/io/grpc/ConnectivityStateInfo.html#getStatus--

**Comment by dfawley** [comment]
I created a PR (#2055) as a proof of concept for this.  In light of some offline discussions, I still plan on reworking it a bit.

**Comment by dfawley** [comment]
In light of #2266, if the TLS error is non-temporary, then using `WithBlock` in combination with `FailOnNonTempDialError` should get you the behavior you want.

**Comment by skipor** [comment]
Is there any progress? The problem greatly complicates the analysis of connection problems.

**Comment by dfawley** [comment]
Unfortunately, the TLS library doesn't make it readily apparent when a definite TLS error occurs vs. a transient connection error.  One idea: we could attempt to detect temporary network errors and call any other errors permanent.  (This would be done by the TLS wrapper in the `credentials` package.)

**Comment by sethp-nr** [comment]
I'm not sure the `FailOnNonTempDialError` interface is going to help us too much here. Without modifying the [`defer`](https://github.com/grpc/grpc-go/blob/fff75ae/clientconn.go#L216-L222) it's racy (the context deadline error will always overwrite any returned error, if it exists). It also presumes that the definition of `Temporary` is universal – and that any errors that _are_ `Temporary` are therefore uninteresting to callers.

re:

> In that case, you'd want to do a non-blocking dial, and then poll connectivity state* until you get either TransientFailure or Connected (or some deadline). On TransientFailure, we could then add a method to our connectivity state API similar to what Java has** to provide the relevant connection error.

I'm not sure I understand how what you're describing is different from `grpc.Block()`. What is the benefit to asking each user of the library to independently re-implement the same polling loop?

I understand that #3412 is an interface change. However, given the number of issues linked to this one from other go projects, it sounds like an interface that's desirable – would you consider something like that functionality behind a dial option?

**Comment by sethp-nr** [comment]
Also, per https://github.com/grpc/grpc-go/issues/3406#issuecomment-595567052 I believe this applies to more than just TLS misconfigurations – in Cluster API's case, we're providing a [custom dialer](https://github.com/kubernetes-sigs/cluster-api/blob/728fd4d/controlplane/kubeadm/internal/proxy/dial.go#L86) that might exhibit a number of different types of non-TLS-related failures, and we'd want to surface those to the caller (ourselves).

**Comment by dfawley** [comment]
> I'm not sure I understand how what you're describing is different from grpc.Block(). What is the benefit to asking each user of the library to independently re-implement the same polling loop?

Each user that wants to block until a connection is ready after client creation would need to do this, yes.  (We could make a utility function that does the polling, if that helps, but it should be pretty simple.)  This is not necessary, however.  Many applications will do a non-blocking `Dial` and just start attempting RPCs, seeing the connection errors at that time.  Note that being connected, while an important step in startup, is not necessarily an indication that the backend you've connected to is healthy and able to serve RPCs for the client.  And the connection may be lost in the future, so it's not really necessary to do a blocking dial in gRPC in general.  Clients will always need to be tolerant of RPC errors which may be connection errors.

> would you consider something like that functionality behind a dial option?

Potentially.  Longer-term I would like to get rid of `Dial` entirely (#1786), and not provide a blocking option at all for the replacement (`NewClient`).

> I believe this applies to more than just TLS misconfigurations – in Cluster API's case, we're providing a custom dialer  that might exhibit a number of different types of non-TLS-related failures, and we'd want to surface those to the caller (ourselves).

I think our guidance here would be the same.  If you consider the error a permanent one, then implement `Temporary() bool { return false }` and a blocking `Dial` will stop and return the error to the caller immediately.  Or don't do a blocking dial and inspect the errors returned when making the RPCs.

**Comment by sethp-nr** [comment]
At least in my testing, I could not get an RPC error to behave differently than the blocking dial – if I included a `context.WithTimeout` then all I'd get back from various RPCs is a context.DeadlineExceeded error. A complicating factor is that I don't actually hold a reference to the client, the etcd client interface I'm using does: I have no easy way to ask it about the state of the connection without a PR to their client library to expose that. As it stands, the shortest path I have to information about the health of the connection is the `err` value from either the RPC or Dial calls, which is always `context deadline exceeded`.

> Note that being connected, while an important step in startup, is not necessarily an indication that the backend you've connected to is healthy and able to serve RPCs for the client.

Agreed. However, it is a strong indication that my connection configuration embeds the _potential_ for successful communication: in the cases where that's not true, what I desire from the system is to help me understand what action I need to take, and `context deadline exceeded` is fairly sparse in that sense.

That's why I'm not sure I grok the `Temporary` axis – almost all connection failures are temporary, in my experience, but some of them require me to _do_ something before my next connection attempt succeeds. Connection refused sometimes implies I should go start that service back up. Read timeout sometimes suggests I misconfigured part of the network between my client and my server. DNS resolution failures are frequently because the name of the server I'm connecting to has a typo in it.

What I (&, it seems, others) think I want out of a networking API is exactly something like `grpc.Block()` – I want to make a call that, upon success, tells me that there is at least the possibility that my future RPCs will succeed & gives me good context on failure as to why. Returning a non-`Temporary` error immediately is a nice optimization, but even the `Temporary` ones are usually informative.

**Comment by sethp-nr** [comment]
I should add that I'm coming from a very short-lived context, in the sense that it's not a client with an indefinite lifespan like a long-running application. It's more like a CLI tool in that it's going to attempt to do one or two things with the RPC before shutting down – in the long-lived application case, I would strongly agree that `grpc.Block()` is _not_ what I want.

Tools like `etcdctl` & `crictl` don't really have a way to respond to failure, temporary or not, than "well, here's what happened, goodbye."

**Comment by sethp-nr** [comment]
>> would you consider something like that functionality behind a dial option?

> Potentially. Longer-term I would like to get rid of Dial entirely (#1786), and not provide a blocking option at all for the replacement (NewClient).

While we discuss the longer-term piece, I did put together a draft of what a dial option for this could look like: https://github.com/grpc/grpc-go/pull/3430

**Comment by dfawley** [comment]
I believe this issue can be closed:

Blocking dial calls can now use `WithReturnConnectionError` to see what happened after #3430, and RPCs should return the last connection error with #2777.

Let us know if there's anything else not covered by these changes.
