### ISSUE TITLE
Unclear on client retry support

### ISSUE THREAD

**Issue by jpbetz** [grpc/grpc-go#2061]
(context: we're [upgrading etcd to use the new grpc load balancer api](https://github.com/gyuho/etcd/tree/new-balancer-april-2018))

`FailFast` [godoc string](https://github.com/grpc/grpc-go/blob/d07538b1475ec5b0ac85319e4a6706b2d2d8cab7/rpc_util.go#L257-L259) suggests that the server can retry if it did not process the data:

> gRPC will not retry if data was written to the wire unless the server indicates it did not process the data

But it's unclear to me if or how a server could indicate this. The [docs](https://github.com/grpc/grpc-go/blob/0ebfac42d612337c9e7fb66cbe79fe25c6b818ca/codes/codes.go#L132-L134) for `codes.Unavailable` suggest it would be an appropriate way to indicate that the server "did not process data", but when I tried a simple case where a client sets the `grpc.FailFast(false)` call opt against a server that responds with `status.Errorf(codes.Unavailable, ...)`, I didn't observer any retry attempts. Also tried this with `grpc.WithBalancerName(roundrobin.Name)` dial opts to see if using the new load balancer makes any difference.

I also noticed in the discussion on https://github.com/grpc/grpc-go/issues/1585#issuecomment-337345911 that `FailFast` "is not supposed to retry", which seems to match the current implementation. And the status of https://github.com/grpc/proposal/blob/master/A6-client-retries.md is "ready for implementation", suggesting it is a WIP.

Am I correct in understanding that client retry is not yet available? If so, any recommendations/best practices/reference implementations for adding retry in the etcd client library?

grpc versIon: v1.11.3

cc @gyuho

**Comment by dfawley** [comment]
> But it's unclear to me if or how a server could indicate this.

@jpbetz We intuit this by seeing a GOAWAY with a stream ID that indicates the stream was not processed or by getting a RST_STREAM with error code of REFUSED_STREAM.  You cannot control the former; the latter can be controlled by setting https://godoc.org/google.golang.org/grpc#InTapHandle, but I would not recommend using this if possible.

Full retry support is in progress.  Unfortunately this has been going much slower than I had hoped, due to other demands on my time more than anything else.  I hope to have it done within 2-4 weeks.  Until it's fully ready, the best way to accomplish this would be by using interceptors.  There is a package that does this available here: https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/retry.

Let me know if you have any other questions about this.

**Comment by jpbetz** [comment]
Thanks @dfawley I'll have a look at interceptors, and sync back with you about retry support periodically, we'd like to switch over to that once it becomes available.
