### ISSUE TITLE
【Question】How to deal with proto denpdency in big repo?Copy or reference?

### ISSUE THREAD

**Issue by longXboy** [grpc/grpc-go#2152]
Our team uses a big mono repo like google. All microservices are a separate folder and placed in the same repo. The following shows the directory structure of one of our microservices: 
service/main/identify
├── cmd
├── conf
├── dao
├── http
├── model
├── proto<here is *.proto and *.pb.go>
├── rpc
│   ├── client
│   └── server
└── service

Previously we used HTTP communication. Now we plan to migrate to grpc, but we don't know how to store proto files in each microservices. Now we think of two options:
1, copy
Manage the proto file by copying. If service A depends on service B, then service A needs to copy all proto files of service B into their own directory and generate the code. There is no direct interdependence between each service. A little copying is better than a little dependency.
2, dependent
Each project exposes its own proto folder, relies on the proto folder, and manages permissions and builds through Bazel, but this greatly reduces Bazel's build speed when there are too many 
 proto dependencies.
So if it is yours, how will you choose? Or any other suggestions？

**Comment by menghanl** [comment]
I would prefer `dependent`.

Maintaining copies sounds like a bad idea to me because you will need to keep the copies consistent, which means, whenever you make a change, you will need to find all the copies and update those as well.

I'm not very familiar with Bazel, but it should be able to skip those proto files that are unchanged when building. And "Caching + incrementality" is listed as a benefit in this post: https://blog.bazel.build/2017/02/27/protocol-buffers.html. 

The bazel repo would be a better place for this question.

**Comment by longXboy** [comment]
@menghanl thanks a lot!
