### ISSUE TITLE
grpc-go should support reloading certificates and keys

### ISSUE THREAD

**Issue by vamshi-k** [grpc/grpc-go#2167]
### What version of gRPC are you using?
v1.12
### What version of Go are you using (`go version`)?
Go 1.10.3

### What operating system (Linux, Windows, …) and version?
Linux

https://github.com/grpc/grpc/issues/10528 - I see that this is handled in python, C etc... but not in go. Any plans to have this support ?

**Comment by lyuxuan** [comment]
I believe our credential API allows user to implement reloading certificates and keys functionality themselves. We'll discuss whether we plan to add support for this in our TLS implementation of the credential API and update here. Thanks!

**Comment by dfawley** [comment]
@cesarghali do you know anything about this?  Do you know if the Go TLS library supports the ability to reload?d

**Comment by cesarghali** [comment]
I can think of two scenarios:

* Reloading the credentials without reconnecting: (@dfawley correct me if I'm wrong) this cannot be done today with the current gRPC code because it requires a new TLS handshake. Note that if this is a server, all connections to all clients need to be re-handshaked.
* Reloading the credentials without with reconnecting but without terminating and rerunning the application binary: this can be done using the Go TLS library. Depending on your code but you might be able to do something like the suggestion in this [post](https://stackoverflow.com/questions/37473201/is-there-a-way-to-update-the-tls-certificates-in-a-net-http-server-without-any-d).

**Comment by dfawley** [comment]
It looks like the extent of support in C is to fetch the credentials for every new incomming connection attempt.  This would not mean that existing connections would be affected.

The same technique should be possible with the grpc credentials package as well.

**Comment by mastersingh24** [comment]
@dfawley  -  You are of course correct.  We actually do this today in one of my projects.  The `tls.Config` struct allows you to set a specific function `GetCertificate func(*ClientHelloInfo) (*Certificate, error)` for getting the `tls.Certificate`.  This function will always be called for new connections if you don't set the `Certificates` field.

**Comment by dfawley** [comment]
True.  It should be pretty straightforward to implement this and use it with grpc-go:

```go
grpc.DialContext(...,
  grpc.WithTransportCredentials(
    credentials.NewTLS(tls.Config{GetCertificate: myGetCertFunc, ...})))
```

I'm going to close this because I don't see much value in any additional support for this in grpc-go.  If I'm missing something, feel free to comment and we will reconsider.
