### ISSUE TITLE
resolver: make "dns" the default scheme

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#2168]
Some gRPC features relies on that information from DNS. To make those features work by default, we need to make "dns" the default scheme.

Features:
https://github.com/grpc/proposal/blob/master/A2-service-configs-in-dns.md
https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md

**Comment by dfawley** [comment]
Note:

This should be backward compatible as long as the user does not have a custom dialer, because the default dialer of `net.Dial("tcp", addr)` will behave indistinguishably from our DNS resolver for both `hostname[:port]` and `IP[:port]` uses.  We should _not_ use "dns" as the default if a custom dialer is used, however, as most users in that scenario will need the target passed through to their dialer verbatim.

**Comment by dfawley** [comment]
On second thought, it seems more prudent to avoid changing behavior, even if it's minor, due to backward compatibility.  When there is a `grpc.NewClient`, the default resolver for that path will be "dns".
