### ISSUE TITLE
Requests block under partitioning

### ISSUE THREAD

**Issue by jborlum** [grpc/grpc-go#2191]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
grpc-go v1.12.0

### What version of Go are you using (`go version`)?
go1.10.2 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Debian GNU/Linux 8.11 (jessie)

### What did you do?
We stream messages to the server using a normal stream. We establish the connection at system start, and cache a stream stream until either the client or server is shut down.

Establish connection:
```
    conn, err := grpc.Dial(addr,
        grpc.WithInsecure(),
        grpc.WithBackoffMaxDelay(time.Millisecond*500),
        grpc.WithKeepaliveParams(keepalive.ClientParameters{
            Time:                time.Millisecond * 500,
            Timeout:             time.Second * 2,
            PermitWithoutStream: true,
        }),
        grpc.WithDefaultCallOptions(
            grpc.MaxCallSendMsgSize(1024*1024),
            grpc.MaxCallRecvMsgSize(1024*1024),
            grpc.FailFast(true),
        ),
    )
```

Proto def:
`rpc Raft(stream RaftRequest) returns (RaftReply) {}`

Send msg:
```
    func (t *transport) StreamRaftMsg(msg *sifpb.RaftRequest) error {
        if t.raftClient == nil {
            rc, err := t.Raft(context.Background())
            if err != nil {
                return err
            }
            t.raftClient = rc
        }

        if err := t.raftClient.Send(msg); err != nil {
            t.closeStream()
            t.raftClient = nil
            return err
        }
        return nil
    }
```

### What did you expect to see?
Our expectation was that all requests to `StreamRaftMsg` would become unblocking,  when the connection becomes unhealthy - either by pings failing or the server shutting down.

We also have a number of unary rpc calls which we expect to either cancel already running requests or fail instantly when called while connection is down.

### What did you see instead?
If we take down the server everything works as we intended. Everything fails instantly. However if we introduce a partitioning, like a firewall rule, all rpc requests and stream creation calls become blocking or block until their context times out.

Example firewall rule applied on the server:
`sudo iptables -A OUTPUT -d <client-hostname> -j DROP`

These symptoms happen in production when a server become unstable. I've been able to work around this by buffering outgoing requests and have a separate go routine drain that buffer. The go routine would then handle the blocking. This is not a great solution. 

It is perfectly fine for us to drop packages when the connection is down. It is however crucial that all requests are fail fast if either the internal grpc buffer is full or the connection becomes unhealthy.

What are your suggestions for getting these properties?

**Comment by lyuxuan** [comment]
The root cause of this problem is actually not even at grpc layer, it's actually the golang `net` package. In short, grpc gets no update from the `net.Conn` when the other side set a firewall rule against it. And therefore, there's no way we could unblock from waiting for the events on the connection. Below are some details.

I've carried out the following experiments:
1. Starts a grpc server and sets `sudo iptables -A OUTPUT -d <client-hostname> -j DROP`. Then do a `net.Dial(...)` on the client side. It will block forever. 

2. Starts a grpc server and starts a grpc client. The RPCs are just fine. Then sets the firewall up. And now all the rpcs' progresses, will be blocked on the transport reader goroutinue ([here](https://github.com/grpc/grpc-go/blob/d35d006431ef290500616acf0c1a5640a07f53a7/transport/http2_client.go#L1136)) forever (or until deadline exceeds). Stack trace is below. And it shows that we are really blocked on the `net.(*conn).Read`.

```
goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x7f50d66daf00, 0x72, 0xc420061bb0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201b2198, 0x72, 0xffffffffffffff00, 0x8ef2a0, 0xad0618)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201b2198, 0xc4201c0000, 0x8000, 0x8000)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4201b2180, 0xc4201c0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4201b2180, 0xc4201c0000, 0x8000, 0x8000, 0x11, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4201bc000, 0xc4201c0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6a
bufio.(*Reader).Read(0xc4201b8060, 0xc4201da038, 0x9, 0x9, 0x9, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x8edba0, 0xc4201b8060, 0xc4201da038, 0x9, 0x9, 0x9, 0xc420061de8, 0x401afe, 0xc420061e97)
        /usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x8edba0, 0xc4201b8060, 0xc4201da038, 0x9, 0x9, 0xa14d3a3, 0xa14d3a3200c856c, 0x5b3ac4bc)
        /usr/local/go/src/io/io.go:327 +0x58
golang.org/x/net/http2.readFrameHeader(0xc4201da038, 0x9, 0x9, 0x8edba0, 0xc4201b8060, 0x0, 0xbec6cf0f00000000, 0xef06b7ad, 0xb163a0)
        /home/yuxuanli/go/src/golang.org/x/net/http2/frame.go:237 +0x7b
golang.org/x/net/http2.(*Framer).ReadFrame(0xc4201da000, 0xc4200c8560, 0xc4200c8560, 0x0, 0x0)
        /home/yuxuanli/go/src/golang.org/x/net/http2/frame.go:492 +0xa4
google.golang.org/grpc/transport.(*http2Client).reader(0xc4201de000)
        /home/yuxuanli/go/src/google.golang.org/grpc/transport/http2_client.go:1136 +0x125
created by google.golang.org/grpc/transport.newHTTP2Client
        /home/yuxuanli/go/src/google.golang.org/grpc/transport/http2_client.go:265 +0xb38
```

In your case, keepalives is helpful in detecting the problematic connection, so you may play around with the parameter values to achieve the quick detection you want. You may still need the extra goroutine to handle blocked calls. 

Please let us know if you have further questions. Thank you!

**Comment by jborlum** [comment]
Thank you so much for the reply. I've done some more digging and what we're seeing does not align with what you see. I'll try and elaborate.

It looks like the keepalives does tear down the connection as it should when the connection with the server becomes interrupted. In my case by adding an uni-directional firewall setting. The connection maintenance will try and reestablish the connection as expected. It will use the backoff logic defined here: https://github.com/grpc/grpc-go/blob/master/clientconn.go#L1235

This blocks on the backoff context created.

This can be seen here:
```
goroutine 5 [IO wait]:
internal/poll.runtime_pollWait(0x7fc3dae1be30, 0x77, 0xc420001200)
	/usr/local/Cellar/go/1.10.2/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420246518, 0x77, 0xc4200c2a00, 0xc4200c2ab0, 0x432704)
	/usr/local/Cellar/go/1.10.2/libexec/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitWrite(0xc420246518, 0xc4200c2a00, 0x28, 0x544d56)
	/usr/local/Cellar/go/1.10.2/libexec/src/internal/poll/fd_poll_runtime.go:94 +0x3d
internal/poll.(*FD).WaitWrite(0xc420246500, 0x8b88a8, 0x8f0fc0)
	/usr/local/Cellar/go/1.10.2/libexec/src/internal/poll/fd_unix.go:440 +0x37
net.(*netFD).connect(0xc420246500, 0x8f0fc0, 0xc42038a420, 0x0, 0x0, 0x8ec960, 0xc420258d40, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/fd_unix.go:152 +0x299
net.(*netFD).dial(0xc420246500, 0x8f0fc0, 0xc42038a420, 0x8f22e0, 0x0, 0x8f22e0, 0xc42032fc80, 0xc4200c2cd0, 0x55f6ce)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/sock_posix.go:142 +0xe9
net.socket(0x8f0fc0, 0xc42038a420, 0x897090, 0x3, 0x2, 0x1, 0x0, 0x0, 0x8f22e0, 0x0, ...)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/sock_posix.go:93 +0x1a6
net.internetSocket(0x8f0fc0, 0xc42038a420, 0x897090, 0x3, 0x8f22e0, 0x0, 0x8f22e0, 0xc42032fc80, 0x1, 0x0, ...)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/ipsock_posix.go:141 +0x129
net.doDialTCP(0x8f0fc0, 0xc42038a420, 0x897090, 0x3, 0x0, 0xc42032fc80, 0xb33ac0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/tcpsock_posix.go:62 +0xb9
net.dialTCP(0x8f0fc0, 0xc42038a420, 0x897090, 0x3, 0x0, 0xc42032fc80, 0x101fe9f379, 0xb16300, 0x4a810d86b)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/tcpsock_posix.go:58 +0xe4
net.dialSingle(0x8f0fc0, 0xc42038a420, 0xc420246480, 0x8ee940, 0xc42032fc80, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/dial.go:547 +0x375
net.dialSerial(0x8f0fc0, 0xc42038a420, 0xc420246480, 0xc42024d110, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/dial.go:515 +0x22d
net.(*Dialer).DialContext(0xc4200c31b8, 0x8f0fc0, 0xc42038a420, 0x897090, 0x3, 0x7ffe5b8f67cc, 0x14, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.10.2/libexec/src/net/dial.go:397 +0x678
google.golang.org/grpc.dialContext(0x8f0fc0, 0xc42038a420, 0x897090, 0x3, 0x7ffe5b8f67cc, 0x14, 0x0, 0x0, 0x0, 0xc42039c000)
	/Users/jborlum/gocode/src/google.golang.org/grpc/go17.go:38 +0xb3
google.golang.org/grpc.DialContext.func1(0x8f0fc0, 0xc42038a420, 0x7ffe5b8f67cc, 0x14, 0x0, 0x0, 0x8ec060, 0xc4200ccfb0)
	/Users/jborlum/gocode/src/google.golang.org/grpc/clientconn.go:542 +0x4d
google.golang.org/grpc.newProxyDialer.func1(0x8f0fc0, 0xc42038a420, 0x7ffe5b8f67cc, 0x14, 0xc4200c3350, 0x427fd9, 0xc42023a6b0, 0xc4200c3370)
	/Users/jborlum/gocode/src/google.golang.org/grpc/proxy.go:121 +0x12a
google.golang.org/grpc/transport.dial(0x8f0fc0, 0xc42038a420, 0xc4200ccff0, 0x7ffe5b8f67cc, 0x14, 0x5a, 0x140, 0x0, 0xc420394000)
	/Users/jborlum/gocode/src/google.golang.org/grpc/transport/http2_client.go:129 +0x5a
google.golang.org/grpc/transport.newHTTP2Client(0x8f0fc0, 0xc42038a420, 0x8f0f40, 0xc420330b00, 0x7ffe5b8f67cc, 0x14, 0x0, 0x0, 0x7ffe5b8f67cc, 0x14, ...)
	/Users/jborlum/gocode/src/google.golang.org/grpc/transport/http2_client.go:162 +0x101
google.golang.org/grpc/transport.NewClientTransport(0x8f0fc0, 0xc42038a420, 0x8f0f40, 0xc4200f0180, 0x7ffe5b8f67cc, 0x14, 0x0, 0x0, 0x7ffe5b8f67cc, 0x14, ...)
	/Users/jborlum/gocode/src/google.golang.org/grpc/transport/transport.go:506 +0xba
google.golang.org/grpc.(*addrConn).createTransport(0xc4201e6000, 0x2, 0x0, 0xbec6f82fd6cb58ff, 0xb9b5845ef, 0xb16300, 0xbec6f834aee00889, 0x101fe9f379, 0xb16300, 0xc420330ac0, ...)
	/Users/jborlum/gocode/src/google.golang.org/grpc/clientconn.go:1334 +0x301
google.golang.org/grpc.(*addrConn).resetTransport(0xc4201e6000, 0x8ee340, 0xc4200a0070)
	/Users/jborlum/gocode/src/google.golang.org/grpc/clientconn.go:1292 +0x4d9
google.golang.org/grpc.(*addrConn).transportMonitor(0xc4201e6000)
	/Users/jborlum/gocode/src/google.golang.org/grpc/clientconn.go:1477 +0x46b
google.golang.org/grpc.(*addrConn).connect.func1(0xc4201e6000)
	/Users/jborlum/gocode/src/google.golang.org/grpc/clientconn.go:999 +0x1b5
created by google.golang.org/grpc.(*addrConn).connect
	/Users/jborlum/gocode/src/google.golang.org/grpc/clientconn.go:990 +0xe1
```

All RPCs coming in while the connection is being reestablished are blocked by the blocking picker -Despite they are defined as failfast.

```
goroutine 20 [select]:
google.golang.org/grpc.(*pickerWrapper).pick(0xc4200f0140, 0x8f1020, 0xc4202cb7a0, 0xc4201df701, 0xc4202abaf0, 0x53090c, 0xc4201df7c0, 0x0, 0x0)
	/Users/jborlum/gocode/src/google.golang.org/grpc/picker_wrapper.go:124 +0x53e
google.golang.org/grpc.(*ClientConn).getTransport(0xc4201c8000, 0x8f1020, 0xc4202cb7a0, 0x8f0f01, 0xc4201df7c0, 0xc4202abb58, 0x410438, 0x120, 0x88a100)
	/Users/jborlum/gocode/src/google.golang.org/grpc/clientconn.go:1055 +0x53
google.golang.org/grpc.(*clientStream).newAttemptLocked(0xc420352000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8ec2a0, ...)
	/Users/jborlum/gocode/src/google.golang.org/grpc/stream.go:314 +0x139
google.golang.org/grpc.newClientStream(0x8f1020, 0xc4202cb7a0, 0xb15bc0, 0xc4201c8000, 0x8a272c, 0x19, 0xc4200cfa40, 0x3, 0x3, 0x0, ...)
	/Users/jborlum/gocode/src/google.golang.org/grpc/stream.go:274 +0x7dd
google.golang.org/grpc.invoke(0x8f0fa0, 0xc4200d6030, 0x8a272c, 0x19, 0x85bf80, 0xc4202cb710, 0x85ba80, 0xc4202d3280, 0xc4201c8000, 0xc4200cfa40, ...)
	/Users/jborlum/gocode/src/google.golang.org/grpc/call.go:66 +0x9c
google.golang.org/grpc.(*ClientConn).Invoke(0xc4201c8000, 0x8f0fa0, 0xc4200d6030, 0x8a272c, 0x19, 0x85bf80, 0xc4202cb710, 0x85ba80, 0xc4202d3280, 0x0, ...)
	/Users/jborlum/gocode/src/google.golang.org/grpc/call.go:37 +0x1b3
google.golang.org/grpc/examples/helloworld/helloworld.(*greeterClient).Write(0xc4200da048, 0x8f0fa0, 0xc4200d6030, 0xc4202cb710, 0x0, 0x0, 0x0, 0x0, 0x8ec2a0, 0xc420328460)
	/Users/jborlum/gocode/src/google.golang.org/grpc/examples/helloworld/helloworld/helloworld.pb.go:173 +0xd2
main.main.func2(0xc4200d6670, 0x8ee460, 0xc4200da048)
	/Users/jborlum/gocode/src/google.golang.org/grpc/examples/helloworld/greeter_client/main.go:67 +0x232
created by main.main
	/Users/jborlum/gocode/src/google.golang.org/grpc/examples/helloworld/greeter_client/main.go:62 +0x56f
```

Is this expected behaviour? It seems rather weird that failfast wouldn't fail these requests when no subconn is available. What would be a good workaround for solving this problem?

**Comment by lyuxuan** [comment]
It is actually the expected behavior. Documented [here](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md) that failfast RPC should not fail if the channel is in the `CONNECTING` stage. What you observed is grpc trying to reestablish the connection and get blocked on `net.Dial`, and the channel state is `CONNECTING` during this time, thus failfast RPC does not fail.

One way for you to work around this is before you issue an RPC, check the connectivity state by calling [`GetState()`](https://github.com/grpc/grpc-go/blob/a3e99ebee0a498c3093e9741d09c579f0fc34a7f/clientconn.go#L770) and do not fire the RPC if the connectivity state is `CONNECTING`. This is kind of tedious.

Another workaround is to pass in a custom dialer to grpc through [`WithDialer(...)`](https://github.com/grpc/grpc-go/blob/a3e99ebee0a498c3093e9741d09c579f0fc34a7f/clientconn.go#L367). What you can do is in your custom dialer, shorten the context timeout to what you see fit. Currently in grpc, we have a minimum [20s](https://github.com/grpc/grpc-go/blob/a3e99ebee0a498c3093e9741d09c579f0fc34a7f/clientconn.go#L55:2) (specified [here](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md)) timeout for dial. You may shorten the timeout to X seconds in your custom dialer, and your rpcs will only be blocked for at most X seconds.

Let us know if none of them works for you. Thank you!

**Comment by jborlum** [comment]
Unfortunately those are not good options for the behaviour we want to achieve. The system relying on these connections communicate thousands of requests per second, and introducing a delay on each request to malfunctioning node will cause the setup to grind to a halt.

In that case we will need to build an abstraction on top of gRPC which allows us to separate the concerns of sending the messages through the stream and adding the messages to a buffer / queue.

**Comment by dfawley** [comment]
If you want to control the behavior of the RPCs, another idea would be to write your own balancer.  You can use the simple [pick-first](https://github.com/grpc/grpc-go/blob/master/pickfirst.go) or [round robin](https://github.com/grpc/grpc-go/blob/master/balancer/roundrobin/roundrobin.go) implementations as a starting point if you don't need anything fancy.  Then, in `Pick`, instead of returning `balancer.ErrNoSubConnAvailable`, return `balancer.ErrTransientFailure` and fail-fast RPCs will fail immediately, or any other error for both fail-fast *and* wait-for-ready RPCs to fail immediately.  (See calling code ([ref](https://github.com/grpc/grpc-go/blob/40cd6b15e2880b88deb091b0fcb091694285fcb0/picker_wrapper.go#L138-L150)) for details.)  Note that this may have some adverse effects, e.g. the first RPCs dispatched to the connection will fail until a connection is established.

**Comment by jborlum** [comment]
I've tested it out dfawley. This is exactly the behaviour I was looking for. Thank you for the input.

**Comment by dfawley** [comment]
Glad to hear!  Let us know if you have any other questions or suggestions.
