### ISSUE TITLE
gRPC - Nginx connection is draining 

### ISSUE THREAD

**Issue by stephanustedy** [grpc/grpc-go#2197]
gRPC version : 
v1.10.0

go version : 
v1.10.2 

OS : 
Ubuntu 14.04

I try to use nginx.
setup is : 
- use service discovery, it will resolve to multiple server
- each server will have dedicated nginx and do grpc_pass to localhost

I get this error on the client `rpc error: code = Unavailable desc = the connection is draining`
what happens actually ? and how to fix this.

Thanks

**Comment by lyuxuan** [comment]
This error means the RPC fails because the connection is draining. This could be caused by server sending goaway or balancer removing the address. I think this issue involves grpc-web as you mention `grpc_pass`, you may open an issue in their [repo](https://github.com/grpc/grpc-web/issues/new) and reference this issue there. Thanks!

**Comment by stephanustedy** [comment]
okay.

will open issue and debug more.
Thanks!

**Comment by lyuxuan** [comment]
FYI #2205 seems relevant to this issue.
