### ISSUE TITLE
Why remove transport folder?

### ISSUE THREAD

**Issue by ShiningRush** [grpc/grpc-go#2222]
Our project now is failed on jenkins's CI,
It show error that 

> /go/src/github.com/micro/go-plugins/server/grpc/grpc.go:34:2: cannot find package "google.golang.org/grpc/transport"

Then i get a latest source from here, find that transport is indeed moved,
so i want to know how to fix the problem,
Any helps is appreciated.

**Comment by ShiningRush** [comment]
It looks like "/internal/transport" is a substitute,
Should i replace all of old transport's reference with it?

**Comment by dfawley** [comment]
@ShiningRush We moved this package to internal to prevent others from importing it, and to make room for new pluggable transports in gRPC.  Our transport package was never intended for external use.  Do you work on micro, or are you a user?  If the former, we would be interested in learning more about its use cases and finding another, more maintainable way to accomplish the same functionality.

**Comment by aaronbee** [comment]
I am a user and the use case I had for the transport package was the error types, such as `transport.ErrConnClosing`. We log errors that are unexpected, and we don't consider errors due to a connection closing unexpected. So we try to determine if an error should be logged by comparing it against `ErrConnClosing`.

**Comment by dfawley** [comment]
@aaronbee `transport.ErrConnClosing` isn't returned to users through the grpc API.  It is converted into a `status` package error instead.  Referencing it was not correct.  All errors returned by RPC methods must be implemented by the `status` package (or `io.EOF`).  (#531 tried to change that in 2016, but was rejected.)  It can be matched by checking for `status.Convert(err).Code()==codes.Unavailable`

**Comment by aaronbee** [comment]
@dfawley Got it. Thanks. My code no longer directly depends on the `transport` package.

**Comment by dfawley** [comment]
@ShiningRush do you know why micro does not use `grpc.NewServer`+`Server.Serve`, instead of trying to integrate with `transport` directly (essentially reimplementing `Serve` and below)?  That is the expected way of serving with grpc.

Note that @asim, who works on micro, is aware of this breakage per his [twitter post](https://twitter.com/chuhnk/status/1017396419907514369); I'm not sure about his plans to fix it, but it sounds like he intends to maintain a fork of grpc-go.

As a short-term workaround, you could vendor grpc-go to a version prior to e85134f.

**Comment by ShiningRush** [comment]
@dfawley Yes, i already did the workaround, and i also will follow the issue on micro's slack, thanks.
