### ISSUE TITLE
Using proxy

### ISSUE THREAD

**Issue by tianxiaoliang** [grpc/grpc-go#2243]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
latest
### What version of Go are you using (`go version`)?
1.8+
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?
M using WithDialer to apply  proxy, but as you see it is not a good practice, because the proxy address is fixed 127.0.0.1:30103. but I have to write a so much code to use a proxy. so should grpc-go support a simple WithProxy option which just accept address, timeout as input, if it makes sense I will implement
![image](https://user-images.githubusercontent.com/1610890/43306529-15e52970-91ae-11e8-9049-d14f8236b4f1.png)

**Comment by dfawley** [comment]
If you set HTTP_PROXY or HTTPS_PROXY in your environment, grpc-go will use that by default.  Does that work for you?

**Comment by tianxiaoliang** [comment]
Ok, that sounds easier, I will have a try

**Comment by tianxiaoliang** [comment]
![image](https://user-images.githubusercontent.com/1610890/43890418-4717479e-9bf9-11e8-8dbe-ab40b9fb7348.png)
as you see I am trying to use http proxy, it is no working

**Comment by tianxiaoliang** [comment]
so I must directly dial proxy port, but there is another problem, the client must tell me the target instead of IP:Port, the proxy will play the discovery role, which means it discovery ip port based on name and redirect
So I need client written like this 
grpc.DialContext(context.TODO(), "name", grpc.WithInsecure())

in that case I must use another option to specify the proxy IP and port, how?

**Comment by menghanl** [comment]
Try dialing to the server name, without setting custom dialer:
```go
grpc.DialContext(context.TODO(), "gRPCServer", grpc.WithInsecure())
```
(Note that even though the above works, I would suggest dialing to `"passthrough:///gRPCServer"` instead of just `"gRPCServer"`. The `"passthrough:///"` prefix is to pick the passthrough resolver. It's not necessary because passthrough is the default now. But the default may change to DNS in the future.)

Run the client with proxy environment variable set:
```sh
HTTP_PROXY="proxyIP:port" go run client.go
```

The behavior should be, a connection will be created to `"proxyIP:port"`, and then a HTTP connect request will be sent to the proxy, which should contain `"gRPCServer"` as the URL.
