### ISSUE TITLE
Perfect forwarding of calls on a server to a client?

### ISSUE THREAD

**Issue by EdSchouten** [grpc/grpc-go#2297]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.13.0 (168a6198bcb0ef175f7dacec0b8691fc141dc9b8)

### What version of Go are you using (`go version`)?

1.11

### What operating system (Linux, Windows, …) and version?

Linux

### What did you do?

I had to write a single GRPC server that receives RPCs for a handful of different services. Based on the service, some of the RPCs had to be handled locally, while others had to be forwarded to backend jobs in literal form.

### What did you expect to see?

That instances of `*Client` are type compatible with `*Server`. In other words, that I could call `Register*Server()` on an object returned by `New*Client()` to transparently forward RPCs.

### What did you see instead?

That they are not type compatible. In the end I had to write a bridge between the two like this:

https://github.com/EdSchouten/bazel-buildbarn/blob/master/pkg/builder/forwarding_build_queue.go

Would it be possible for protoc to automatically emit something like this?

**Comment by dfawley** [comment]
@EdSchouten,

That is an interesting idea!  Unfortunately, I don't think we will be able to do what you are asking for directly in the default grpc proto generator.  There is another option available: [`UnknownServiceHandler`](https://godoc.org/google.golang.org/grpc#UnknownServiceHandler).  This will be invoked for any unregistered methods on your server, and can be used to make your server act as a proxy for those methods.  This handler would call [`NewStream`](https://godoc.org/google.golang.org/grpc#ClientConn.NewStream) on the client and then forward all operations between that stream and the incoming stream.  The messages sent/received would need to be passed between the server and client internally as `[]byte`s, because otherwise the proto codec would need to know the message types.

To do this in a more type-safe way, I think it could be done in a separate protoc plugin.  It would essentially generate a function like this:
```go
func FooForwardingService(foopb.FooClient) foopb.FooServer
```
Where the implementation of each method performs a call on the client and forwards all the operations.  The reason I would rather have this in a separate plugin is because the code would not be needed by the majority of our users.

Thanks for the suggestion, and let us know if you need help with anything else!
