### ISSUE TITLE
GRPC stream fail rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by ciscoxll** [grpc/grpc-go#2443]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
`grpc-go 1.14 `
### What version of Go are you using (`go version`)?
`go version go1.11`

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
If possible, provide a recipe for reproducing the error.

I use the grpc client to send the request to the same server at the same time, during which the service is normal, but after the restart, the master reports this error.

If you restart the master server, it works fine.

### What did you expect to see?

Will not report this error
### What did you see instead?

server
```
2018/11/06 20:25:11 server.go:1005: [error] [server] create FetchDDLInfo stream for worker 172.16.30.67:10085 fail rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.16.30.67:10085: connect: connection refused"
2018/11/06 20:25:11 server.go:1020: [info] [server] receive DDLInfo task:"test" schema:"shard_db" table:"shard_table" DDLs:"USE `shard_db`; ALTER TABLE `shard_db`.`shard_table` ADD COLUMN `abc` int(11);"  from worker 172.16.30.64:10083
2018/11/06 20:25:11 server.go:1025: [error] [server] try to sync sharding DDL for task test, but with no workers
2018/11/06 20:25:14 server.go:922: [info] [server] update task workers to map[test:[172.16.30.64:10083]]
2018/11/06 20:25:16 server.go:1005: [error] [server] create FetchDDLInfo stream for worker 172.16.30.67:10085 fail rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.16.30.67:10085: connect: connection refused"
2018/11/06 20:25:16 server.go:1020: [info] [server] receive DDLInfo task:"test" schema:"shard_db" table:"shard_table" DDLs:"USE `shard_db`; ALTER TABLE `shard_db`.`shard_table` ADD COLUMN `abc` int(11);"  from worker 172.16.30.64:10083
2018/11/06 20:25:16 server.go:1060: [info] [server] sharding DDL test-`shard_db`.`shard_table` synced
2018/11/06 20:25:16 server.go:1119: [info] [server] requesting 172.16.30.64:10083 to execute DDL (with ID test-`shard_db`.`shard_table`)
2018/11/06 20:25:16 server.go:1068: [info] [server] resolve DDL lock test-`shard_db`.`shard_table` successfully, remove it
2018/11/06 20:25:21 server.go:1005: [error] [server] create FetchDDLInfo stream for worker 172.16.30.67:10085 fail rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.16.30.67:10085: connect: connection refused"
```

client
```
RPC stream fail rpc error: code = Unavailable desc = transport is closing
```

**Comment by lyuxuan** [comment]
Can you turn on logging on both client and server side? i.e. using environment variable `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info`.

Also can you provide a code snippet to show your set up? Thanks!

**Comment by ciscoxll** [comment]
I have solved it because of the problem caused by the null pointer. thank you @lyuxuan.

**Comment by mattthym** [comment]
Could you please elaborate on what you had to do to fix this issue. I've got the same rpc error and do not know what causes it.

**Comment by menghanl** [comment]
`transport is closing` is usually caused by peer, turning on logging reveals what the cause is:
https://github.com/grpc/grpc-go/blob/master/README.md#the-rpc-failed-with-error-code--unavailable-desc--transport-is-closing

**Comment by mattthym** [comment]
Thanks for your response!
I'm currently rewriting a client I wrote in Python in Go. When trying to connect to the server without the right credentials with python, it returned the rpc error "origin authentication failed", so I guess I just expected a similar error to be returned with Go and now I am a little puzzled about why the rpc error in Go is the same if the server is down and if the connection failed on handshaking...

**Comment by mattthym** [comment]
Thanks for your response.
The server did expect authentication, but I knowingly tried to connect using `WithInsecure()` and expected the error to be similar to the one in python where you get a different error, depending on if the server is down or if it expects authentication. 
I managed to achieve what I wanted, so thanks again.

**Comment by jesushernandez** [comment]
Hey, I just wanted to briefly detail how we solved this issue recently, just in case someone else has a similar setup and is facing these 'intermittent' connection drops

Our environment (prior to solving the issue):
 - grpc v1.18 (in both client and server)
 - golang v1.10.8 (in both client and server)
 - connection from a k8s cluster in GCP to an instance in AWS. No meshes in between, but there's a network load balancer routing traffic to our AWS instance. This turned out to be the key part.
 - unary RPCs
 - no keepalive settings configured in neither client nor server
 - server and client verbose logging:

```
GRPC_TRACE=all
GRPC_VERBOSITY=DEBUG
GRPC_GO_LOG_VERBOSITY_LEVEL=2
GRPC_GO_LOG_SEVERITY_LEVEL=info
```

What we were experiencing were random `transport is closing` errors on the client when making unary RPCs to our server (usually after ~5 minutes of inactivity). Most of the time, our server would not even get the request by the client, so we thought some other component in between should be causing the connections to be closed.

After some digging, we eventually found this section in the [AWS network load balancer docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout):
> For each request that a client makes through a Network Load Balancer, the state of that connection is tracked. The connection is terminated by the target. If no data is sent through the connection by either the client or target for longer than the idle timeout, the connection is closed. If a client sends data after the idle timeout period elapses, it receives a TCP RST packet to indicate that the connection is no longer valid.

> Elastic Load Balancing sets the idle timeout value to 350 seconds. You cannot modify this value. Your targets can use TCP keepalive packets to reset the idle timeout.

Immediately after seeing this, we decided to start using keepalive pings from the client. You can easily enable this on the client as a dial option (`keepalive.ClientParameters`) and on the server (`grpc.KeepaliveEnforcementPolicy`) as a server option which enforces clients to comply with the keepalive policy.

Since we just use *unary* RPCs, we had to set `PermitWithoutStream=true`, so that the client sends keepalive pings while not streaming. We also made sure that the enforcement policy has a `KeepaliveEnforcementPolicy.MinTime=1 * time.Minute` (it *has* to be lower than the LB's connection idle timeout of 350s) and the client would submit keepalive pings every 2 minutes (`ClientParameters.Time=2 * time.Minute`). As long as `Time > MinTime`, we're [good](https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L683)!

We applied the changes to our clients and server (as others have mentioned, the clients must comply with the server policy!) and the `transport is closing` issue is now totally gone, as the client will keep the connections alive.
