### ISSUE TITLE
Add error details support

### ISSUE THREAD

**Issue by ch3rub1m** [grpc/grpc-go#2453]
Do you guys consider add the `errdetails` package to offer some functions for [`google/rpc/error_details.proto`](https://github.com/google/go-genproto/blob/master/googleapis/rpc/errdetails/error_details.pb.go)?

It may look like as below:
```
s := status.New(codes.InvalidArgument, "Invalid Argument.")
d := errdetails.NewBadRequest(...)
s := s.withDetails(d)
```

**Comment by dfawley** [comment]
If you are asking for something to help you construct `errdetails` proto messages more easily, that is outside the scope of grpc, and something like it would belong more naturally in the [googleapis repo](https://github.com/google/go-genproto/tree/master/googleapis) where the messages are defined.  I would suggest opening an issue there.

**Comment by ch3rub1m** [comment]
@dfawley There are three generated packages in [`go-genproto`](https://github.com/google/go-genproto/tree/master/googleapis/rpc) for error handling. They are `status`, `codes` and `errdetails`.

However, there are just two packages `status` and `codes` in `grpc` to help constructing `Status` and `Code` proto messages except `errdetails`.

I think if `status` and `codes` package are inside the scope of grpc, the `errdetails` package should be treated equally.

**Comment by dfawley** [comment]
@ch3rub1m Good point.  The difference is that gRPC error details are based upon `Status` messages, whereas the details within a `Status` are arbitrary proto messages.  `errdetails` protos are not specifically supported.  Also note that the `status` package is not designed to help you work with generic `Status` proto messages more easily, and `codes` exists mostly because it predates the google/go-genproto repo.

**Comment by ch3rub1m** [comment]
@dfawley Ok. Thanks for your reply. I will write a third party library to handle this situation.
