### ISSUE TITLE
Use the connection ctx timeout when creating the transport or allow a way to specify deadline

### ISSUE THREAD

**Issue by mauriciogg** [grpc/grpc-go#2466]
I'm running gRPC 1.16 with Go 1.11 on linux.

Currently one can specify a a dial timeout (via DialContext). However, it is only respected for the underlying net.Dial call. There is no way to set a custom timeout for the connection initialization. The client will close the connection if the preface is not received after 20s (minConnectTimeout).

**Comment by dfawley** [comment]
@mauriciogg - The connection establishment timeout will actually be given more than 20s after the backoff has increased beyond that amount.  (20s is the *lower* bound.)  `WithBackoffMaxDelay` or `WithBackoffConfig` can be used to configure this, but by default the maximum backoff is 2 minutes.

Otherwise, no, there is no way to configure it currently.  What kind of scenario are you encountering where 20s is insufficient, and what kind of problems are you encountering?

**Comment by mauriciogg** [comment]
Thanks for the quick reply. My connections weren't going through the retry/backoff logic because I'm connecting through a proxy that forwards the connections to the actual server. That is the connection always succeeds if it can connect to the proxy, but if the server is not up the http2 layer of the connection establishment was timing out in cases where the server was taking a while to come up. The simplest workaround was to only start listening for client connections in the proxy until we have a connection to the server. That way everything follows the right logic. Closing the issue.
