### ISSUE TITLE
Feature:  Using naked request response

### ISSUE THREAD

**Issue by egonelbre** [grpc/grpc-go#2479]
Using the request/response types in services is a bit awkward in Go, it would look slightly nicer with unpacking the request and response structs.

For example:

```
service Database {
  rpc Put(PutRequest) returns (EmptyResponse);
  rpc Get(GetRequest) returns (GetResponse);
}

message PutRequest {
  string path = 1;
  bytes  data = 2;
}

message EmptyResponse {}

message GetRequest {
  string path = 1;
}

message GetResponse {
  bytes  data = 1;
}
```

It currently generates interfaces for:

```
func (Database) Put(ctx context.Context, req *PutRequest) (*EmptyResponse, error) { ... }
func (Database) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) { ... }
```

However it would look nicer and clearer as:

```
func (Database) Put(ctx context.Context, path string, data []byte) error { ... }
func (Database) Get(ctx context.Context, path string) ([]byte, error) { ... }
```

_I understand that it wouldn't work for all scenarios, however it would be much nicer code for common cases._

_First requested in https://github.com/gogo/protobuf/issues/517_

**Proposal**

Version "Option". Based on a option instead of generating the "wrapped" interfaces, generate the "unwrapped" versions.

Version "Wrapped". Based on a option additionally generate a Register that takes the unwrapped service implementation as an argument.

**Alternatives**

These wrappers can be written manually, which adds overhead.

Separate wrapper generator could be used on top of protobuf, which would be somewhat annoying to use.

**Comment by egonelbre** [comment]
Sorry, made the issue against the wrong respository. This probably should be in golang/protobuf instead.

**Comment by dfawley** [comment]
This is an interesting idea, but I don't believe it is feasible, unfortunately.  A service definition should have only one canonical form, and generating different forms based on command-line flags or options in the proto file could be problematic.  Also, a change to your request/response messages would result in new function signatures being generated, which would cause backward compatibility problems when there otherwise would be none.  I'm sorry we won't be able to do this, but thank you for submitting your idea.
