### ISSUE TITLE
ErrConnClosing becomes nil in loopyWriter.run

### ISSUE THREAD

**Issue by krhubert** [grpc/grpc-go#2557]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

`1.12` but the pbm exists in the newest release

### What version of Go are you using (`go version`)?

`go version go1.11.4 linux/amd64`

### What operating system (Linux, Windows, …) and version?

`linux/mac`

### What did you do?

When grpc client & server are in different docker container it might happen that over the time connection will be closed because of docker network configuration.

When I connect to grpc api and get stream in return I want to reconnect on any error, but for `ErrConnClose` type of error, reconnection is impossible because I don't know if a stream was closed due to issue or a normal close. 

To read more about it: https://github.com/mesg-foundation/core/issues/549#issuecomment-451342555

Is a way to distinguish this type of error and reconnect with api stream?

**Comment by canguler** [comment]
Hi @krhubert,

To better understand the problem, I have a couple of questions:

1. What do you mean by a normal close? Can you give an example?
2. You mentioned "... reconnect on any error ...". What function's errors are we talking about? Error from the function establishing the stream, or error from Recv function?

**Comment by dfawley** [comment]
@krhubert do you have any updates here?

**Comment by krhubert** [comment]
Hi,

I can't reproduce it easily right now, so to close for now

**Comment by NicolasMahe** [comment]
The problem we had was because of the timeout default configuration of docker network.
[By default, Docker drops idle connection after 15 mins](https://success.docker.com/article/ipvs-connection-timeout-issue).
gRPC server is configured by default to ping on an idle connection after 2h. This config is fine because most systems drop idle connection only after 2h.
https://github.com/grpc/grpc-go/blob/6086f8d68f83701fc00a9549c30c2b48861c8a6f/keepalive/keepalive.go#L65-L68

Setting a shorter time than 15min in gRPC server fix the problem.

I also recommend to set the same config in gRPC clients (by default the client config is set to infinity). The reason is, if the client never try to publish a message on the connection, it will never knows that the connection drops, and will not get any error.
