### ISSUE TITLE
compression and message size check conflict

### ISSUE THREAD

**Issue by eau-u4f** [grpc/grpc-go#2616]
### What version of gRPC are you using?
v1.16.0

### What version of Go are you using (`go version`)?
1.11.5

### What operating system (Linux, Windows, …) and version?
OpenBSD 6.4 / Ubuntu 18.04.1 LTS

### What did you do?
When enabling compression, grpc reject compressed message, while the size is under limit.
looking at the code 
https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L638

recvAndDecompress() function check AFTER decompression.

it is not clear if it is a transport limit or a memory process resource limit (not sure how to phrase it), if the later, the problem already happens (hence making the check useless) memory is _already_ used since it's already decompressed in memory (does it try to prevent malicious/bad behavior from the client?)

in the case of a wire size limit, then the check should be before the decompression of the data and p.recvMsg() already check for the message wire size.

I'll prepare a PR in the following hours with fix proposal for the issue.

### What did you expect to see?

no resource exhaustion since the compressed data are way smaller than the limit.

### What did you see instead?

resource exhaustion when receiving a message compressed (and hence smaller than my limit).

**Comment by menghanl** [comment]
Thanks for filing the bug.

The message limit is to protect receiver's memory, so the safe solution is to check both (wire length and after decompression).

Note that because of the limitation of the API, this only works with the new [encoding.Compressor](https://godoc.org/google.golang.org/grpc/encoding#Compressor), not the old [grpc.Decompressor](https://godoc.org/google.golang.org/grpc#Decompressor).

**Comment by eau-io** [comment]
yep, legacy grpc.Decompressor is basically a black box so cannot be touched,  you've submitted the PR i was about to send with io.LimitReader() 👍.
So I don't have to send it.
