### ISSUE TITLE
Provide a mechanism to Listen on an address of the same format as Dial

### ISSUE THREAD

**Issue by kylelemons** [grpc/grpc-go#2648]
When using `grpc.Dial` I can give it a format of the same type as those that I give to a C++ server (notably, a unix domain socket with the `unix:` prefix), but there is no mechanism for doing the same thing for a server.  We need to be able to pass the same flag to a Go gRPC server that we pass to a C++ gRPC server in order to control how it listens (for example, we need to select between unix domain socket, localhost-bound `:0` or public-bound fixed-port), and thus we are writing our own parser for targets.  This is less than ideal, and we would like to be able to use some public interface (whether it's `func Listen(target) Listener` in the `grpc` package or simply a target parser in the new, experimental `resolver` package) instead of having to roll our own or copy/pasting unexported code.

**Comment by dfawley** [comment]
A target string intended for Dial is not a meaningful thing to use in a Listen API.  E.g. what do we do for `"dns://example.com"`?  This would be a problematic API.

We also would prefer not to expose an API for parsing target schemes at this time - #2403.

I would recommend either using `url.Parse` to parse target URIs or use a different format for your flags and construct the target strings instead of trying to parse them.
