### ISSUE TITLE
Getting to the actual error after Send failure with bidirectional streaming

### ISSUE THREAD

**Issue by egonelbre** [grpc/grpc-go#2683]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

latest master, commit 77ce7bc228475a8f28dc50a9d74ac4994fc019e7

### What version of Go are you using (`go version`)?

go 1.12

### What operating system (Linux, Windows, …) and version?

Windows 10

### What did you do?

Given an error on `Send` the recommendation is to use `CloseAndRecv` however given message buffering this won't actually get the actual error that happened. Currently it's not returning the "processing failed" message.

```
package main

import (
	"context"
	"errors"
	"fmt"
	"net"
	"time"

	"google.golang.org/grpc"
	pb "google.golang.org/grpc/examples/features/proto/echo"
)

func runClient(addr string) {
	conn, err := grpc.Dial(addr, grpc.WithInsecure(), grpc.WithBlock())
	check(err)
	defer conn.Close()

	client := pb.NewEchoClient(conn)

	stream, err := client.BidirectionalStreamingEcho(context.TODO())
	check(err)

	time.Sleep(5 * time.Second)
	err = stream.Send(&pb.EchoRequest{})
	if err != nil {
		closeErr := stream.CloseSend()
		recvMsg, recvErr := stream.Recv()
		fmt.Println("CLIENT", err, closeErr, recvErr, recvMsg)
	}
	fmt.Println("SENT")
}

type Server struct{}

func (s *Server) BidirectionalStreamingEcho(stream pb.Echo_BidirectionalStreamingEchoServer) error {
	err1 := stream.Send(&pb.EchoResponse{Message: "1"})
	err2 := stream.Send(&pb.EchoResponse{Message: "1"})
	fmt.Println("SERVER", err1, err2)

	return errors.New("processing failed")
}

// irrelevant code

func main() {
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	check(err)

	go runClient(listener.Addr().String())
	runServer(listener)
}

func runServer(listener net.Listener) {
	server := grpc.NewServer()
	pb.RegisterEchoServer(server, &Server{})
	err := server.Serve(listener)
	check(err)
}

func check(err error) { if err != nil { panic(err) } }

func (s *Server) UnaryEcho(ctx context.Context, req *pb.EchoRequest) (*pb.EchoResponse, error) { return nil, errors.New("processing failed") }
func (s *Server) ServerStreamingEcho(req *pb.EchoRequest, stream pb.Echo_ServerStreamingEchoServer) error { return errors.New("processing failed") }
func (s *Server) ClientStreamingEcho(pb.Echo_ClientStreamingEchoServer) error { return errors.New("processing failed") }
```

### What did you expect to see?

I would expect there to be a way to get to the server error without having to parse manually each message, set read timeouts etc.

As far as I know there are two scenarios that you want to do given a send error:

1. When there's io.EOF and it's expected part of the protocol (as in expected sequence of messages) for server to close at some point, in which case you should read all errors until it's closed. This seems to be what the current API is designed for.
2. When there's an error and it's not part of the expected part of the protocol, in that case the server might have terminated with an error, while still having some other messages in the buffer. In this case when the `Send` is required to succeed it does not make sense to go through all the messages until you find the error.

Given the 2. scenario even if you implement the loop:

```
sendErr := stream.Send()
if sendErr != nil {
    for {
        closeErr := stream.CloseSend()
        _, recvErr := stream.Recv()
        if recvErr != nil {
            return combineErrors(sendErr, closeErr, recvErr)
        }
    }
}
```

It doesn't necessarily terminate properly, because if there was an error in sending, but server keeps sending messages... then it wouldn't ever terminate. So it would require some additional closing of the underlying connection.

So given scenario 2. what is the expected order of calls to handle and capture server error properly?

**Comment by lyuxuan** [comment]
Hi @egonelbre, thanks for the detailed context.

First, the impression that

> Given an error on Send the recommendation is to use CloseAndRecv

is not quite right. `CloseAndRecv` is called when stream is healthy (no error has occurred), the RPC is of client streaming type, and the client has finished sending all the stuffs. 

If send errors, then the RPC has finished (i.e stream is done). To get the RPC status, you need to do `Recv` until an error occurs. You may get multiple messages before you get the error due to buffering. And the final RPC status may be OK, in which case, those buffered messages are valid and need to be processed. If the final status is not OK, some user applications may want to ignore all the buffered messages, but it totally depends on the application. Therefore, we need to deliver the buffered messages in order and error at last for all possible use cases.

For your question, given scenario 2, the server will not be able to send more messages because the stream is finished once send errors. So the case you mentioned about non-terminating loop won't happen.

Please let us know if you have any further question. Thanks!

**Comment by egonelbre** [comment]
Ah ok, just to mirror back how I understood it, if `Send` fails (any error) the connection is guaranteed not to read more data from the socket (i.e. only what's in the buffers) for that particular Server. And this property also holds for a misbehaving Server.

If that is the case, yeah, then there isn't a problem with Recv in a loop until completed. Thanks.

**Comment by lyuxuan** [comment]
I'd like to make some clarification here. `Send` fails means the stream is done (you can think of it as HTTP2 stream is done). However the transport connection is still up, if the failure wasn't caused by connection failure.

There are two concepts here, connection and stream. gRPC is based on HTTP2, which multiplexes multiple streams on the same transport connection. Each RPC corresponds to a stream, so when the RPC finishes the stream finishes. 

For your question,

> Or in other words my main concern is either server/client being able to keep connection open indefinitely when I write such loop.

once server handler returns, your loop will exit.

**Comment by egonelbre** [comment]
@lyuxuan I'm implementing P2P and I do not know what the server is actually doing and it could be someone malicious. So I have no control over whether the server handler returns or not. I only know about the agreed upon protocol, if that is violated then the connection should be torn down with as much information as possible.

**Comment by lyuxuan** [comment]
In that case, once you got enough info, you can just close the `ClientConn` you created through `Dial`. It will tear down all connections set up through the `Dial`.

**Comment by egonelbre** [comment]
Yeah, that could work. Close the underlying connection, then recv until the buffer is completely, parsed, although not sure whether the ClientConn supports it, have to test it. However I'm failing to find a way to shut it down on the server side, i.e. after detecting an unwanted client, feels like I'm missing something obvious. I guess I can capture the stream into a context via a context somehow, I'll take a deeper look tomorrow. Thanks.
