### ISSUE TITLE
Does it have to be the same connection?

### ISSUE THREAD

**Issue by guanw** [grpc/grpc-go#2808]
In https://github.com/grpc/grpc-go/blob/master/balancer/roundrobin/roundrobin_test.go the test `TestBackendsRoundRobin` makes sure the connections are up by keeping calling server until it hits every available server at least once.

Why does it have to do it this way? What if I make sure simple connection to the individual peer that's created from `startTestServers` are up and just create new connections and load balancing on the new ones? I would expect that to pass tests.

But based on my observation, the second approach failed and it seems the steps at first paragraph is necessary. Isn't this a bug or something?

**Comment by menghanl** [comment]
Roundrobin balancer only uses READY connections.
If the connections to 3 addresses are in state `{ip1: READY, ip2: READY, ip3: TRANSIENT_FAILURE}`, the balancer will do round-robin between `[ip1, ip2]` because `ip3` is not READY.
Do this behavior match your expectation?

---

The check in the test is purely for the test.
The test needs to make sure the balancer actually picks in all READY connections. Instead of getting the currently READY connections (not a stable state because it's different when a new connection get READY), it waits for all connections to be READY (so the state becomes relatively stable) and then checks balancer's picking results.

**Comment by guanw** [comment]
Got it. Thanks for the detailed explanation.

**Comment by 90wukai** [comment]
change
