### ISSUE TITLE
Implement hedging, from gRFC A6

### ISSUE THREAD

**Issue by jhump** [grpc/grpc-go#2823]
The gRFC for client retries added a second kind of retry support named "hedging":
https://github.com/grpc/proposal/blob/master/A6-client-retries.md#hedging-policy

This allows an RPC that is not yet complete to be automatically retried, which can help reduce tail latency. (The call must obviously be idempotent; the client uses the response for whichever RPC returns first.)

The retry support added to the Go runtime does not yet support this; it only supports failure-based retries (i.e. retry after RPC completes with an error code).

I didn't see any other issue related to this. Is the hedging proposal "on hold" or has it just not been implemented here? Is there a time table for adding it?

**Comment by canguler** [comment]
I believe it is not implemented in any language because of some concerns about the design. There is no plan to implement it until its design is reviewed.

**Comment by jhump** [comment]
@canguler, how can one get visibility into that process?

According to the gRFC (https://github.com/grpc/proposal/blob/master/A6-client-retries.md), it is "ready to implement":

> * Status: Ready for Implementation
> * Implementation: In progress for all language stacks

And, in fact, much of it _has_ already been implemented -- the retry policy and retry throttling policy.

Maybe the gRFC process needs an amendment that if a proposal is only accepted and implemented _in part_, the original proposal should be split so that status of the parts can be tracked independently. So, based on what you're saying, I'd love to see a separate gRFC for hedging that adequately describes its status as "pending" (or whatever the right term is). That way this one only shows the agreed-upon parts as "implementation in progress"...

**Comment by dfawley** [comment]
@jhump,

Yes, retry has been implemented in all 3 of the main languages, but hedging support has been put on hold in all due to priorities and also concerns about that part of the design.

All those suggestions are fair.  I think the best forum for this kind of discussion would be our community meetings if you can make it.  However, I just looked and we haven't held one in quite a long time (!).  I pinged some folks around here and have been assured there will be (at least) one in June.  If you can't make the next community meeting in June, I would suggest starting a thread on the grpc-io mailing list: https://groups.google.com/forum/#!forum/grpc-io

We've also had some discussions recently about making sure the official documentation (https://github.com/grpc/grpc/tree/master/doc) is updated when gRFCs are approved (or implemented) - the proposal repo is a changelog and shouldn't need to be used to learn what gRPC can do or how it works.

**Comment by dfawley** [comment]
Update: apparently gRPC-Java has implemented hedging.

**Comment by jhump** [comment]
LOL. I remember discussing hedging with @ejona86 pretty early on -- maybe even before it was called gRPC. (When I worked at Square, I worked on their bespoke proto-based RPC system, which very intentionally had support for hedging to support multi-region fail-overs when databases in a given datacenter were just slow.)

One thing we did at Square, that wasn't in the gRFC, was to actually limit hedging downstream. So headers would be supplied so that a server could tell that it was acting on a hedge request. If it was, it would disable its own hedging for outbound RPCs in the course of handling that request, to prevent exponential query amplification in leaf services in the event that hedging were configured all the way down the stack.

Anyhow, not surprised it's been implemented in grpc-java, and I'm sure he had something to do with it :P
