### ISSUE TITLE
ClientConnection target is not the same as BuildOptions.Target.Endpoint

### ISSUE THREAD

**Issue by krzysztofdrys** [grpc/grpc-go#2838]
I am not sure if this is a question or a bug report. Please advise me, if I was using some undocumented feature. Long story short: https://github.com/grpc/grpc-go/pull/2803 broke our grpclb integration.

### What version of gRPC are you using?
1.21

### What version of Go are you using (`go version`)?
go version go1.12 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Linux

We implemented our own grpclb server on top of k8s. This works on production with grpc versions 1.20 and prior. 

We call services likes this:
```
conn := grpc.Dial("grpclb://user-service:8080/")
```
Before we call any service we register builder/resolver to grpc schema.

In grpc 1.20, in the situation above, our grpclb server would receive:
```
 &lbpb.LoadBalanceRequest{
		LoadBalanceRequestType: &lbpb.LoadBalanceRequest_InitialRequest{
			InitialRequest: &lbpb.InitialLoadBalanceRequest{
				Name: "grpclb://user-service:8080/"
			},
		},
	}
```

This is becase as per [this code](https://github.com/shipwallet/som/blob/264aa7b1d8bcd8614ac3906c82d38e90c5858dbc/vendor/google.golang.org/grpc/balancer/grpclb/grpclb.go#L159) `lbBalancer` would receive `"grpclb://user-service:8080/"` as target.

Now after https://github.com/grpc/grpc-go/pull/2803, instead of client connection target, `lbBalancer` receives `opt.Target.Endpoint`. Which, in our case is an empty string.

So our integration with grpclb is broken in 1.21 and I am wondering, what I can do about this. Questions:

1. Shouldn't target be set to `opt.Target.Authority` instead of `opt.Target.Endpoint`? 
2. If https://github.com/grpc/grpc-go/pull/2803 works as intended, how can I overwrite target, which is passed `lbBalancer`?

**Comment by lyuxuan** [comment]
#2803 works as intended. The [name](https://github.com/grpc/grpc-proto/blob/54e1b97ab0fe96a32ce1af14c9a6bf1df178ccf5/grpc/lb/v1/load_balancer.proto#L52) of the load balanced service should be the endpoint instead of authority. As described [here](https://github.com/grpc/grpc/blob/master/doc/naming.md#resolver-plugins), authority is the entity contacted by the resolver to get name resolution.

For your second question, there is no viable way to overwrite the target.

May I know why you have a target with empty endpoint, which is not normal? Since scheme and authority are intended for resolver name resolution and the endpoint is the part to identify the service host.

Also +@menghanl Did we have any special consideration for target with authority specified? Since before the change, we used to preserve the whole target string if authority is not empty.

**Comment by menghanl** [comment]
There was no special consideration for authority. The dial target was expected to be `scheme:///service-name`, and `InitialLoadBalanceRequest.Name` will be set to `service-name`.
The problem (or more like a bug in the previous version) is, [target parsing](https://github.com/grpc/grpc-go/commit/4748a040c895a974ae1820670e90205252fbafc3#diff-0e70b7ea1171441ec36ee9d30efad690L148) isn't complete, so `"grpclb://service-name/"` will be sent as is.

@krzysztofdrys 
How hard is it for you to change your dial target to `"grpclb:///user-service:8080"`, and also change your grpclb server to handle just `"user-service:8080"`?

Another fix would be to revert the behavior change in grpclb. If `target.authority` is not empty, reassemble the original target string and sent in it `InitialLoadBalanceRequest`.

**Comment by krzysztofdrys** [comment]
Thanks for the replies. So yes, it seems that our problems are because of misreading [spec](https://github.com/grpc/grpc/blob/master/doc/naming.md) and a bug in the previous versions of grpc-go , as described by @menghanl.

> How hard is it for you to change your dial target to "grpclb:///user-service:8080", and also change your grpclb server to handle just "user-service:8080"?

The second part is very easy. The first part is updating approximately 150 configuration files. So manageable. :-)

Anyway, thanks for helping me to understand this issue. I will close this issue.

Having say all this, I wonder if `grpc.Dial` shouldn't be more strict about validating it's input. Right now `grpc.Dial("grpclb://user-service:8080")` will not return an error, but will fail to connect with error "Error while dialing dial tcp: address grpclb://user-service:8080: too many colons in address". Shouldn't it return an error saying that the target is incorrect? 

The same error is logged for `grpc.Dial("grpclb:user-service:8080")`, though it could be argued that this target is correct. Because authority is optional, right? 

On the other hand, when I use ` grpclb:///user-service:8080/` a target, it will use `user-service:8080/` as the endpoint. Is this correct?

To be clear: I now understand that an issue described in this ticket is not a problem in `grpc-go` package. We ended up using `grpclb://user-service:8080/`after trying various formats. Unfortunately, we didn't try `grpclb:///user-service:8080`. I am just thinking that this experience could be improved with more strict validation.

**Comment by menghanl** [comment]
> Having say all this, I wonder if `grpc.Dial` shouldn't be more strict about validating it's input. Right now `grpc.Dial("grpclb://user-service:8080")` will not return an error, but will fail to connect with error "Error while dialing dial tcp: address grpclb://user-service:8080: too many colons in address". Shouldn't it return an error saying that the target is incorrect?

Some background:
1. Resolvers are registered for schemes, and are picked by schemes ([link to example](https://github.com/grpc/grpc-go/tree/master/examples/features/name_resolving)).
   - If you dial to `dns:///example.com`, `dns` resolver will be picked to resolve `example.com`.
1. We can only pick resolvers with valid schemes. *Invalid cases* include
   1. valid target string, but non-registered scheme
      - e.g. `grpclb:///user-service:8080`, which parses to `{Scheme: "grpclb", Endpoint: "user-service:8080"}`, but no resolver is registered for scheme `"grpclb"`.
   1. invalid target string (that doesn't parse)
      - e.g. `grpclb://user-service:8080`, we will fail to parse this target
1. There's a [default scheme](https://godoc.org/google.golang.org/grpc/resolver#SetDefaultScheme) to use when we cannot get a valid one. It's something called `"passthrough"`, which pass the original string back as name resolution result.
   - The default is important because we want to make targets like `localhost:8080` work by default. This will fail to parse, but it works.
   - We wanted to make the default `"dns"`, but couldn't because of backward compatibility.

Because of these, it's hard to fail `Dial` because target parsing fails.
Maybe the default resolver is set, and the target, though doesn't parse for us, makes sense for them.

> The same error is logged for `grpc.Dial("grpclb:user-service:8080")`, though it could be argued that this target is correct. Because authority is optional, right?

This is a known issue. We have [plans](https://github.com/grpc/grpc-go/issues/1911#issuecomment-397429803), but didn't have time to implement it.

> On the other hand, when I use `grpclb:///user-service:8080/` a target, it will use `user-service:8080/` as the endpoint. Is this correct?

Similar to what I mentioned: `user-service:8080/` may make sense for a user registered resolver.
Another example is `grpclb:///user-service:8080/sub-service?some-argument=123`. ¯\_(ツ)_/¯
