### ISSUE TITLE
WithAuthority call option

### ISSUE THREAD

**Issue by mpuncel** [grpc/grpc-go#2858]
### Use case(s) - what problem will this feature solve?
We use gRPC in a service mesh in which our applications connect insecurely to a sidecar on the local network and the sidecar does the work of initiating TLS to backends and load balancing/routing based on the `:authority` pseudo header.

Right now we're a bit limited by the fact that `:authority` can only be selected at dial time. We'd benefit from a call option for setting `:authority` so that we can use a single `ClientConn` to the sidecar and choose which backend we're talking to dynamically.

### Proposed Solution
add a `WithAuthority` call option similar to the dial option

### Alternatives Considered
N/A
### Additional Context
N/A

**Comment by lyuxuan** [comment]
For your use case, you can just create a custom metadata and pass the authority info to the side car. Please take a look at the example [here](https://github.com/grpc/grpc-go/tree/master/examples/features/metadata) if you are not familiar with custom metadata.

The authority is a connection level concept instead of call level, so a call option to modify authority does not sound right. Please let us know if the custom metadata solve your problem and if you need any help. Thanks!

**Comment by mpuncel** [comment]
@lyuxuan My understanding is that it's not possible to override `:authority` using metadata: https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_client.go#L450. Am I missing something?

**Comment by lyuxuan** [comment]
I was suggesting creating a custom metadata field to contain the authority info you need, not overriding the `:authority` field. I am under the impression that you only need the authority info instead of needing the `:authority` field to contain that info. You may need to change your side car code to read that specific custom metadata field in order to get the authority info, rather than reading the `:authority` field.
