### ISSUE TITLE
RemoveSubConn won't work when stream exists

### ISSUE THREAD

**Issue by wi-cuckoo** [grpc/grpc-go#2897]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
v1.21.1
### What version of Go are you using (`go version`)?
1.12.5
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
I have a  client to receive message from server all the time with a server-side stream, and I developed a name resolver and a load balancer.  when resolved addresses changed, I hope to re-establish connection with new address, as well as remove old connection with RemoveSubConn call. Also I will retry to re-establish the stream in application-level

### What did you expect to see?
I hope the old connection should be closed anyway. then the stream.Recv() call will return error,  so I can create stream with new connection 

### What did you see instead?
I use `netstat -atn` to check, but found the old connection won't be closed. When I remove stream code in my application, anything works as expected, the old closed!

**Comment by dfawley** [comment]
@wi-cuckoo this is by design.  Once your existing stream completes, the connection will be closed.  There are two ways to mitigate this if your client eventually has more open connections than you'd like:

1. Use a deadline on your RPCs, even long-lived streaming RPCs.

2. Set MaxConnectionAge on your server, with a finite MaxConnectionAgeGrace ([ref](https://godoc.org/google.golang.org/grpc/keepalive#ServerParameters)).

(These are both good things to do even without this behavior.)

Let us know if you have any other questions or concerns.  Thanks!
