### ISSUE TITLE
Provide a way to seed Context in a `grpc.Server`

### ISSUE THREAD

**Issue by mwitkow-io** [grpc/grpc-go#298]
Currently the `http2_server.go` instantiates a new context per Stream inside:
`func (t *http2Server) operateHeaders`.

```go
	if hDec.state.timeoutSet {
		s.ctx, s.cancel = context.WithTimeout(context.TODO(), hDec.state.timeout)
	} else {
		s.ctx, s.cancel = context.WithCancel(context.TODO())
	}
```

It would be great to have some flexibility around how the context is bootstrapped. For example:

```go
Grpc = grpc.NewServer(grpc.InitialContext(myContext))
```

Is this a feature request worth considering?

**Comment by iamqizhao** [comment]
This sounds a good idea. I can see this provides a way to cancel all the rpcs on server side, which is probably needed in some scenarios. Let me see if there is any hidden side effect. If there is no, I can probably make it happen very quickly.

**Comment by dsymonds** [comment]
Why would one want to cancel all the RPCs on the server side?

This seems somewhat at odds with a Context's purpose, which is meant to be request scoped. A whole server scoped thing is broader than that.

@mwitkow-io: What's your actual use case?

**Comment by iamqizhao** [comment]
Testing is the only use case I imagine for now ...

**Comment by dsymonds** [comment]
Well, we shouldn't design general APIs if they're only going to be used for testing.

**Comment by iamqizhao** [comment]
Sure thing. Just brainstorming, a client could talk to N equivalent servers to finish a transaction consisting of a number of rpcs ASAP. It will start the transaction with N server in parallel. Once it finishes the transaction with a particular server (the fastest one), it can notify the other servers via a side channel so that the other servers can cancel all the pending rpcs which are still under processing to save power. 

Let's see if @mwitkow-io has any real use cases.

**Comment by dsymonds** [comment]
For that, a client cancelling *their* context should definitely signal (where possible) to the server, and terminate the server-side context tree. But that should happen automatically and shouldn't require anything like this issue's feature.

**Comment by iamqizhao** [comment]
You are right, but i) this approach might not be bandwidth efficient because the client will send a cancellation for each particular rpc ending up with a lot of http2 frames to server. With this feature, the client can send much less; ii) As mentioned in Jeff Dean's paper "The tail at scale"(http://research.google.com/pubs/pub40801.html), the fastest server could try to notify the other servers to cancel the transactions directly. Then this feature could be used to achieve that when a slow server receives the notification from the fastest server.

**Comment by mwitkow-io** [comment]
So, we'd like to use `Context` as a way of passing into Service implementation all the things necessary to process the RPC in it's scope. 

We currently have two use cases: one an auth object and the server hop-tracing.

For the first one we'd like to parametrize the `Context` with a `RpcAuther` that will handle things like: answering whether the given Bearer Token is good enough for this call, propagate it to other RPC calls. 

If we could seed the `RpcAuther` into the server's `Context`, it would be immediately available to all Services handled by that server.

Second use case is tracing what the name of the server handling the request is, so we can have an easy to use trace of which backends were used for this particular query. Again, it seems like it would make sure to have this available in the Context.

The alternative is to inject the values into the struct that implements the Service. This unfortunately leads to boilerplate (you need a `rpcAuther` and a `serverName` field in every Service that you implement, and we have tons).

**Comment by dsymonds** [comment]
Remember that a context and its values are meant to be request-scoped. Your `RpcAuther` sounds like it is server-wide, and you want to hang it off context as a convenience. That's not what context is for. Pass it around to your server objects as required, probably during initialisation. The same thing applies to the name of the server, which is also not request-scoped.

Inserting magic values into contexts to avoid a bit of boilerplate is not okay.

**Comment by mwitkow-io** [comment]
Ok, neither of our use cases is unsolveable without this.
