### ISSUE TITLE
Google Cloud healthcheck 503 after upgrade to grpc-go@v1.20

### ISSUE THREAD

**Issue by tobiasfriden** [grpc/grpc-go#2988]
### What version of gRPC are you using?
grpc-go v1.20
### What version of Go are you using (`go version`)?
go version 1.11
### What operating system (Linux, Windows, …) and version?
Alpine Linux 3.10 (latest tag on docker hub)
### What did you do?
Originally submitted this in the grpc-web repo, but was recommended to post it here instead: https://github.com/grpc/grpc-web/issues/613

I am running grpc-web with the recommended Envoy sidecar proxy on GKE, talking to a grpc service written in go. However, after upgrading to grpc-go version 1.20 I am starting to see 503 Upstream Reset errors from the Google Cloud healthcheck. 

I have traced back and the error occurs when upgrading from v1.19 to v1.20 (with 1.19 the healthcheck returns 200). 

### What did you expect to see?
Google Cloud health check to grpc-web service returning status 200, like this:
`[2019-08-21T09:44:29.528Z] "GET / HTTP/1.1" 200 - 0 0 92 91 "-" "GoogleHC/1.0" "8d1754bd-68e8-49d8-b923-f5a4b4614c32" "10.166.0.49" "[::1]:6000"`
### What did you see instead?
Response 503 Upstream Connection Reset, like this:
`[2019-08-21T09:36:29.483Z] "GET / HTTP/1.1" 503 UR 0 85 83 - "-" "GoogleHC/1.0" "f6ee3baf-f0cf-4114-8672-97df8f195a18" "10.166.0.49" "[::1]:6000"`

**Comment by dfawley** [comment]
I am reasonably confident this change was caused by #2599.  Your healthcheck is not originating from a grpc client.  We previously had a bug that caused grpc-go servers to assume all clients understood gRPC semantics -- these semantics include returning HTTP status 200 *even on errors*.  #2599 updated servers to determine that the client is not a gRPC client (based on `content-type != application/grpc`), and return HTTP status errors instead.

So, this request was always returning an error, but it wasn't reported as an HTTP error until #2599.

**Comment by tobiasfriden** [comment]
This does sound reasonable, thanks for the help!
