### ISSUE TITLE
Can I get access to the underlying accepted socket while processing a client's request?

### ISSUE THREAD

**Issue by mpontillo** [grpc/grpc-go#3004]
(This might be an enhancement request rather than a question.)

I'm working on a project that uses gRPC over a UNIX socket. I want to get access to the underlying socket while processing an RPC request, so that I can do low-level socket calls. For example, I'd like to [get the peer credential](https://stackoverflow.com/questions/8104904/identify-program-that-connects-to-a-unix-domain-socket) for access control and/or logging purposes.

That is, it looks like I could provide a custom `net.Listener` object to `Serve()`, but that would only solve half the problem. (I could then accept or reject *connections* based on the peer credential, but not individual *RPC methods*.)

Is there a supported way to do this? (I [don't see an obvious way to do it](https://github.com/grpc/grpc-go/blob/master/server.go#L586), but it looks like if I can get access to the `rawConn`, I can move on to the next problem to solve...)

**Comment by menghanl** [comment]
A solution that should work:

Credentias [`ServerHandshake`](https://github.com/grpc/grpc-go/blob/6c2b3b1ba47edddd558d6772e61db6c983ef9d37/credentials/credentials.go#L98) gets the rawConn and returns an `AuthInfo`. This `AuthInfo` will be made available in the context via https://godoc.org/google.golang.org/grpc/peer#FromContext

If you put rawConn into `AuthInfo` in `ServerHandshake`, you can get it latter from the RPC context.

---

Further more, you can make the syscalls in `ServerHandshake`, get the peer credential information, and put those in `AuthInfo`. This way, you only make the syscalls once per connection (instead of once per RPC).
