### ISSUE TITLE
Any way to remove the dependency on cloud.google.com/go?

### ISSUE THREAD

**Issue by aarondl** [grpc/grpc-go#3036]
I've been doing some spelunking into our dependencies at work; there are a staggering amount of them. I suppose they were always there but go modules makes them a lot more obvious.

One thing I noted was that there's a module-level circular dependency chain that looks like this:

```
google.golang.org/grpc -> golang.org/x/oauth2 -> cloud.google.com/go
  ^                               ^-------------------|
   \--------------------------------------------------|
```

The circular module dependency doesn't matter I suppose because at the package level nothing's circular. A more detailed view is:

```
"google.golang.org/grpc":credentials/oauth/oauth2.go -> "golang.org/x/oauth2/google"
"golang.org/x/oauth2/google":google.go -> "cloud.google.com/go/compute/metadata"
"cloud.google.com/go":go.mod -> "google.golang.org/grpc" & "golang.org/x/oauth2"
```

I didn't look into why the cloud.google.com/go module is requiring grpc & oauth2 because it seems reasonable. The somewhat less reasonable part is oauth2/google's and grpc's transitive dependency on the metadata package which brings in the big module "cloud.google.com/go".

The oauth2 library is pulling in cloud.google.com for 2 methods. `metadata.OnGCE` and `metadata.Get` that are implementations for `ComputeTokenSource` implementation of oauth2's `TokenSource` interface. Presumably to be able to get GCE tokens.

I don't have any proposed solutions because it's really up to the authors of these 3 libraries to figure out the best course of action but I hope that we can agree that it'd be good if this were not the case.

**Comment by dfawley** [comment]
I don't think there's anything we can do here (in any of these repos, though I can't speak authoritatively for oauth or google-cloud-go), except splitting up modules and adding sub-modules, which is an exercise fraught with danger IIUC.  Note that `grpc/credentials/oauth` is not imported by grpc by default - only users that need this functionality will import it, and consequently pull in the dependency on `x/oauth2/google`.  OAuth must talk to the metadata server to get the GCE tokens, which it does with google-cloud-go, and google-cloud-go uses grpc extensively.

Why do you believe the circular module dependency is problematic?  This is entirely normal and happens often.  We do try to reduce our dependencies, but generally the focus is on minimizing the dependencies users get from importing the `grpc` package itself, not at a module level.  (That said, I've been wanting to shard things so that at least our static analysis tools -- not referenced by any real `.go` file, and not needed by any user -- are in a separate module.)

**Comment by aarondl** [comment]
@dfawley Essentially the reduction of dependencies. My follow-up question is essentially: Why not try to reduce dependencies at the module level given that that's the unit of focus now? There is overhead and other problems introduced by module dependencies, not just package dependencies. I'm not really concerned about the circular module dependency (though it doesn't feel right to me) so much as the seemingly excessive dependency that is `cloud.google.com/go`.

While it's true at a package level `grpc/credentials/oauth` will only be pulled in by direct importers, that's not true at the module level. This module is now included in your build and there will be time spent fetching the git repository (`cloud.google.com/go`) and examining it's go.mod and it's recursive of course for all module dependencies of it (and yes, a proxy can save you the entire source DL but you'll still hit the proxy for all it's go.mods). Unless I'm misunderstanding something which is totally possible, modules are quite new and I'm not familiar with all areas of it.

There could be problems at the open source level since now whatever license and transitively the licenses of the `cloud.google.com/go` repo include are now my problem as well (or just their go.mod which is awkwardly probably also covered by their license, would have to dig into what "use" is). Although the licenses in these modules are all MIT/Apache2 it's still a bunch of dependencies to have to worry about when collecting licenses and producing licensing reports. And even though this process is automated, it's just "more things".

I look at the list of modules my project needs and I see things like `cloud.google.com/go` and think: "Why am I plulling in an entire Google Cloud SDK to use grpc?" We have a small bunch of dependencies but it's through oddities like this (and trust me, this case is no exception) where huge amounts of additional code and dependencies get pulled in. One of my personal side goals is to try to find these links and get them deleted so that the overall set of dependencies we're using (and also Go programmers in general) is reduced where possible hence I reached out looking for others sympathetic to the general plight.

In terms of solutions I don't think submodules are the right way to go so much as separate modules. In my mind the only fix here is to make `oauth2/google.go` more self-contained by moving the metadata pieces into it, or remove the functionality entirely into the `cloud.google.com/go` module. Either way works, and seems better than what's going on currently where each package has half of the authentication logic.

**Comment by dfawley** [comment]
To me your concern seems like a greater "Go Modules" concern, and I think it's very real.  For that I would recommend the [golang-nuts group](https://groups.google.com/forum/#!forum/golang-nuts) (searching there may yield useful results).  I agree this feels like a kind of C header file situation, where unused features of unused parts of unused libraries can easily lead to even simple programs including the universe (but at least they stay out of the binary!).

In the grpc-go repo, our only option here would be to have a sub-module for the `credentials/oauth` package.  However, it feels like a broken system if we have to declare a new module for every package we add.

I do know that the google-cloud-go team looked into what it would take to use sub-modules for their different projects (it is a huge repo), but I believe the conclusion at the time was that it was too easy for things to break, and too hard to do it right.  CC @jadekler for any updates there that I haven't seen (or references to other people if he is no longer involved in those discussions; thanks!).  This, to me, seems like the best place to do any splitting, since they have many, different projects happening inside a single repo/module right now.  If there are excessive logistical difficulties utilizing sub-modules when it does make sense, though, then I think that, also, is a concern to bring up with the Go community/team via an issue in their repo or on golang-nuts.

**Comment by jadekler** [comment]
> @jadekler for any updates there

We ended up adding sub-modules (nested modules? multi modules?) to make it more understandable what version different clients were at. We only did it for a few, manually-written clients rather than everywhere: the overhead is definitely a thing. However, I'm not sure I see a compelling reason to do so here:

> The circular module dependency doesn't matter I suppose because at the package level nothing's circular.

Correct. Cycles in modules are allowed and don't cause problems in practice (mostly... see https://github.com/golang/go/wiki/Resolving-Problems-From-Modified-Module-Path).

> There is overhead and other problems introduced by module dependencies

Are there? The proxy makes the download overhead negligible, which is the only one I'm aware of. Are there other overheads you could point to for us to investigate?

**Comment by aarondl** [comment]
@jadekler That does assume a proxy which is optional (even if it is the default now). You're still going to query that API N times because of this which I don't think is completely negligible (worst case scenario that many zips). I don't think the open source licensing problem is one to take lightly either. There is overhead for the go build tool to do the math for it and all the dependencies under it for no reason at all as well (since these things are just discarded by the compiler in the end). Although in this case perhaps the overheads are small it's these sorts of things that if everyone does it piles up and the next time you require a single module you get 40 dependent modules relating to Azure that you didn't want/need. Currently our code by some transitive dependency is pulling in all of `etcd` which seems... odd.

I hope submodules isn't the solution that's reached for first. Personally I'd hope for a new top-level module before that happens.

I think the most compelling reason to change anything is that there are two libraries here that are supposed to deal with auth in GCE and neither do, they only do half the job so far as I can tell? Just seems like an odd way to have the code organized. Perhaps the GCE Token Source implementation should just reside in the Google Cloud SDK.

If we refactor it, break the link, I think everyone only stands to gain in several ways. The dependency graph becomes much cleaner. Proxies and Compilers both do less work. People who want to auth to GCE will get dependencies relating to GCE. Only downside is change management/version bumping that I can see.

**Comment by jadekler** [comment]
> You're still going to query that API N times

Lost you on this one. What is N, and what API?

> I don't think the open source licensing problem

What problem? Could you elaborate?

> There is overhead for the go build tool to do the math for it and all the dependencies under it for no reason at all as well

I hear what you're saying, but this is negligible. It would have to be a _very_ large subgraph for build times to become noticeably slower. (which it is not)

> Currently our code by some transitive dependency is pulling in all of etcd which seems... odd.

That seems like a problem you could investigate with `go mod graph`. Certainly it has nothing to do with our dependencies: it's not in our graph.

> I think the most compelling reason to change anything is that there are two libraries here that are supposed to deal with auth in GCE and neither do, they only do half the job so far as I can tell?

Yes, I agree that is a nuisance. We are working on making auth more obvious and clear for GCP. Apologies for the confusion. <-- @broady 

> If we refactor it, break the link, I think everyone only stands to gain in several ways.

The maintenance work is greater, and there is honestly not a whole lot that users gain AFAICT (apart from some fairly small runtime speed improvements in tooling).

**Comment by dfawley** [comment]
@aarondl I'm not a lawyer, but I'd be surprised if there's a license issue caused by unused, unimported, uncompiled code.  `go build` shouldn't even see the unused code if it's truly not referenced.  `go list -f {{ join .Deps "\n" }} <pkg>` will show you the true dependencies of your package, which is all that `go build` needs to process.  Any other code from a module that is unused might still be downloaded, but it won't appear in the binary output in any form.

> I think the most compelling reason to change anything is that there are two libraries here that are supposed to deal with auth in GCE and neither do, they only do half the job so far as I can tell?

I'm not sure what you mean by this.  AIUI `google-cloud-go` has generic code to talk to the metadata server.  `oauth/google` uses g-c-g to get keys from the metadata server, but is otherwise a complete auth implementation.  `grpc/credentials/{oauth,google}` are fairly small wrappers of `oauth/google` to make it work in grpc.
