### ISSUE TITLE
Make insecure ClientConn as explicit

### ISSUE THREAD

**Issue by iamqizhao** [grpc/grpc-go#307]
Requested by our security team, I will make some change to change the default security setting of ClientConn to TLS. If users need insecure ClientConn, they have to request it explicitly via a dialOption. 

This change will probably lead to breakage. Sorry about the inconvenience. But this will provide better protection for your service and customers.

**Comment by dsymonds** [comment]
It would have been nice to roll out the `grpc.WithInsecure()` bit first (and maybe only log if it was absent), and give people time to update their code before enforcing this.

**Comment by iamqizhao** [comment]
This is a mandatory request we just got from security team and has to be
done before beta (tomorrow or early next week) ...  We are not given a
reasonable time window to achieve graceful deployment unfortunately.

**Comment by michael-berlin** [comment]
For the time being, you could extend the error message and let people know how to fix it or point them to this issue.

For the record: Due to the breakage, tests will fail with "grpc: no transport security set".

Even though this is a small hiccup, we're super happy with the Go support for gRPC. So keep up the good work :-)

**Comment by iamqizhao** [comment]
@michael-berlin 

I have extended the error message in #313 to tell the caller how to fix.

Please expect a few other hiccups in the next a few days to indicate the end of alpha. :-)
