### ISSUE TITLE
gRPC bi-directional streaming: Close stream from client.

### ISSUE THREAD

**Issue by ysong4** [grpc/grpc-go#3230]
I have a bi-directional streaming RPC. On the client side, I have a goroutine like this
```
func listenEvents(stream pb.XXXXX, ) {
    for {
        msg, err := stream.Recv()
        ...
    }
}
```

Now I want to close the stream, which receive data from server. But, when I invoke context ```cancel()``` and ```ClientConn.Close()```, the ```stream.Recv``` is still blocking there.

Any suggestion on how to close the server stream on client side?

**Comment by ysong4** [comment]
https://github.com/grpc/grpc-go/issues/990

Well, I found out the solution... But I am confused. Why we need to create a new context from the old context to cancel the stream?

**Comment by menghanl** [comment]
Which `cancel` did you call if you didn't create a new context?

And `ClientConn.Close()` should close the stream, and unblock `Recv` with error.

**Comment by ysong4** [comment]
Thanks for the reply! Sorry for the question if it is too dumb... I did not read context document before carefully.

On client side, after created the ```ClientConn```, I create a context ```ctx``` and a ```cancel```` using ```context.WithCancel(context.Background())```, which creates the 'old context'.

And then I put the ```ClientConn```, ```ctx``` and ```cancel``` into a ```struct```, and pass that ```struct``` to other functions.

Now I read the context doc and some posts, which say do not to put context inside a struct.

[link1](https://golang.org/pkg/context/)
[link2](https://github.com/golang/go/issues/22602)

Is this the of cause of the problem? Why can't I put a context inside a struct?

**Comment by menghanl** [comment]
> Can I use a shared context in a sequence of requests?

In general I would say: don't.

It might work now, but that's mostly because you never do anything to those contexts.

If you share the context between two RPCs, you won't be able to cancel only one, because canceling the context will cancel both.
In a more gRPC specific case, context is also used to send [metadata](https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md). Metadata for one RPC can be leaked to another if the context is shared.

**Comment by ysong4** [comment]
Got it! Thank you.
