### ISSUE TITLE
How to serve one service on two ports?

### ISSUE THREAD

**Issue by koho** [grpc/grpc-go#3274]
I want to serve a grpc service on an insecure port and a secure port at the same time. I found that grpc for python can use [add_insecure_port](https://grpc.github.io/grpc/python/grpc.html#grpc.Server.add_insecure_port) and [add_secure_port](https://grpc.github.io/grpc/python/grpc.html#grpc.Server.add_secure_port) to do this. But how to do that in go?  Something like this?

```go
func serve(server Server, address string) {
    lis, err := net.Listen("tcp", address)
    if err != nil {
        log.Fatalf("failed to listen: %v", err)
    }
    if err := server.Serve(lis); err != nil {
        log.Fatalf("failed to serve: %v", err)
    }
}

func main() {
    insecureServer := grpc.NewServer()
    secureServer := grpc.NewServer(...)
    pb.RegisterIOServer(insecure_server , &server{})
    pb.RegisterIOServer(insecure_server, &server{})
    go serve(insecureServer, ":8001")
    serve(secureServer, ":8002")
}
```

**Comment by icholy** [comment]
Reuse the same `&server{}` instance.

**Comment by menghanl** [comment]
Your code should work for your case, except that, as suggested by @icholy, you should register the same `&server{}`:

```
s := &server{}
pb.RegisterIOServer(insecure_server , s)
pb.RegisterIOServer(secure_server, s)
```

---

Support both secure and insecure in the same gRPC server isn't possible because of the APIs today. But if you really want, you can override credentials `Handshake()`  method to bypass handshake for some connections.
