### ISSUE TITLE
Keep getting "the connection is draining" and "transport is closing" when sharing ClientConn goroutines.

### ISSUE THREAD

**Issue by jedrp** [grpc/grpc-go#3297]
I have a grpc server working behine nginx reverse proxy, for testing this issue I set the **http2-max-requests to 10** that mean 10 requests can be served through one HTTP/2 connection, after which the next client request will lead to connection closing and the need of establishing a new connection.

### gRPC version
 v1.26.0

### go version 
go1.12.5 windows/amd64

### operating system
client - Windows
grpc server - Kubernetes version: 1.13.12

### What did I do?
```go
	creds := credentials.NewTLS(&tls.Config{
		InsecureSkipVerify: true,
	})
	conn, err := grpc.Dial(fmt.Sprintf("xxx.xxx.xxx:%v", 443), grpc.WithTransportCredentials(creds))
	d := grpc_api.NewEventServiceClient(conn)

	if err != nil {
		fmt.Println(err.Error())
	}
	for {
		go func() {
			for i := 0; i <= 100; i++ {
				_, err := d.SendEvent(context.Background(), &grpc_api.SendEventRequest{})
				if err != nil {
					fmt.Println(err.Error())
				}
			}
		}()
		time.Sleep(200 * time.Millisecond)
	}
```

### What did I expect to see?

The ClientConn should be renew and all requests should be in success status code 

### What did you see instead?

Some requests failed with:
rpc error: code = Unavailable desc = the connection is draining
rpc error: code = Unavailable desc = the connection is draining
rpc error: code = Unavailable desc = the connection is draining
rpc error: code = Unavailable desc = transport is closing
rpc error: code = Unavailable desc = transport is closing
rpc error: code = Unavailable desc = transport is closing

Note: if I done with the code like this then everything work fine
```go	
	for {
		go func() {
			creds := credentials.NewTLS(&tls.Config{
				InsecureSkipVerify: true,
			})
			conn, err := grpc.Dial(fmt.Sprintf("xxx.xxx.xxx:%v", 443), grpc.WithTransportCredentials(creds))
			d := grpc_api.NewEventServiceClient(conn)
		
			if err != nil {
				fmt.Println(err.Error())
			}
			for i := 0; i <= 100; i++ {
				_, err := d.SendEvent(context.Background(), &grpc_api.SendEventRequest{})
				if err != nil {
					fmt.Println(err.Error())
				}
			}
		}()
		time.Sleep(200 * time.Millisecond)
	}
```

**Comment by menghanl** [comment]
This is caused by a race between the start of a stream on a connection and the graceful close of the connection.
The server sends a `GOAWAY` when number of requests on the connection reaches the limit. But the client keeps sending new streams on this connection, until it receives the `GOAWAY`. The steams between server sending `GOAWAY` and client receiving `GOAWAY` will fail.

The gRPC client does a retry for this kind of failures, but retry only happens once (for each RPC).

How often do the errors happen? And which of the errors ("connection is draining" vs "transport is closing") happen more often?

One thing to try is to add `grpc.WaitForReady(true)` to the RPC.
Another thing to think of is to handle these errors in the application code. This is what will happen when the connection (TCP) is down for whatever reason. The application should be able to handle them (retry, or fail).

**Comment by jedrp** [comment]
Thanks for great explanation.

> How often do the errors happen?
It will happen more often if I increase number of concurrency RPC for each time the code run.

> And which of the errors ("connection is draining" vs "transport is closing") happen more often?
the "connection is draining" happen more often than "transport is closing".

> One thing to try is to add grpc.WaitForReady(true) to the RPC.
I try to add this to the RPC but it didn't help, still getting those errors.

I see after some fail RPCs (with "connection is draining" and "transport is closing" message), the code still run and get the success RPCs. that mean the ClientConn was renew somehow, how if we block to make the new RPCs untill the ClienConn is reopened?

**Comment by menghanl** [comment]
The ClientConn always recreates the connection, so new RPCs won't fail.

There's no way to block the RPCs, because from the RPCs' point of view, the connection is ready to use (GOAWAY not received yet).

If the server first sends a GOAWAY with last stream ID as max-uint, waits for a round trip, and sends another GOAWAY with the real last stream ID, the race can be avoided (this is what a gRPC server does during graceful stop, and is also briefly mentioned in [this paragraph in the spec](https://httpwg.org/specs/rfc7540.html#rfc.section.6.8.p.16)), but it's not clear if nginx is doing that.

On the client side, you can turn on retry for error code `unavailable`. You can find a retry example here: https://github.com/grpc/grpc-go/tree/master/examples/features/retry

**Comment by jedrp** [comment]
I set  the GRPC_GO_RETRY=on in environment variables and I tried with the code bellow but seem like it did not reduce the number of fail requests. I will take more time to debug the code base

```
creds := credentials.NewTLS(&tls.Config{
		InsecureSkipVerify: true,
	})
	var retryPolicy = `{
		"methodConfig": [{
			"name": [{"service": "grpc.examples.echo.Echo"}],
			"waitForReady": true,
			"retryPolicy": {
				"MaxAttempts": 10,
				"InitialBackoff": "01s",
				"MaxBackoff": ".01s",
				"BackoffMultiplier": 1.0,
				"RetryableStatusCodes": [ "UNAVAILABLE" ]
			}
		}]
	}`
	conn, err := grpc.Dial(fmt.Sprintf("xxx.xxx.xxx:%v", 443), grpc.WithTransportCredentials(creds), grpc.WithDefaultServiceConfig(retryPolicy))
	d := grpc_api.NewEventServiceClient(conn)
	if err != nil {
		fmt.Println(err.Error())
	}
```

**Comment by menghanl** [comment]
@jedrp Did you get time to look more into this?
FYI you can also try [turning on logs](https://github.com/grpc/grpc-go#how-to-turn-on-logging) to see that gives more clues.

**Comment by dfawley** [comment]
@jedrp - do you have any updates on this issue?
