### ISSUE TITLE
Empty port while 'dial'ing connection doesn't throw an Error ?

### ISSUE THREAD

**Issue by ideepg** [grpc/grpc-go#3319]
`conn, err := grpc.Dial("", grpc.WithInsecure())
  if err != nil {
    log.Fatalf("did not connect: %s", err)
  }`

The above code with empty port doesn't throw any error. What is the recommend way to know if the connection has been established or failed?

**Comment by easwars** [comment]
You could possibly use the [WithBlock](https://godoc.org/google.golang.org/grpc#WithBlock) DialOption to make sure that `Dial` blocks until the connection is up. If you are using [WithBlock](https://godoc.org/google.golang.org/grpc#WithBlock), you should also probably use [DialContext](https://godoc.org/google.golang.org/grpc#DialContext) with an appropriate deadline (instead of `Dial`), so that you only block for a reasonable amount of time.

Also, please refer to the [naming guide](https://github.com/grpc/grpc/blob/master/doc/naming.md) for the URI syntax. Port is optional in the URI.
