### ISSUE TITLE
DumpRequest/DumpResponse equivalents for gRPC?

### ISSUE THREAD

**Issue by philips** [grpc/grpc-go#335]
How can I dump the requests and responses from grpc-go? The net/http package has some helpers, and I essentially want the equivalent for gRPC:
- http://golang.org/pkg/net/http/httputil/#DumpRequest
- http://golang.org/pkg/net/http/httputil/#DumpResponse

We would like to add a `--dump-file` flag to etcd to support analysis https://github.com/coreos/etcd/issues/3502

**Comment by iamqizhao** [comment]
We call this binary logging. It is on our road map but I do not have an ETA
for now though. I will ping this thread back once there is a decision.
Thanks for bringing this up.

**Comment by philips** [comment]
@iamqizhao Where is the roadmap? Is this something we can help with?

**Comment by iamqizhao** [comment]
We are figuring out. The Google internal one will be done by the end of the
next quarter. Have not got confirmed for the external version.

**Comment by iamqizhao** [comment]
I will let you know if I need help from your side (probably right after I
finish the internal version). Thanks for the help!

**Comment by philips** [comment]
Looking back at this issue this is another example of something that would be solved by building on top of net/http2 directly instead of patching.

**Comment by iamqizhao** [comment]
On Wed, Jan 6, 2016 at 12:29 AM, Brandon Philips <notifications@github.com>
wrote:

> Looking back at this issue this is another example of something that would
> be solved by building on top of net/http2 directly instead of patching.
>
To be clear, I think the feature you requested here is on grpc message
level (i.e., request message and response message) instead of http2 frames
(a grpc message could be chunked into multiple http2 data frames). Do I
misunderstand? I am actually not sure whether httputil works for http2.

In addition, the approach of building on top of net/http2 may bring much
more problems/troubles than the benefit at least at the current stage
(e.g., functional compatibility, performance, etc. plus massive effort on
redesign and development).

**Comment by xiang90** [comment]
@iamqizhao Will grpc-go provide the binary-logging feature? Or we should implement it as an interceptor?

**Comment by iamqizhao** [comment]
@xiang90 It will. But I have not got time to get my hands on that. Yes, you can do that if it fits your requirements.

**Comment by xiang90** [comment]
Thanks!

**Comment by hsaliak** [comment]
We do not yet have a binary logging feature and are not prioritizing it actively, so closing the issue. As the reporter has already addressed this as via an interceptor, closing the issue.
