### ISSUE TITLE
Notify of Closed Client Connections

### ISSUE THREAD

**Issue by capnspacehook** [grpc/grpc-go#3438]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?

I manage sessions internally in my server's code, and I would like to have the robustness and stability of the `google.golang.org/grpc/keepalive` package while also being able to respond to closed client sessions. 

### Proposed Solution

The gRPC server struct could have a public sending channel that sends client addresses that are closed due to the server keepalive settings. If server keepalive settings are not set, the channel would be a nil channel. This would allow users of gRPC to respond internally to closed client connections due to inactivity and non-responsiveness. 

### Alternatives Considered

I tried to at one point implement my own keepalive mechanism using gRPC methods, but abandoned it due to the fact that I now have multiple clients written in different languages, and the cost to maintain my custom keepalive code was not woth it.

**Comment by dfawley** [comment]
@capnspacehook is there any reason why you want keepalive disconnections to be reported separately from all disconnections, regardless of cause?

For instance, it is possible to wrap the `net.Listener` passed to `grpc.Server.Serve` with something that notifies a channel every time a connection is established/lost.  This would not relay any keepalive information, but I'm not sure whether that's important for you.

**Comment by capnspacehook** [comment]
Hmm, that would actually work quite well, except for the fact that one of my clients is using grpc-web, so the Envoy proxy I setup to handle HTTP/1.1->HTTP/2 makes every connection remote address seem to be the IP of the Envoy proxy.

My gRPC server needs to know when connections are established and closed, so wrapping a `net.Listener` and passing it into `grpc.Server.Serve` almost works, but I need to get the real remote IP of each accepted/closed connection. I do this successfully in my upstream RPC calls/interceptors, parsing the x-forwarded-for header, but I can't see how I can do that in a wrapped `net.Listener`. 

To answer your main question, the main reason I wanted to have keepalive disconnections to be reported separately to all other disconnections was for logging and triaging purposes, although if I could get this wrapped listener working properly I could get around that by reading into the context of weather a disconnection was lead by a Logoff call etc.

**Comment by dfawley** [comment]
> I do this successfully in my upstream RPC calls/interceptors, parsing the x-forwarded-for header

I don't think we'd want to do something like this in gRPC.  `x-forwarded-for` would be set per-call, which means it could change during the life of a connection, or never be seen if no calls were made.  If we were to have a feature notifying of connections started/ended, it would not include special considerations for forwarding headers, so it would have the same limitations as wrapping the listener.

In general, the concept of sessions isn't something that gRPC uses.  The closest thing to that is a long-lived streaming RPC.  Otherwise, for load balancing purposes, it is typical for clients to send RPCs to many different backends at the same time, not just a single one.  Sufficient data should be included with every request to allow each RPC to be self-contained, and services should be tolerant of connections being lost at any time.

Given that sessions are not really a feature of gRPC, I will close this since it 1. is possible with a listener wrapper, and 2. would encourage uses that are counter to the core gRPC API design philosophy.
