### ISSUE TITLE
grpclb: DNS SRV/TXT records and the bootstrap JSON file

### ISSUE THREAD

**Issue by miekg** [grpc/grpc-go#3488]
Hi all,

I'm trying to connect all the dots to make a (custom) xDS management server serve all the needs for gRPC loadblancing. I know this code is actively worked on and I would like to ask some clarification on the different mechanism to configure xDs and gRPC LB.

There is:

*balancer/grpclb* - this perform SRV queries to return the endpoints of a service, <https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md> indicates I need to return the IP addresses of the balancer. Using the grpc-go code from yesterday (e965f2a60b15c8d613c9fb4439efccc4c706daa0) seemed to confuse the client (looked to be mixing the service endpoints and the balancer endpoint). I see this is deprecated, but the use of SRV records is still a good idea.

*xds/experimental* - this performs a TXT query that (again?) returns the balancer's clustername in the serviceConfig and some otherbits, but excludes other important data like the node-id proto to use (yes, this is client specific, so putting it here is not a good idea)

*xds/experimental* - GRPC_XDS_BOOTSTRAP a json file with again some bit pertaining to the xds mangement cluster (node-id is here). Using this file seem work best: (but shows that I need to implement xDS v2 as well in my management server)

~~~
INFO: 2020/03/31 08:20:52 [xds-client 0xc000196b40] Sending ADS request for new watch of type: type.googleapis.com/envoy.api.v2.ClusterLoadAssignment, resource names: [helloworld]
INFO: 2020/03/31 08:20:52 [eds-lb 0xc0001a3040] Watch started on resource name helloworld with xds-client 0xc000196b40
INFO: 2020/03/31 08:20:52 Subchannel picks a new address "localhost:18000" to connect
INFO: 2020/03/31 08:20:52 Channel Connectivity change to CONNECTING
INFO: 2020/03/31 08:20:52 Subchannel Connectivity change to READY
INFO: 2020/03/31 08:20:52 Channel Connectivity change to READY
INFO: 2020/03/31 08:20:52 [xds-client 0xc000196b40] ADS stream created
WARNING: 2020/03/31 08:20:52 [xds-client 0xc000196b40] ADS stream is closed with error: rpc error: code = Unimplemented desc = unknown service envoy.service.discovery.v2.AggregatedDiscoveryService
INFO: 2020/03/31 08:20:54 [xds-client 0xc000196b40] ADS stream created
WARNING: 2020/03/31 08:20:54 [xds-client 0xc000196b40] ADS stream is closed with error: rpc error: code = Unimplemented desc = unknown service envoy.service.discovery.v2.AggregatedDiscoveryService
INFO: 2020/03/31 08:20:57 [xds-client 0xc000196b40] ADS stream created
WARNING: 2020/03/31 08:20:57 [xds-client 0xc000196b40] ADS stream is closed with error: rpc error: code = Unimplemented desc = unknown service envoy.service.discovery.v2.AggregatedDiscoveryService
~~~

As said, I'm trying to tie this all together while working on a DNS implementation that gives gRPC the right information. For this I would like to see (please say if I'm jumping the gun here and stuff is planned this way):

* Removal of the bootstrap file:

  * can we make the node-info a grpc.DialOption ?
  * the xds_server addresses can be retrieved from the DNS - with the already specified _grpclb._tcp SRV query (see below).
  * the grpc channel creds can probably *also* put in the DNS? But prolly not public data>

* Require a _grpclb._tcp.<servicename> SRV loookup to find the load balancer IP addresses.

  This is what happens now with balancer/grpc but seems to be left (to be added?) in the xds code? In effect this returns a list of IP:ports where the balancer cluster lives - the gRPC client should connect to those and retrieve the actual cluster endpoints.

* Also allow for a <servicename> SRV lookups that return the endpoints for the service (not the loadbalancer). This can be handy for a one-off gRPC query without doing the whole xDS/ADS setup and assuming the DNS server knows best (should a dialOption as well?)

* Put anything we can't properly place in SRV records in a _grpc_config.<service> TXT record that hold the serviceConfig (channel creds here?)

This would at least unify where to get the config from (initially) namely the DNS - once the gRPC client is connected to the xDS management server it will stop using DNS and directly talk to that and perform load reporting etc. etc.

Some related issues: #3367 and maybe #2619

**Comment by menghanl** [comment]
## xDS and DNS (or other name resolvers)

xDS itself includes name resolution.
The full xDS support includes a name resolver (using LDS+RDS) plus several load balancers (using CDS+EDS).
To use full xDS with another name resolver isn't feasible.


## balancer/grpclb and xDS (and EDS only mode)

balancer/grpclb and xDS use totally different protocal. balancer/grpclb is balancer only, while xDS includes a name resolver as well. So many concepts in balancer/grpclb don't apply well in xDS.

EDS is more similar to balancer/grpclb. You can use EDS only mode with DNS. You will need the resolver to specify a service config that picks EDS balancer: https://github.com/grpc/grpc-go/issues/3286#issuecomment-592214370.
If you do this with DNS, you can use SRV record for service config.

You will still need the json file to configure the xds server.

## GRPC_XDS_BOOTSTRAP json file

This files contains the address (and configuration) of the xDS server. It cannot come from name resolution (e.g. SRV record), because when xDS is used in the full mode, the xDS resolver will need the xDS server address.

Making it a dial option would in theory work.
But xDS server as a control plane server, isn't expected to change. The same client binary should use the same server, so there's no need to specify one for each ClientConn, nor return it as a name resolution result. There are actually discussions to make the ClientConns share one singlton xds_client.

---

Not sure if this answers all you question, but it should help clear things up. Let me know if you have further questions.

**Comment by miekg** [comment]
Thanks for your comments, that does clarify a few things. And sorry for my late reply.

Focusing on xDS (as that is the main mechanism going forward. What do you mean when saying:
> ... includes a name resolver (using LDS+RDS) 

This still requires something to answer does queries? 

I think you reply allows me to ask a more specific question:
balancer/grpclb uses the DNS to find the load-balancer, but xDS needs a bootstrap file. Why can't xDS not also use DNS to find the load balancer (at least initially) after that it will communicate directly with the LB.
