### ISSUE TITLE
support not decompress data on client side

### ISSUE THREAD

**Issue by xrmzju** [grpc/grpc-go#3569]
my case: periodically request a big file(over to 8G) from a grpc server and compress the file, upload to s3 for backup purpose.
my solution for now: directly request the file and do compression on my own code
my expect solution:  tell the grpc server to response me with compressed data to reduce the network io and my grpc client could decide whether to decompress the data or not.

i read the [compression guide ](https://github.com/grpc/grpc-go/blob/master/Documentation/compression.md) and made some test, found out that if i set UseCompressor CallOption in client side, then the server will response the compressed data as i expected, but the client side would do the decompress too, which is redundant and not expected in my case.

is there any way to make this happen for now?

**Comment by menghanl** [comment]
A somewhat hacky solution: on client side, [register](https://godoc.org/google.golang.org/grpc/encoding#RegisterCompressor) a `encoding.Compressor` with name `gzip` whose decompress() is a no-op, then still make the RPC with "gzip". When the client receives the gzip'ed response, it will call the registered gzip compressor to decompress the message. But because decompress() doesn't do anything, client will get compressed message.

The problem with this is, since the message is compressed, the proto decoder won't decode it, and for your application code to see the bytes, you will need to make a decoder that returns bytes. See packege [encoding](https://godoc.org/google.golang.org/grpc/encoding) for detailed information.

Some other thoughts. Not decoding the file on the client side means the client doesn't need to see the file content. If the whole purpose is to send it again to backup, why not make server send it directly to backup instead?

**Comment by dfawley** [comment]
> but the client side would do the decompress too, which is redundant and not expected in my case.

This use case doesn't really match the intent of message compression.  I think it would be advisable to have the client request message have a flag that indicates the server should compress the response payload data (manually).  Message compression is intended to compress the messages themselves, and in this case, the data payload in the response is apparently not a message.

Also, an 8GB proto message is not advisable.  The maximum message size in grpc is 2GB (after compression), and even at that size, you will almost definitely run into performance problems (memory constraints, etc).  It would be best to use a streaming RPC and chunk your data.

**Comment by xrmzju** [comment]
> Some other thoughts. Not decoding the file on the client side means the client doesn't need to see the file content. If the whole purpose is to send it again to backup, why not make server send it directly to backup instead?

actually my case is backup etcd snapshot data to s3,  i think etcd server send snapshot data directly to s3 is not a good idea....

> The problem with this is, since the message is compressed, the proto decoder won't decode it, and for your application code to see the bytes, you will need to make a decoder that returns bytes. See packege encoding for detailed information

i only need decode the data in case i need restore from the backup data, which is a rare case, i can decode the data in a simple cli tool by using the same decoding package used by proto

**Comment by xrmzju** [comment]
>  Message compression is intended to compress the messages themselves, and in this case, the data payload in the response is apparently not a message.

emmm...i do not really understand this... yes u r right about all my need is a compressed data pyload. but what do you mean by saying that ` the data payload in the response is apparently not a message`? would u mind explain it in detail?

> Also, an 8GB proto message is not advisable. The maximum message size in grpc is 2GB (after compression), and even at that size, you will almost definitely run into performance problems (memory constraints, etc). It would be best to use a streaming RPC and chunk your data.
yes it is  streaming RPC

**Comment by xrmzju** [comment]
> A somewhat hacky solution: on client side, [register](https://godoc.org/google.golang.org/grpc/encoding#RegisterCompressor) a `encoding.Compressor` with name `gzip` whose decompress() is a no-op, then still make the RPC with "gzip". When the client receives the gzip'ed response, it will call the registered gzip compressor to decompress the message. But because decompress() doesn't do anything, client will get compressed message.

i'll give this solution a shot..

**Comment by dfawley** [comment]
Sorry, I missed your question earlier:

> yes u r right about all my need is a compressed data pyload. but what do you mean by saying that the data payload in the response is apparently not a message? would u mind explain it in detail?

What I meant is that your client doesn't want to read the decompressed data.  Message compression is intended to make messages take up less space on the wire, but otherwise be transparent to the application.  If you don't want to decompress, you'll need to implement the compression yourself, and store the result in a message as `bytes`.
