### ISSUE TITLE
xds: propagate xds client transport error to watchers

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#3823]
- [ ] start a goroutine to monitor xds client's ClientConn's state, and send error to watchers on Transient Failure
- [x] when ADS stream is broken, send error to watchers

**Comment by easwars** [comment]
@menghanl : This seems to be similar in spirit to https://github.com/grpc/grpc-go/issues/4121.
Do we want to do this at this point in time? Do we need consensus among the languages.

**Comment by menghanl** [comment]
@markdroth Do you remember what's the reason for monitoring the channel's connectivity state? What problem is not covered by errors when the ADS stream is broken?

**Comment by markdroth** [comment]
The ADS call is wait_for_ready, so if the channel goes into TF before it becomes READY, the ADS call may not fail for a long time.  We want a more timely error message, which is why we watch the channel's connectivity state.

**Comment by easwars** [comment]
Blocked on https://github.com/grpc/grpc-go/issues/5818.

**Comment by markdroth** [comment]
See my comments on #5818 -- I don't think we want that as a public API.  It would be fine to provide that as an internal API, though, and then use that internal API here.

See also [gRFC A57](https://github.com/grpc/proposal/blob/master/A57-xds-client-failure-mode-behavior.md).  It is not strictly required to monitor the xDS channel's connectivity state; if you don't have an internal API you can use that reports the associated status when the channel reports TF, then there's probably no need to do this (although it does result in slightly sub-optimal backoff recovery when connectivity is restored, because you will not be able to use `wait_for_ready` for the ADS call).  My understanding is that Java does not plan to monitor the xDS channel's connectivity state, although C-core does do so.

**Comment by easwars** [comment]
A57 was implemented as part of https://github.com/grpc/grpc-go/pull/5996. We removed setting `wait_for_ready` as part of those changes, and we no longer plan to monitor the connectivity state of the xDS channel.

Changes which eventually get made as part of #5818 should no longer affect this issue. Hence closing this.
