### ISSUE TITLE
Interceptor not called when method not implemented in v1.32

### ISSUE THREAD

**Issue by mvrhov** [grpc/grpc-go#3847]
### Use case(s) - what problem will this feature solve?
With the new Service/Server definitions in 1.32, the interceptor doesn't get called if method is not implemented. 
This is a problem as you have no idea now that you forgot to implement the method as this doesn't get logged.
Another case is when you are starting with grpc you may think that your interceptors are not working as nothing gets logged.

### Proposed Solution
Call interceptors every time.

**Comment by dfawley** [comment]
Thanks for pointing this out; I'll fix this ASAP.

Note that this only applies to unary interceptors, which must be called by the generated code due to the design.  The handler needs to construct the message type and pass it to the `decode` function given to it before calling the interceptor.  Streaming interceptors are called by gRPC itself.

Should we call the (streaming) interceptor for unregistered methods?  We already do if `UnknownServiceHandler` is defined, but not if it isn't.  It seems like we should always call it -- i.e. the "default" `UnknownServiceHandler` is `func() { return Unimplemented }`.
