### ISSUE TITLE
v1 of protoc-gen-go-grpc

### ISSUE THREAD

**Issue by veith** [grpc/grpc-go#3870]
When do you plan to release a v1?

**Comment by dfawley** [comment]
The goal is by the end of the month, but we won't release it until we are comfortable with the API.  #3669

**Comment by veith** [comment]
@dfawley 
I would like to suggest to rename Unstable<XXX>Service to Strict<XXX>Service. And remove the "not recomended" from the comment. 

"Unstable" depends on the point of view...

**Comment by dfawley** [comment]
Please feel free to use #3669 for comments on the API.

`Unstable` is appropriate here, since it will break backward compatibility when backward-compatible changes are made to the service definition in the proto.  Similarly, it is not recommended for use outside of the immediate project containing the package for that reason.
