### ISSUE TITLE
Server streams never close when using GRPC with HTTP Server mux with timeout

### ISSUE THREAD

**Issue by aimichelle** [grpc/grpc-go#3884]
### What version of gRPC are you using?
1.29.1

### What version of Go are you using (`go version`)?
go1.13.8

### What operating system (Linux, Windows, …) and version?
linux 5.4.0-42-generic

### What did you do?
We are currently serving gRPC requests using a HTTP Server mux so that we may handle both gRPC/non-gRPC requests on the same port. 
We have a server-side streaming RPC call, where the server continually streams updates to the client until terminated by the client. 
On the client-side, we have code which does the `stream.Recv` in a loop. If the stream closes, or returns an error, the client sleeps for X seconds and starts up a new stream.
In our application code, our HTTP server has a read/write timeout of 30mins. We noticed that every 30 mins, the client gets a `"rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR"` error from the `stream.Recv`. We've adjusted the HTTP timeout and can confirm this error is from the timeout. 
However, on the server side, we noticed that although the client sees the stream as terminated, the stream is never closed on the server-side, and it runs forever. 

I was able to reproduce this using the gRPC route-guide example on a branch I made based off of gRPC 1.29.1:
https://github.com/aimichelle/grpc-go/commit/1ef03791bd5b21404001fa271ba4c4742a77f150 
The major modifications I did are:
- Update server.go's ListFeatures to send something on the stream every 2s, until stream.Context().Done().
- Update server.go's main() to serve requests using the HTTP sever mux, just like we have set up in our application.
- Update client.go's printFeatures() to call stream.Recv() in a loop, until stream.Context().Done() or until there is an error. In which case, it will wait for X seconds and start a new stream.

The examples can be run by `go run server.go`  and `go run client.go` as usual.

The important variables that I've played around with in the repro are:
- HTTP timeout: server.go, lines 279 &  280
- time the client sleeps before starting a new stream: client.go, line 90

I've seen some interesting results:
- Without TLS: the stream seems unaffected by the HTTP timeout. the stream continues running forever.
- With TLS:
  -- HTTP timeout > client sleep time : client Recv errors with `rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR` at the HTTP timeout time. But server's `stream.Context.Done()` is never called. (This is the case we are running into)
  -- HTTP timeout < client sleep time: client Recv errors with `rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR` at the HTTP timeout time. But server's `stream.Context.Done()` does get called.

I would expect that if there is a HTTP timeout  (even without TLS), that both the client and server would see the stream termination. 
Or, is using gRPC with the HTTP server mux a bad idea?

**Comment by easwars** [comment]
@aimichelle 
Thank you for you detailed problem report and repro steps.
I was able to try exactly what you have mentioned and I can confirm that I see the same behavior.
I can see the streams close on the server only when the client is terminated.

This is from my reading of the code so far (might not be accurate):
When `grpc.ServeHTTP` is used to serve gRPC requests, there is no way for the gRPC server code to know about the `ReadTimeout` set on the `http.Server`. The only timeout that it uses it what it gets from the wire on the `grpc-timeout` header field. See: https://github.com/grpc/grpc-go/blob/4270c3cfce29c699e3139df4b2213772b8eb9500/internal/transport/handler_server.go#L79

This is set on the client-side when a context deadline is specified when creating the stream. See: https://github.com/grpc/grpc-go/blob/4270c3cfce29c699e3139df4b2213772b8eb9500/internal/transport/http2_client.go#L451

I was able to verify that if you set a context deadline on the client when creating the stream, the server side stream gets closed when that context expires.

The documentation for `grpc.ServeHTTP` does have the following caveat:
```
// Note that ServeHTTP uses Go's HTTP/2 server implementation which is totally
// separate from grpc-go's HTTP/2 server. Performance and features may vary
// between the two paths. ServeHTTP does not support some gRPC features
// available through grpc-go's HTTP/2 server, and it is currently EXPERIMENTAL
// and subject to change.
```

And as far as the non-TLS case is concerned, I'm inclined to think that the behavior you are seeing is because of [line 227](https://github.com/aimichelle/grpc-go/commit/1ef03791bd5b21404001fa271ba4c4742a77f150#diff-69daf02e5b6e1b6d6142a1cfb6f65c20R277), where this new handler which is being created to handle h2c traffic has no idea of the timeout configured on the `httpServer`. But I was able to confirm even in this case that if a context deadline was set on the client side, the streams do get cleaned up.

**Comment by easwars** [comment]
And I feel that the better thing to do would be to set the timeout/deadline on the client side and not on the server-side.

If you do feel that there is a bug in the implementation, you are very welcome to send us a PR and we will be glad to review it. But at this point, the team does not have resources to spend more effort on the HTTP handler.

**Comment by aimichelle** [comment]
Setting a timeout on the client-side makes sense.
Thanks for the help and quick response!
