### ISSUE TITLE
1.33.0 was released, but removed?

### ISSUE THREAD

**Issue by ukai** [grpc/grpc-go#3945]
It seems 1.33.0 was released
https://pkg.go.dev/google.golang.org/grpc?tab=versions

but removed now?
https://github.com/grpc/grpc-go/releases/tag/v1.33.0 is 404 Not found.

**Comment by vvakame** [comment]
renovate bot automatically pushed the v1.33.0 to master last night and all CI jobs have been failed since then 😿

**Comment by menghanl** [comment]
The 1.33.0 release was pushed by mistake. We deleted that, and will skip it and release 1.33.1 later (schedule in two weeks).

1.33.0 still shows in pkg.go.dev because the bad release is cached by https://proxy.golang.org/ (as mentioned in its FAQ).

At this time, please avoid using 1.33.0, and use 1.32.0 instead.
Sorry for the confusion and inconvenience. And let us know if there are other problems.

**Comment by blixt** [comment]
This also broke builds for us and our developers – maybe in the future it's better to immediately republish a higher version with the reverted state rather than remove the version? With Go proxies and local caches, it's pretty hard to get rid of a version that is considered the latest version but was removed, leaving you in a flaky state.

**Comment by dfawley** [comment]
> maybe in the future it's better to immediately republish a higher version with the reverted state rather than remove the version?

We can't release 1.33.1 as an older stable version of grpc (e.g. 1.32.latest), as that could break backward compatibility requirements (i.e. 1.33.1 wouldn't have some features that 1.33.0 has).

There really aren't many options here.  We either have to live with an unstable 1.33.0 release for two weeks or delete it.  Neither option is ideal, but leaving an unstable release around seems worse.  If tooling can't handle deleted versions, perhaps it can be improved.

The only thing left to do is make sure this doesn't happen again.  We'll be updating our internal documentation to be clearer about what needs to be done to create a release branch.
