### ISSUE TITLE
Memory leak of gRPC Server in high con-concurrent

### ISSUE THREAD

**Issue by mnff** [grpc/grpc-go#3967]
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
v1.32.0
### What version of Go are you using (`go version`)?
1.14
### What operating system (Linux, Windows, …) and version?
linux
### What did you do?
Memory grows very fast，the request define like:
message Hello3Request {
	double f1 = 1;
	float f2 = 2;
	int32 f3 = 3;
	int64 f4 = 4;
	uint32 f5 = 5;
	uint64 f6 = 6;
	sint32 f7 = 7;
	sint64 f8 = 8;
	fixed32 f9 = 9;
	fixed64 f10 = 10;
	bool f11 = 11;
	string f12 = 12;
	bytes f13 = 13;
	map<string, string> f14 = 14;
	repeated string f15 = 15;
}, and the response same as this, handle is very simple, get every field and filling in the response,
profile is:
![image](https://user-images.githubusercontent.com/13212006/96562921-ea2b6f00-12f3-11eb-84bc-b4af4e424b57.png)

### What did you expect to see?
how to reduce mem

**Comment by menghanl** [comment]
We will need more information before we can look at this problem.
And if you believe it's a leak caused by gRPC, please try to reduce your code to the smallest possible reproduction.

And, see those issues (https://github.com/grpc/grpc-go/issues?q=is%3Aissue+sort%3Aupdated-desc+memory+leak+is%3Aclosed) for how other users solved their memory problems.
