### ISSUE TITLE
How implements response after function

### ISSUE THREAD

**Issue by ryo-kagawa** [grpc/grpc-go#3971]
implements Unary RPC Only
server side

At first I thought I should implement stats.Handler
But there was a problem
This is what I made
```
type myHandler struct {
}

func (m *myHandler) TagRPC(ctx context.Context, rti *RPCTagInfo) context.Context {
  return ctx
}

func (m *myHandler) HandleRPC(ctx context.Context, rs RPCStats) {
}

func (m *myHandler) TagConn(ctx context.Context, cti *ConnTagInfo) context.Context {
  return ctx
}

func (m *myHandler) HandleConn(ctx context.Context, cs ConnStats) {
  switch cs.(type)
  case *stats.End:
    // Can't determine if there is an error
}
```

How can I handle it after sending a response to the client?

**Comment by menghanl** [comment]
Sorry I didn't fully understand your question.
What information are you trying to get from the RPC? Can you give more details?

**Comment by ryo-kagawa** [comment]
I'm sorry the question is not appropriate

I created an implementation of this stats.Handler
```
type MyStatsHandler struct {
}

func (m *MyStatsHandler) TagRPC(ctx context.Context, rti *RPCTagInfo) context.Context {
  return ctx
}

func (m *MyStatsHandler) HandleRPC(ctx context.Context, rs RPCStats) {
  switch asdf := rs.(type) {
  case *stats.End:
    // break point
    // connection close from grpc client
    break
  }
}

func (m *MyStatsHandler) TagConn(ctx context.Context, cti *ConnTagInfo) context.Context {
  return ctx
}

func (m *MyStatsHandler) HandleConn(ctx context.Context, cs ConnStats) {
  switch cs.(type) {
  case *stats.ConnEnd:
    // if (http transport no error) {
    //   no error function
    // } else {
    //   error function
    // }
    break
  }
}
```

When the connection is disconnected from the client during the processing of the end timing of HandleRPC
Unable to return response to client, but unable to handle the error
I want to determine if the value was really returned to the client and do the work accordingly

**Comment by menghanl** [comment]
Stats handlers are not designed to send responses to the clients. If you need that, you need interceptors instead.

If you just want to see on the server side, whether the response/RPC-status is sent to the client. Since the RPC broke due to connection error, it's very likely the response didn't reach the client.

But, this is not the reliable way. Connection errors can happen anytime after the server writes the message on wire, before the client receives the message.
If it's important to know whether the client receives the message, the only reliable way is to synchronize at the application level.

**Comment by ryo-kagawa** [comment]
thank you
It was very helpful
