### ISSUE TITLE
Question: Can the client respond to a query from a server, and vice versa

### ISSUE THREAD

**Issue by wari** [grpc/grpc-go#412]
In the interest of actual 2 way communications, when a client connects to a server, I'd like the server to send some RPC calls to the client when it needs to query something on that end. Looking at both the hello and routeGuide examples, I'm not sure if this is possible. Can we `grpcServer.Serve(conn)` on a dialer instead of a listener, or does one have to the client have to be a server on a different port?

Thanks.

**Comment by wari** [comment]
A quick test shows that this is not possible `Serve()` requires a `net.Listener` instead of a `net.Conn`. Is it not possible to get this working other than setting up two servers?

**Comment by iamqizhao** [comment]
rpc is traditionally a client-server model. gRPC obeys this tradition by requiring client initiating the session. However, gRPC is more powerful than the traditional RPC libraries because it natively supports bi-directional streaming rpc where client is still responsible to initiate the communication but after that both sides can feel free to send the messages to the peer. I guess with some slight tuning of your service definition, your application might be able to use bi-directional streaming to meet your requirements.

And setting up two servers is the last resort.
