### ISSUE TITLE
is there any examples to show xds match header route

### ISSUE THREAD

**Issue by carolove** [grpc/grpc-go#4168]
i recently want to use grpc's xds features. but i find it is hard to practice,
i want a example to show me how to practics   grpc xds's header match route.
thank you for your help.

**Comment by menghanl** [comment]
We don't currently have an example.
And the configuration would be to set the routes on the management server side, instead of in gRPC.
I have an example in [this commit](https://github.com/menghanl/grpc-go/commit/83277715bed0fd7203d96a9053a641d77c950b1c) that runs the client with our fake server.

If using istio: https://istio.io/latest/docs/concepts/traffic-management/ would probably help.

If using go-control-plane: https://github.com/envoyproxy/go-control-plane/blob/ac21eb35a67ec2a897847769685e9412b9bd68fa/internal/example/resource.go#L78

**Comment by carolove** [comment]
Thank you for your support

**Comment by carolove** [comment]
Have your code in https://github.com/menghanl/grpc-go merged into upstream already?
i find your e2e case works not well in upstream code.

**Comment by menghanl** [comment]
> remove xds_routing_experimental and add cluster_manager_experimental
It's because part xds_routing's functionality was moved to the xds_resolver.
The reason for that is to support other configurations (e.g. timeout).
You can find more details in this design doc: https://github.com/grpc/proposal/blob/master/A31-xds-timeout-support-and-config-selector.md

**Comment by carolove** [comment]
thank you for your reply.
