### ISSUE TITLE
RPC called stacked at waitOnHeader

### ISSUE THREAD

**Issue by minaevmike** [grpc/grpc-go#4301]
Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
1.35.0
### What version of Go are you using (`go version`)?
1.16
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
I am requesting an external service, and sometimes request got stacked. 
In pprof I can see such thing
```
#	0x98ef38	google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader+0x98						/builds/bx/adv-search-api/.cache/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/transport.go:321
#	0xa12cd0	google.golang.org/grpc/internal/transport.(*Stream).RecvCompress+0x730						/builds/bx/adv-search-api/.cache/go/pkg/mod/google.golang.org/grpc@v1.35.0/internal/transport/transport.go:336
#	0xa12cbc	google.golang.org/grpc.(*csAttempt).recvMsg+0x71c								/builds/bx/adv-search-api/.cache/go/pkg/mod/google.golang.org/grpc@v1.35.0/stream.go:915
#	0xa1b245	google.golang.org/grpc.(*clientStream).RecvMsg.func1+0x45							/builds/bx/adv-search-api/.cache/go/pkg/mod/google.golang.org/grpc@v1.35.0/stream.go:780
#	0xa1079e	google.golang.org/grpc.(*clientStream).withRetry+0x9e								/builds/bx/adv-search-api/.cache/go/pkg/mod/google.golang.org/grpc@v1.35.0/stream.go:638
#	0xa11944	google.golang.org/grpc.(*clientStream).RecvMsg+0x104								/builds/bx/adv-search-api/.cache/go/pkg/mod/google.golang.org/grpc@v1.35.0/stream.go:779
#	0x9f2501	google.golang.org/grpc.invoke+0x141										/builds/bx/adv-search-api/.cache/go/pkg/mod/google.golang.org/grpc@v1.35.0/call.go:73				
#	0xa17073	google.golang.org/grpc.chainUnaryClientInterceptors.func1+0x133							/builds/bx/adv-search-api/.cache/go/pkg/mod/google.golang.org/grpc@v1.35.0/clientconn.go:365
#	0x9f21e8	google.golang.org/grpc.(*ClientConn).Invoke+0x108								/builds/bx/adv-search-api/.cache/go/pkg/mod/google.golang.org/grpc@v1.35.0/call.go:35
.....
``` 
And this goroutine stacked for 11 hours. Unfortunately, I can't reproduce this problem at my localhost.

**Comment by minaevmike** [comment]
Some additional info: client using grpc-go 1.35 server grpc-go 1.36

**Comment by menghanl** [comment]
https://github.com/grpc/grpc-go/blob/f9b209ab966ceeea260ac751ff9e60eb4cfcbb98/internal/transport/transport.go#L315-L331

This RPC is waiting for the response. More specifically, it's waiting for the response header, which includes the status code and metadata. But for unary RPCs, the header and message usually come together.

It's hard to tell why this happened, something to consider first:
1. Was it stuck in the server? Did the server send the response?
   - This would need server side logs, or set env var on the client side `GODEBUG=http2debug=2` to see http2 level logs
   - Also, it's always a good idea to set a timeout for the RPCs, and retry if it fails
2. Was there a connection problem? Sometimes TCP can break without sending FIN, and the endpoint wouldn't know, and will keep waiting
   - I doubt this though, because there's also TCP level timeout, and it's likely shorter than 11 hours
