### ISSUE TITLE
Backoff configuration API versions are unclear

### ISSUE THREAD

**Issue by riconnon** [grpc/grpc-go#4446]
Referring to the documentation here:
https://pkg.go.dev/google.golang.org/grpc

`grpc.DefaultBackoffConfig` is marked as deprecated with the command:
> Deprecated: use ConnectParams instead. Will be supported throughout 1.x.

Looking at `grpc.ConnectParams` it is marked as experimental, which says:
> Notice: This API is EXPERIMENTAL and may be changed or removed in a later release.

It seems insane to have a deprecated API which is superseded only by an experimental API. What is the correct method for specifying a back-off configuration for a production workload as of today?

**Comment by easwars** [comment]
[This](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md) is a detailed explanation of the exponential backoff protocol used in gRPC.

We initially had the following dial options:
- [WithBackoffMaxDelay](https://pkg.go.dev/google.golang.org/grpc#WithBackoffMaxDelay)
- [WithBackoffConfig](https://pkg.go.dev/google.golang.org/grpc#WithBackoffConfig)
But both of these allowed configuring only the `MaxDelay` parameter.

In order to comply with the [spec](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md), we added [WithConnectParams](https://pkg.go.dev/google.golang.org/grpc#WithConnectParams) which allows the user to configure all the parameters mentioned in the spec.

I would strongly encourage using the `WithConnectParams` API. Even though it is marked experimental, we haven't made any changes since we introduced it and we don't expect to make any changes in the foreseeable future. At some point, we would remove the experimental label and make this stable.
