### ISSUE TITLE
transport: validate :status header is 200 in gRPC mode

### ISSUE THREAD

**Issue by JNProtzman** [grpc/grpc-go#4451]
I'd like to discuss validating the :status header in gRPC mode. I thought I could throw in an `|| httpStatus != "200"` [here](https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_client.go#L1317) and that would validate the status per grpc mode request. The problem is that this causes a lot of test failures. I'm wondering if this is something that needs to be added to the test suite or if I'm maybe doing it wrong.  

@dfawley - I hope this ping is OK. If it's not please let me know and I won't do it again.

**Comment by dfawley** [comment]
That link doesn't look right -- I think you mean here maybe?

https://github.com/grpc/grpc-go/blob/23a83dd097ec07fc7ddfb4a30c675763e4972ba4/internal/transport/http2_client.go#L1321

But that isn't right because it's inside `if !isGRPC`.

Probably something around line 1342 would be needed?

https://github.com/grpc/grpc-go/blob/23a83dd097ec07fc7ddfb4a30c675763e4972ba4/internal/transport/http2_client.go#L1341-L1343

**Comment by dfawley** [comment]
Oh, I see, it looks like you meant:

https://github.com/grpc/grpc-go/blob/23a83dd097ec07fc7ddfb4a30c675763e4972ba4/internal/transport/http2_client.go#L1315 

If so, that seems right, and it doesn't surprise me that tests fail; especially if they are transport tests, they may be doing something manually that isn't 100% according to the spec.

**Comment by JNProtzman** [comment]
Sorry I linked master and it must have shifted but you're last comment is right. I took a stab at this - and ended up putting up a PR.
