### ISSUE TITLE
Unary gRPC calls timeout but server still receives it and not cancelled

### ISSUE THREAD

**Issue by ahtsan** [grpc/grpc-go#4580]
I have a client invoking unary gRPC request and retrying when each request times out, like

```
conn, err := grpc.Dial(serverURL, grpc.WithInsecure()
client = NewClient(conn)
...
for i := 1; i <= 10; i++ {
  ctx, _ := context.WithTimeout(context.Background(), time.Second * 5)
  
  rep, err = UnaryRPC(ctx)
  if err != nil {
    // retry after 5 sec
    time.Sleep(time.Second * 5);
  }
}
```

However, the server is still getting more than one (usually two) RPC calls. I have the server checked all these requests and see if the context is cancelled but all of them are not.

When a gRPC call timeout, does it cancel the context by default? If not, how can I make it do that?

**Comment by dfawley** [comment]
> When a gRPC call timeout, does it cancel the context by default? If not, how can I make it do that?

The context on the client is canceled by the context itself (`context.WithTimeout`).

The context on the server is canceled by two ways:
1. the deadline, determined when the RPC starts (in your case, 5s after it started), or
2. explicit cancelation on the client side, which is propagated to the server.

If the server returns an error directly, then the context won't have been canceled on the server side.

I don't understand the problem here.  The server could receive up to 10 calls in your example, since you try the RPC 10 times if there is any error (deadline OR otherwise).

**Comment by ahtsan** [comment]
Thanks for the reply. The problem is if the client had 5 retries, I'm seeing server receiving 2 requests with both context.IsCancelled() = false. That makes me think the context of the second last retry is not cancelled by grpc.

**Comment by ahtsan** [comment]
@dfawley

**Comment by ahtsan** [comment]
@dfawley any thought?

**Comment by dfawley** [comment]
I'm not sure I understand the confusion.  The context on the server for any given RPC should not be cancelled, since the RPC just started.  Note that in your example you are using a new context for every attempt.

**Comment by ahtsan** [comment]
In the example, I set the time out to 5 second just for illustration, I can also set it to 1 hour.

What I want to achieve is to have the client send a request with a timeout, and retry the request when it times out for up to 10 times. For example say the server is spawned 35 seconds after the client is spawned. If client timeout is 10 seconds, it should timeout the first 3 requests and when it makes the 4th request, the server side is up and receive the request. 

What I'm seeing is that ￼server received both the 3rd and 4th request, and the context of the 3rd request is not cancelled (I thought it would). In my case, server can only receive one gRPC call, and I couldn't find a way to avoid server receiving more than one.

**Comment by dfawley** [comment]
> What I want to achieve is to have the client send a request with a timeout, and retry the request when it times out for up to 10 times. For example say the server is spawned 35 seconds after the client is spawned. If client timeout is 10 seconds, it should timeout the first 3 requests and when it makes the 4th request, the server side is up and receive the request.

I'm not sure why you want to do this in the first place.  Why not set a timeout according to how long you are willing to wait?  Retries are only needed for _RPC failures_, not timeouts.

> What I'm seeing is that ￼server received both the 3rd and 4th request, and the context of the 3rd request is not cancelled (I thought it would).

From your example code, if the server returned a non-timeout error from the 3rd attempt, then a 4th attempt would still happen.  Instead of `if err != nil` you could do `if status.Code(err) == codes.DeadlineExceeded` to only retry on deadline exceeded errors.

> In my case, server can only receive one gRPC call

If it is an error for the server to receive an RPC more than once, then that sounds risky.  Generally, RPCs should be idempotent.  There are _many_ situations where the client cannot determine whether an RPC was received by the server when an error was returned.  E.g. the deadline could have hit right _after_ the server was responding to the RPC.  The client would see "deadline exceeded" due to network latency, but the server would see that it properly serviced the RPC.  There are other situations as well.  Networks are inherently racy, and you need to plan for such races.

**Comment by ahtsan** [comment]
These are very helpful suggestion and clear explanation, thank you!
