### ISSUE TITLE
Stream interceptor error at creation for authentication

### ISSUE THREAD

**Issue by malletgaetan** [grpc/grpc-go#4592]
### Problem
In the case that my service need authentication and client isn't authenticated, server-side interceptor will return an error. But the error will not be returned at the creation of the stream but with Recv() of the stream.

  ```go
conn, _ := grpc.Dial("myserveraddress:8080", grpc.WithTransportCredentials(credentials.NewTLS(nil)))
client := proto.NewClientControlServer(conn)
stream, err := client.StreamAllMoves(context.Background(), &proto.Id{Id: "1"})
  ```

In this example, even if the server interceptor return an error, err will still be nil as the connection succeed, but when reading the incoming data from stream, i'll get my authentication error.
  
### Question

  * I would like to setup a stream client interceptor (unary is just working just fine) that check if there is an authentication error, if there is, make a grpc call to another service to renew the auth token and remake the request. How could i do that?
 
#### stream client interceptor
```go
func streamClientInterceptor(auth *Authentication) grpc.StreamClientInterceptor {
	return func(parentCtx context.Context, desc *grpc.StreamDesc, cc *grpc.ClientConn, method string, streamer grpc.Streamer, opts ...grpc.CallOption) (grpc.ClientStream, error) {
		// callCtx, _ := context.WithTimeout(parentCtx, clientTimeout)
		stream, streamErr := streamer(parentCtx, desc, cc, method, opts...)
		// test stream error
		if streamErr == nil {
			return stream, nil
		}
		if code := status.Code(streamErr); code != codes.Unauthenticated {
			return nil, streamErr
		}
		// renew tokenauth
		res, err := auth.jwtCaller.Renew(parentCtx, &authpb.JWTToken{JWT: auth.refreshToken})
		if err != nil {
			return nil, errors.Wrap(err, "Grpc client failed to renew token")
		}
		if res.HttpStatusCode != int32(http.StatusOK) {
			return nil, errors.New(fmt.Sprintf("Grpc client failed to renew token with status=%d", res.HttpStatusCode))
		}
		if err := checkJWT(res.RefreshJWT); err != nil {
			return nil, errors.New("Renew returned malformed token")
		}

		auth.mu.Lock()
		auth.JWT = res.JWT
		auth.refreshToken = res.RefreshJWT
		auth.mu.Unlock()

		// callCtx, _ := context.WithTimeout(parentCtx, clientTimeout)
		return streamer(parentCtx, desc, cc, method, opts...)
	}
}
```

#### stream server interceptor
```go
func authStreamInterceptor(srv interface{}, stream grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) error {
	ctx, err := authorize(stream.Context())
	if err != nil {
		return err
	}
	return handler(srv, &wrappedStream{ss: stream, sc: ctx})
}
```

#### 

### Version
grpc 1.29.1

**Comment by malletgaetan** [comment]
Forgot the [project](https://github.com/malletgaetan/stream-interceptor) to reproduce :-)

**Comment by dfawley** [comment]
For streaming RPCs, stream creation is always successful (`streamErr == nil` near the top of your client interceptor) unless there is some kind of connection error.  This is because the stream needs to be created before the server needs to respond (with a bidi stream, the server may just sit and wait for hours before responding, so the client can't block until there is a response).

What you want is actually not really possible unless you have tight control over your server and client.  To receive the RPC error, you need to call `RecvMsg` on the stream.  To call `RecvMsg`, you need to know the message type in case a response message was sent before the stream's error, so it's not something you can typically do in an interceptor unless the actual client logic invoked a `RecvMsg` call.  Also, any number of `SendMsg` operations may be performed by a client before the server even finishes processing the RPC headers, which means you would need to cache them all.  An ugly sequence diagram:

```
Client                    Server
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RPC start----  (connection exists; stream object created client-side immediately)
             --       
Send1--        --
       --        --
         --        --
           --        --
Send2--      --        --
(etc)  --      ..      --
         --            -->|  RPC headers reach server
           ..             |  Interceptor Invoked
                       ---|  Auth Error Returned
                   ----
      <------------ (client receives auth error)
```

By the end of that sequence, to refresh the auth token and restart the RPC would require replaying all the send operations from the client on the new RPC.

Maybe there is another way you can do what you are wanting.  For example, perform a "dummy" unary RPC in your interceptor to determine whether the credentials need to be refreshed before starting the stream.

**Comment by malletgaetan** [comment]
Finally i did the Unary request in the stream creation, thanks for the clear explanation :)

**Comment by dfawley** [comment]
Great, I'm glad you found something that worked!
