### ISSUE TITLE
How to retrieve client connection at server side?

### ISSUE THREAD

**Issue by bglmmz** [grpc/grpc-go#4598]
I think a connection must setup between client and service while  a client calling the gRPC service,  so,  is there anyway to retrieve and reuse the connection at server side??
 I only found this method:
`peer, ok := peer.FromContext(ctx)`
but the peer only has addr info but no connection info.

**Comment by menghanl** [comment]
The connection is not exposed to the users.
Can you explain a bit more what you need the connection for?

**Comment by bglmmz** [comment]
I just try to develop a proxy service, it accepts the grpc services registration, and the proxy will forward the client's request to grpc service transparently. So, I want reuse the connection while the grpc service registering

**Comment by menghanl** [comment]
I still don't quite understand your requirement.

If you want to proxy at gRPC level, you won't need `net.Conn`.
Create gRPC clients to the real backends, and send the proto messages. You won't see the raw bytes.

If you want to proxy at TCP level (so that you read and send bytes from/to `net.Conn`), gRPC won't be involved.

**Comment by menghanl** [comment]
Closing this issue now. Please leave a comment if you have further questions.
