### ISSUE TITLE
Is it possible to log invalid connections/requests on server side?

### ISSUE THREAD

**Issue by powerman** [grpc/grpc-go#4666]
The problem is some client libraries on some languages don't log these issues with enough details for debugging, so it will be really helpful if server logs will contain this information. E.g. I'd like to see in server log:
- client connected without TLS and was rejected by server (probably this one already works, not sure)
- client connected without right CA cert or using IP instead of hostname matching server certificate and disconnected while TLS handshake because of this
- client sends non-gRPC request
- client send request using invalid gRPC service or method name

I.e. issues which happens before our handler is called.

**Comment by menghanl** [comment]
> client connected without TLS and was rejected by server (probably this one already works, not sure)

This should already be there

> client connected without right CA cert or using IP instead of hostname matching server certificate and disconnected while TLS handshake because of this

Handshake failures are already logged by the server.
ServerName verification happens only on the client side, so that cannot be detected by the server

> client sends non-gRPC request
> client send request using invalid gRPC service or method name

Logs like this can get quite spammy. So even if they are added, they should be behind a verbosity level.

Balancing between logs being informative or too spammy is tricky, and decisions are usually case by case.
The general logging guideline is https://github.com/grpc/grpc-go/blob/master/Documentation/log_levels.md.

If you think some logs are missing, feel free to send a PR to add them. We can discuss whether they are necessary or which level they should be in the PRs. Thanks!
