### ISSUE TITLE
Any known error that results to the shutdown of connection

### ISSUE THREAD

**Issue by XJangel** [grpc/grpc-go#4764]
I wanna ask is there any known error that results to the shutdown of connection in addition to the close the server. What should client do when encountering these errors?
Thanks a lot!

**Comment by menghanl** [comment]
Any connection error would cause the connection to shutdown.

The client automatically reconnects when there's a connection error. So the client usually doesn't need to do anything.

RPCs may fail due to a broken connection. [wait-for-ready](https://github.com/grpc/grpc-go/tree/master/examples/features/wait_for_ready) might help in some situations.

If you are running into connection errors, [turning on the logs](https://github.com/grpc/grpc-go#how-to-turn-on-logging) could also help.

**Comment by XJangel** [comment]
Actually I wanna know more about here [SHUTDOWN](https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md)
![image](https://user-images.githubusercontent.com/38457133/133394147-d060fafb-b709-4d9e-9766-da5bc3635fec.png)
Is there more info about non-recoverable errors since 6/12/2015?

**Comment by menghanl** [comment]
No. No error causes the Client to  turn SHUTDOWN.

**Comment by XJangel** [comment]
Get it! 
thank u!
