### ISSUE TITLE
How to simulate unreliable/lossy network conditions for integration testing?

### ISSUE THREAD

**Issue by iamlucaswolf** [grpc/grpc-go#4804]
I'm implementing a distributed consensus protocol (Raft) in Go on top of gRPC. To verify correctness, I would like to test whether servers act according to spec in the face of certain edge cases (packet loss, network delays, disconnects, etc...)

Is there a way to simulate these network behaviors in gRPC (preferably, in a way that is compatible with `go test`)? 

So far, I have considered the following options:

- Run the servers as isolated processes on several containers/VMs connected by a virtual network. This is probably the closest to real-world operation, but requires substantial extra coordination/shell scripting

- MIT's 6.824 course features a [lab exercise](https://pdos.csail.mit.edu/6.824/labs/lab-raft.html) around Raft (though without gRPC). The grading test suite runs each server in its own goroutine and mocks all RPC calls. This Dependency-Injection-style approach has great ergonomics and configurability, but comes with substantial overhead (they essentially wrote custom versions of `rpc` and `gob` to make it work). Also, pursuing a similar path for mocking gRPC calls/endpoints would likely increase the delta to real-world behavior.

Any suggestions? Anything I'm overlooking? Thanks a lot in advance!

**Comment by dfawley** [comment]
This is not a feature of grpc-go, but we have a couple tools that might be able to help you:

An in-memory listener/dialer pair:
https://pkg.go.dev/google.golang.org/grpc/test/bufconn

A way to inject "realistic" (non-variable) latency into a conn/listener/dialer:
https://pkg.go.dev/google.golang.org/grpc/benchmark/latency

You should be able to use the above as a model for injecting variable delays or connection loss instead of a constant latency.  Since these (and gRPC) are all TCP-based, packet loss isn't really a concern -- it would just look like a long delay to the application.  Good luck!
