### ISSUE TITLE
client retry question related to the retry feature

### ISSUE THREAD

**Issue by jwomackgsa** [grpc/grpc-go#4937]
In my current code using grpc-go 1.40, I am using some wrapper code to facilitate client rpc retries when a broken connection is detected.  I am not currently re-dialing, but instead using the `ResetConnectBackoff()` and some state logic to continuing retrying.

In upgrading to 1.41, my code no longer works as intended due to what appears to be the reconnection mechanism cycling to an IDLE state before attempting reconnection.  I am investigating converting to the retry service config capability, but I had a question.  My current "max retries" code is based on a duration threshold instead of a retry count.  Does anyone know if the retry configuration can used in this way.  It appears from the features docs that its limited to a max count of 5 with configurable retry intervals, but there didn't appear to be a way to recycle that service config to potentially make it continually retry with out redialing.  I am fairly new to grpc so maybe there is a better approach than what I am doing today.

**Comment by dfawley** [comment]
> ResetConnectBackoff

This should only _very_ rarely be needed.  Basically if you know your network was disconnected for some time and became reconnected due to an external event (e.g. you were just notified wifi connected).

> In upgrading to 1.41, my code no longer works as intended due to what appears to be the reconnection mechanism cycling to an IDLE state before attempting reconnection

What is your LB policy?  If you aren't setting it, it would be pick first.  Pick first will reconnect (leave IDLE) when new RPCs are dispatched.  I don't believe this subtle behavior change re: IDLE should affect you.  Unless you are using a custom LB policy (which is unusual) or polling the connectivity state (which you almost definitely don't need to do).

> there didn't appear to be a way to recycle that service config to potentially make it continually retry with out redialing

If you need unlimited retries, you would need to do that in the client code directly or via an interceptor.  Our retries do end after 5 attempts.  Is your network extremely unreliable?  Unless your network is down completely, you shouldn't get more than one failure on an RPC due to connection loss (i.e. the reconnect should be successful, and nothing fails while it's reconnecting).

Also I'm not sure what you mean about "without redialing".  You should never need to create the client via grpc.Dial more than once.  The connection management in the client should be sufficient for your needs unless you are doing something very unusual.

**Comment by jwomackgsa** [comment]
Thanks for looking into my question.  So let me start with some responses to your LB question.  

> What is your LB policy?

I am currently not setting an LB policy.  The server end is a single node.

I apologize I didn't go into my details in the original question so here is that if it helps explain my situation a bit.  
The client and server will run within a WAN environment that is mostly stable but does have periodic issues with carriers.  The general purpose of the RPC is for the client to call and start a long running process.  It when will use a unary query to regularly get status of that process.  Right now the client dials once, then just loops at a define interval calling the RPC watching for state of the server process.  This process could go on for several hours.  I want to be able to set a time out of say 3 hours so that if the client connection with the server goes dead (say ISP goes out for 30 minutes), the RPC will keep trying for up to 3 hours to reconnect before finally bailing.  

I am fine with handling this with client code but just looking for best approach to handle dead remote connections and retrying for an unlimited amount of times during a prescribed duration.  If I detect an Unavailable code when trying to call the RPC on a dead connection, do I just need to let the client do its retry on its own and will it continue to do so or will it eventually give up trying to move back to a READY state.  

At the end of the day, I am trying to make a process that will be less likely to break with future updates and still meets the business requirements.

**Comment by dfawley** [comment]
> I am fine with handling this with client code but just looking for best approach to handle dead remote connections and retrying for an unlimited amount of times during a prescribed duration. If I detect an Unavailable code when trying to call the RPC on a dead connection, do I just need to let the client do its retry on its own and will it continue to do so or will it eventually give up trying to move back to a READY state.

Yes!  The `ClientConn` will maintain a connection to the backend and continue to retry indefinitely _as long as it has pending RPCs_.  Outstanding RPCs will fail when each connection attempt fails unless you set `WaitForReady` on them, in which case they will only be stopped when their deadline is exceeded or after they start and then complete normally or die due to a subsequent connection loss.

Also there should be no need to call `ResetConnectBackoff` unless you are aware when your connection returns due to an external signal.  This causes the client to attempt to reconnect immediately, as opposed to waiting for the backoff period to end.

With connectivity issues, you may also be interested in keepalive support to detect a connection loss more quickly:
- https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md
- https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md
- https://pkg.go.dev/google.golang.org/grpc/keepalive

**Comment by jwomackgsa** [comment]
Thank you for the guidance.  I will review all the docs and the examples and see if I can put this into place in-lieu of my current code.
