### ISSUE TITLE
xDS server spams mode "switches"

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-go#4939]
When trying to debug a (non-Go) problem, I was looking at logs and discovered that Go xDS server is very spammy.

Per [A36 xDS for Servers](https://github.com/grpc/proposal/blob/master/A36-xds-for-servers.md):
> If the application does not register the callback, XdsServer should log any errors and each serving resumption after an error, all at a default-visible log level.

Go appears to be broken in multiple ways:
1. The logs occur even if the application provides a callback
2. The logs occur even for transitions from SERVING to SERVING. The only time the default logger should log in SERVING state is if immediately previously there was an error state

https://github.com/grpc/grpc-go/blob/e469f0d5f5bcc1324dc3940c584e0969e2ea1f90/xds/internal/server/listener_wrapper.go#L432-L442

This is much more mild, but for a reason that I don't understand, the xds interop test server is providing its own callback. That seems unnecessary given the default behavior. But it will log up to two times per event:

https://github.com/grpc/grpc-go/blob/b9d7c74e01f89a52880332f584776ccfe0c27756/interop/xds/server/server.go#L102-L107

It would be more clear as a single log entry.

**Comment by zasweq** [comment]
From chat: Eric Anderson, 4 min
I'm seeing weird behavior in Go server.
https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22bct-gcestaging-guitar-grpc%22%0Aresource.labels.container_name%3D%22psm-grpc-server%22%0Aresource.labels.namespace_name%3D%22psm-interop-server-20211103-0810-vbyi9%22;timeRange=2021-11-03T08:12:53.955756Z%2F2021-11-03T09:12:53.955793Z;cursorTimestamp=2021-11-03T08:14:12.898921552Z?project=bct-gcestaging-guitar-grpc
At 2021-11-03 08:14:12.898 GMT there is a log entry for a Listener that contains RBAC configuration containing:                                            "authenticated": {
                                              "principalName": {
                                                "safeRegex": {
                                                  "googleRe2": {

                                                  },
                                                  "regex": "+*"
                                                }
                                              }
                                            }
It appears the server accepts that happily. At 2021-11-03 08:14:12.902 GMT it enters SERVING.[xds] [xds-server-listener 0xc000222b60] Listener "0.0.0.0:8080" entering mode: "SERVING" due to error: <nil>

Eric Anderson, Now, Edited
That repeats for a while (is xds client not filtering updates? I don't know why the logging callback keeps getting called)

Eric Anderson, Now
But then, minutes later, at 2021-11-03 08:16:17.363 GMT it seems to have noticed the configuration is (correctly) invalid:[xds] [xds-server-listener 0xc000222b60] route configuration construction: virtual host construction: filter construction: error constructing matching engine: safe_regex matcher "+*" is invalid

**Comment by ejona86** [comment]
@zasweq, that is different from this bug.

**Comment by ejona86** [comment]
I think the logging is even more wrong than I thought. I created a trash bootstrap (`td-grpc-bootstrap --gcp-project-number 5`) and ran on my local machine without any credentials.

```
examples/features/xds/server$ ./server
2021/11/30 16:03:34 Serving GreeterService on 0.0.0.0:50051 and HealthService on 0.0.0.0:50052
```

And nothing more. Minutes later, nothing more. But I know it has to be failing to start the xds server... I'd expect a message at least after 20 seconds of inability to get listener resource. In this case I'd hope it wouldn't even be delayed 20 seconds. It hasn't bound yet to the xds server port:

```
$ ss -ltn | grep 5005
LISTEN 0      4096         0.0.0.0:50052       0.0.0.0:*          
```

Running with `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info` shows me the errors I expected are actually happening.

```
2021/11/30 15:56:26 WARNING: xds: ADS stream creation failed: rpc error: code = Unauthenticated desc = transport: context canceled
2021/11/30 15:56:27 WARNING: xds: ADS stream creation failed: rpc error: code = Unauthenticated desc = transport: context canceled
2021/11/30 15:56:30 WARNING: xds: ADS stream creation failed: rpc error: code = Unauthenticated desc = transport: context canceled
2021/11/30 15:56:33 WARNING: xds: ADS stream creation failed: rpc error: code = Unauthenticated desc = transport: context canceled
2021/11/30 15:56:40 WARNING: xds: ADS stream creation failed: rpc error: code = Unauthenticated desc = transport: context canceled
2021/11/30 15:56:50 WARNING: xds: ADS stream creation failed: rpc error: code = Unauthenticated desc = transport: context canceled
2021/11/30 15:57:10 WARNING: xds: ADS stream creation failed: rpc error: code = Unauthenticated desc = transport: context canceled
2021/11/30 15:57:36 WARNING: xds: ADS stream creation failed: rpc error: code = Unauthenticated desc = transport: context canceled
```

**Comment by ejona86** [comment]
I still see no warnings by default when unable to connect.

I notice now I also don't see any useful errors (even with `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info`) with garbage like `GRPC_XDS_BOOTSTRAP=/not/exist`.
