### ISSUE TITLE
Is returning objects to pool in custom codecs safe?

### ISSUE THREAD

**Issue by brancz** [grpc/grpc-go#5000]
First of all, I apologize if there is an issue or documentation about this, if so I was not able to find it.

We have a workload written in Go that reads a lot of proto objects from a key-value store, and eventually returns them, and more in a gRPC message. We'd very much like to introduce pooling for this, as allocations for this take a considerable amount of CPU time according to profiling data. Obtaining the proto struct from a pool is no problem since we control the call-site where the unmarshaling happens, but how could one have gRPC return the object to a pool once gRPC is done marshaling? One place that seems theoretically possible could be a custom codec that checks for the specific type of object and after marshaling resets and returns structs back to the pool. Would this be safe to do?

**Comment by dfawley** [comment]
What is the context here?  Are you talking about server-side, unary/client-streaming RPCs only?  I.e. the message is returned by the handler, which is why you can't do it in the application code?  For client-side or streaming RPCs, the obvious way to do this would be to access the pool from the application directly.

What is the nature of this pool?  Are you sure re-using it will have the benefit you are expecting?  We used to re-use protobuf structs in our codec itself, saving them in a `sync.Pool`, but it turned out to not provide any meaningful benefit, so we removed it.  Are you only reusing the memory to avoid the allocation, or are you reusing the complete protobuf struct, including the data?

Doing this in the codec seems possible.  There is one interaction that could be problematic here, however: stats handlers receive a pointer to the proto message struct after the codec is invoked.  If the struct could be freed/reused before the stats handler is invoked, then this would be wrong/racy/invalid.  (Also, for the same reasons: binary logging and tracing could be impacted similarly.)

One other thing that could theoretically work here: we have a `PreparedMsg` type that allows you to pre-encode a message.  The intent of this was if you were going to send the same message multiple times, you could prepare it once and then avoid re-encoding it for subsequent transmissions.  Given this, it only currently works for streaming RPCs.  However, I think we could adjust it so it would also work for unary RPCs.  At that point, you could encode the proto response, return the proto struct to the pool, then return the `PreparedMsg` from the RPC handler instead of the proto struct.

**Comment by brancz** [comment]
> Are you sure re-using it will have the benefit you are expecting?

No way to know if we can't try :slightly_smiling_face:. Profiling data clearly shows that allocating the objects is a major cause of CPU cycles in our system, and consequently also in GC time.

> What is the nature of this pool?

You can vaguely think of the request flow like this:

1) Unary gRPC request comes in containing essentially a query for data.
2) Data is queried from a columnar database (this part is very fast)
3) Data retrieved in 2) contains potentially 1000s of references to metadata
4) The references to metadata are resolved and read from a key-value store, the items in the key-value store are marshaled as proto.
5) The data from 3 is transformed into a report and the data from 4 is practically unchanged embedded into the resulting gRPC response.

The theory is, we could return the embedded structs from the gRPC response back to a pool, that we would initially take from the pool where we unmarshal the proto objects coming from the key-value store in 3).

> One other thing that could theoretically work here: we have a PreparedMsg type that allows you to pre-encode a message. The intent of this was if you were going to send the same message multiple times, you could prepare it once and then avoid re-encoding it for subsequent transmissions. Given this, it only currently works for streaming RPCs. However, I think we could adjust it so it would also work for unary RPCs. At that point, you could encode the proto response, return the proto struct to the pool, then return the PreparedMsg from the RPC handler instead of the proto struct.

This sounds like it could work for us, but as mentioned above we do need it for a unary RPC, how much work would this be to implement for unary RPCs? If it's a reasonable amount of work I could give it a try, and use a patched version of grpc-go to see if we would get the gains we imagine.

**Comment by dfawley** [comment]
It sounds like from your description that you're still doing the same amount of marshalling and unmarshalling, then, just reusing the structs.  This might be helpful if the struct is pretty flat, but probably not much if the struct is nested and deep.

For a proof of concept, I would just use the codec as you suggested.  I'm pretty sure adding support for unary RPCs to `PreparedMsg` would involve an API change (passing the stream's context instead of the stream).  It's possible the protobuf team might have suggestions for reducing allocations, as well.
