### ISSUE TITLE
Support TLS1.3 ECDHE key-exchange between grpc client and server

### ISSUE THREAD

**Issue by alok87** [grpc/grpc-go#5001]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
TLS1.2 uses the key exchange algo as RSA in which the key maintenance infrastructure needs to be in place. ECDHE is used in  TLS1.3 instead of RSA for key exchange. Please add support for exchanging symmetric key using ECDHE algorithm which is efficient as well as does not require key maintenance.

### Proposed Solution
Support TLS1.3 ECDHE  https://en.wikipedia.org/wiki/Elliptic-curve_Diffie%E2%80%93Hellman

Please let me know if it is already supported. In that case, i would happily close the issue. Do we have an example in that case?

**Comment by alok87** [comment]
Certificate management is still required with ECDHE as server needs to sign the public key with a CA and then send to the client so that client knows the data is coming from the server and not someone else. 😢

**Comment by zasweq** [comment]
@ZhenLian are you familiar with this?

**Comment by ZhenLian** [comment]
Thanks @zasweq for bringing this up to me!

> Please let me know if it is already supported. In that case, i would happily close the issue. Do we have an example in that case?

You can change the cipher suites being used by specifying `CipherSuites` in `tls.Config`. You can find your wanted suites in https://go.dev/src/crypto/tls/cipher_suites.go.

> Certificate management is still required with ECDHE as server needs to sign the public key

Yes. Changing the cipher suite being used from `RSA` to `ECDHE` still requires the role of CA to be in place. In general, if you want to use TLS, the certificate management shall be in place, because that's part of today's PKI infrastructure.

Depending on your goals, you might want to try the following:
1. if you want to achieve the similar protection as TLS, you can try [ALTS](https://cloud.google.com/security/encryption-in-transit/application-layer-transport-security). Fortunately, it is already available in [gRPC-Go](https://github.com/grpc/grpc-go/blob/master/credentials/alts/alts.go). The main difference is that in ALTS, you trust Google to help you manage the certificates, and the communications are all done through a handhaker service(CC @cesarghali for more).
2. Use token-based authentication, like [Oauth token](https://github.com/grpc/grpc-go/tree/master/credentials/oauth) or [STS](https://github.com/grpc/grpc-go/tree/master/credentials/sts), or implementing your own [PerRpcCredentials](https://github.com/grpc/grpc-go/blob/master/credentials/credentials.go#L37). Depending on the scenarios, this may be more or less complicated than TLS, as you might need to implement your own logic to handle token management.
3. find a third-party service that can handle certificate management for you
4. use insecure credentials.  This is highly discouraged in production services, as it leads your application to a lot of threats. But in some test environment it might be OK.

CC @yihuazhang in case I miss anything.

**Comment by alok87** [comment]
Thank you for such a detailed response. It helps. :)

I am building for AWS, so no ALTS. I will go with mutual TLS+certificate management by kubernetes controller(cert-manager).

Can we add an example or can you suggest how to add tls1.3+ECDHE? I will give a PR for it.

Tls1.3 constants for ECDHE for CipherSuites does not exist.

**Comment by dfawley** [comment]
> Can we add an example or can you suggest how to add tls1.3+ECDHE? I will give a PR for it.

@ZhenLian is this something worth having an example for here?  Or can it be accomplished with just setting things in tls.Config?

**Comment by ZhenLian** [comment]
It can be accomplished by setting tls.Config, so it's probably not worthwhile to add an example here.

@alok87 You can set this by the following steps:
1. find the cipher suites you want in https://go.dev/src/crypto/tls/cipher_suites.go
2. create the credentials using  [NewTLS](https://github.com/grpc/grpc-go/blob/712e8d4f57fd4a4fbb83406148f9c71eb3e7714e/credentials/tls.go#L141), with the cipher selected in 1) specified in the `tls.Config.CipherSuites`(see[ this article](https://grpc.io/docs/guides/auth/#with-server-authentication-ssltls) for more)

**Comment by alok87** [comment]
Thanks
