### ISSUE TITLE
Distinguishing  READY to IDLE state cases

### ISSUE THREAD

**Issue by adibrastegarnia** [grpc/grpc-go#5008]
Hi
Based on this document: https://grpc.github.io/grpc/core/md_doc_connectivity-semantics-and-api.html a READY state can go to IDLE state if 

- No RPC activity on channel for IDLE_TIMEOUT
- upon receiving a GOAWAY while there are no pending RPCs.

If I understand those correctly, the second one happens if the server is closing the connection (for any reasons). I am tying to use https://pkg.go.dev/google.golang.org/grpc#ClientConn.WaitForStateChange function to monitor state changes for detecting failures but I don't know how can I distinguish READY to IDLE state changes from each other? when there is a server failure, If there is no RPC call after failure, I see READY to IDLE state change but if there is an RPC call after server failure, I see READY to CONNECTING to TRANSIENT FAILURE changes.

**Comment by dfawley** [comment]
> No RPC activity on channel for IDLE_TIMEOUT

Note that this isn't supported in grpc-go.  I believe only grpc-java has it.

> I don't know how can I distinguish READY to IDLE state changes from each other?

I assume you're doing this for health reporting reasons?  (If your client isn't attempting RPCs, then the distinction is not really important otherwise.)

If you need to know the health of the remote peer, and if you want do do it based on reachability alone, then the easiest way would be to call `ClientConn.Connect` when you see the state go to IDLE.  If a connection attempt fails, it will go into TRANSIENT_FAILURE (for the duration of some exponential backoff period; it will go back to IDLE after it expires).

Reachability is only one part of server health, however, so it might be better to use something like a health check instead:
- https://github.com/grpc/grpc/blob/master/doc/health-checking.md
- https://github.com/grpc/proposal/blob/master/A17-client-side-health-checking.md

Let us know if you have any further questions about this topic, or if the above does not answer your question.

**Comment by adibrastegarnia** [comment]
@dfawley thanks for your response. I will check them out and get back to you if I have more questions on this topic.

**Comment by adibrastegarnia** [comment]
@dfawley 
Related to to this topic: Is there a way If we want to use HTTP2 Ping mechansim without using the the abstraction introduced part of the keep alive https://github.com/grpc/grpc-go/blob/v1.43.0/keepalive/keepalive.go#L27? I was reading some article in the web about using gRPC keep alive and it seems some sort of coordination between the client and server is needed and potentially could be tricky. Can we use HTTP2 Ping without dealing with those coordination?

**Comment by dfawley** [comment]
> Related to to this topic: Is there a way If we want to use HTTP2 Ping mechansim without using the the abstraction introduced part of the keep alive v1.43.0/keepalive/keepalive.go#L27?

No; this keepalive support is the only way to configure clients to send pings.

> it seems some sort of coordination between the client and server is needed

With keepalives, the coordination needed is that the server _should_ be configured to allow pings as frequently as the client is configured to be sending them.  However, the client will scale back its pinging if it receives the expected HTTP/2 error 
code  (GOAWAY w/ENHANCE_YOUR_CALM) because the server is configured too conservatively.

> could be tricky if the server ignores such ping traffic

HTTP/2 servers can't "ignore pings" or they are not properly implementing the HTTP/2 spec.

**Comment by adibrastegarnia** [comment]
@dfawley 
thanks for your response. But I read somewhere the server can close the connection if the client sends too many pings which is problematic. Is this a true statement?

**Comment by dfawley** [comment]
> the server can close the connection if the client sends too many pings which is problematic

Yes, this is what I meant above.  If the client is pinging too frequently, the server may close the connection, but the client will scale back its rate to make that less likely to happen again.  The scaled back rate will be remembered and used on all subsequent connections to that address.  Your clients should already be tolerant to connection loss, so this shouldn't be too problematic if it does happen.

**Comment by adibrastegarnia** [comment]
I see. how does the client scale back? Is it something we should implement part of the code to determine the good rate or is there any abstractions or parameters we can use to do that? when you say scale back does it mean changing client parameters at runtime if it is needed?

**Comment by dfawley** [comment]
The scaling is automatic.  The client will ping at half the previous rate when it reconnects and keep doing that until it reaches a rate the server is happy with.

https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md#basic-keepalive

> When a client receives a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings", it should log the occurrence at a log level that is enabled by default and double the configure KEEPALIVE_TIME used for new connections on that channel.
