### ISSUE TITLE
How to use `DialContext` with multiple endpoints using a cert for multiple domains?

### ISSUE THREAD

**Issue by rkapka** [grpc/grpc-go#5014]
I have a certificate that is valid for `sub1.domain.com` and `sub2.domain.com`. On the client side, I use the following code:
```
grpc.DialContext(ctx, "sub1.domain.com:4000,sub2.domain.com:4000", dialOpts...)
```
where `dialOpts` contain the certificate.

I get the following output:
```
"transport: authentication handshake failed: x509: certificate is valid for sub1.domain.com, sub2.domain.com, not sub1.domain.com:4000,sub2.domain.com:4000"
```

It's as if the two domains passed to `DialContext` are treated as one. Using the same certificate and passing only one domain to `DialContext` works fine.

**Comment by easwars** [comment]
[DialContext](https://pkg.go.dev/google.golang.org/grpc#DialContext) accepts a single target string, which needs to comply with the following [spec](https://github.com/grpc/grpc/blob/master/doc/naming.md).

Passing comma-separated targets is not a valid input. Did you find any documentation to the contrary?

**Comment by rkapka** [comment]
First of all, this is our issue: https://github.com/prysmaticlabs/prysm/issues/9049

> This only works well if it's unsafe.

I confirm that I can connect to the gRPC server that's running on `localhost:4000` by specifying the string `localhost:5000,localhost:4000`. I think this might have to do with [gRPC load balancing](https://grpc.io/blog/grpc-load-balancing/).

The spec that you mention does say this:

> The following schemes are supported by the gRPC C-core implementation, but may not be supported in other languages:
    ipv4:address[:port][,address[:port],...] -- IPv4 addresses
        Can specify multiple comma-delimited addresses of the form address[:port]:

It looks like grpc-go supports this feature.

**Comment by menghanl** [comment]
In the spec, `ipv4:address[:port][,address[:port],...]` is about a resolver scheme `ipv4`. This isn't supported in grpc-go.
And if it were supported, the target should look like `ipv4:192.168.1.1:4040,192.168.2.2:8080`. Note that these are ip addresses, and the scheme is `ipv4`

What you wanted is a client channel with multiple targets. But what we normally recommend is to make a client for each target.

If you really to do that, you can implement your own resolver, which splits the input `sub1.domain.com:4000,sub2.domain.com:4000`, and returns one address for each. See https://github.com/grpc/grpc-go/tree/master/examples/features/name_resolving for how to write a name resolver.

In the returned address, make sure that you set [`address.ServerName`](https://pkg.go.dev/google.golang.org/grpc/resolver#Address), so that TLS handshake will use the correct server name.

**Comment by rkapka** [comment]
So to make things clear, are you saying that `grpc.DialContext(ctx, "sub1.domain.com:4000,sub2.domain.com:4000", dialOpts...)` will not switch over to the second server when the first one is unavailable?

**Comment by menghanl** [comment]
Do you use a custom dialer? I don't think the default dialer handles multiple addresses like this.
