### ISSUE TITLE
server: add support for server base context

### ISSUE THREAD

**Issue by derekperkins** [grpc/grpc-go#5016]
### Use case(s) - what problem will this feature solve?

Many apps will want to inject base data into a context: e.g. app/service name for tracing and metrics. Often that is automatically populated by a core daemon runner that expects propagation throughout the program. Currently that is impossible with the grpc server - there are 147 references to `context.Background()` in this repo.

### Proposed Solution

A new field in `Server` called `baseCtx` which defaults to `context.Background()`, to be filled by a new `ServerOption` called `WithBaseContext`. Any references to `context.Background()` would be replaced with `s.baseCtx`. This would be 100% backwards compatible and should have minimal impact to the codebase, and zero impact to users.

### Alternatives Considered

We currently inject context data inside the first grpc interceptor which handles about 80% of the use case, but that requires some code duplication from our core daemon package, and we lose some timeout control.

Here's an example of someone trying to "merge" contexts, but they only are able to watch for timeouts, any data inside the context is not merged.
https://stackoverflow.com/a/58489004/1691542

### Additional Context

A prior request was made in 2015 (https://github.com/grpc/grpc-go/issues/113), closed by OP because passing a DB object is discouraged. There are still many valid reasons to inject values into a root context.

**Comment by dfawley** [comment]
This request would violate this (from https://pkg.go.dev/context):

```
Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it.
```

One alternative would be to accept a context in a new version of `grpc.Serve()`, and pass the context down to transport creation.  (Where we then store it in a struct...sigh...)

The biggest problem I see is that it's probably very difficult to honor context cancelation properly if we do this (or the original suggestion).

Can you better explain why an interceptor is inefficient/suboptimal for your use case?  I would think dropping in an interceptor to add to the context as the first interceptor in `Chain{Unary,Stream}Interceptor` would be a reasonable way to do what you want.

**Comment by derekperkins** [comment]
I think the recommendation to not store context in a struct is for the general use case, and as with all things, there are exceptions, and I think the grpc server is one of those. It's fundamentally not that different from using the global var that is returned by `context.Background()`. The server is the entrypoint to the system, and thus uniquely situated to provide a root context object that is propagated everywhere.

The stdlib http server provides similar semantics (truth be told I just discovered it), though theirs is a function that provides the listener as a parameter https://pkg.go.dev/net/http#Server. While I don't have a reason to reference that function, I think it would make sense to mirror the stdlib, for consistency and because I trust the authors to have thought through the edge cases.

> The biggest problem I see is that it's probably very difficult to honor context cancelation properly if we do this

Where would you see this being an issue? Is it specifically the need to listen for the context cancelation to trigger a shutdown? Other than that, I'm not sure where the grpc lib would need to handle anything not already handled by context natively.

**Comment by dfawley** [comment]
> Where would you see this being an issue? Is it specifically the need to listen for the context cancelation to trigger a shutdown?

Yes, and we'd want to be sure everything downstream is handled correctly too.

**Comment by derekperkins** [comment]
> Yes, and we'd want to be sure everything downstream is handled correctly too.

FWIW, the stdlib server does not appear to handle any of those edge cases from the original commit, nor in a scan of the server code. https://go-review.googlesource.com/c/go/+/167681 While it would be nice to have things more integrated, I can also see the argument for not being overly worried about people misusing it.

@bradfitz As the author of the BaseContext code in `net/http`, do you have any suggestions?

Here's a reference to the original issue and discussion about adding `BaseContext` and `ConnContext` to the `net/http.Server` struct. https://github.com/golang/go/issues/30694

**Comment by derekperkins** [comment]
Given that the stdlib server has implemented this, I think the grpc server should mirror that implementation, and I think it's fine to just comment it saying that canceling the base context will result in undefined behavior.

**Comment by dfawley** [comment]
Any thoughts on this question?

> Can you better explain why an interceptor is inefficient/suboptimal for your use case? I would think dropping in an interceptor to add to the context as the first interceptor in Chain{Unary,Stream}Interceptor would be a reasonable way to do what you want.

**Comment by derekperkins** [comment]
These are the main reasons, plus most of the other discussion for the stdlib addition are equally relevant here:
- Often there are values you want to inject at server creation that aren't readily available elsewhere
- You can't merge contexts, so you have to discard the first interceptor context without knowing if it contains anything valuable and use your own
- Depending on your setup, if you have devs setting up interceptors manually, it's very likely that you can't enforce that your interceptor is the first, rendering the prior point untenable

**Comment by dfawley** [comment]
> Often there are values you want to inject at server creation that aren't readily available elsewhere

Interceptors are injected at server creation, so I'm not really understanding this.  Can you give an example?

> You can't merge contexts, so you have to discard the first interceptor context without knowing if it contains anything valuable and use your own

What's the use case for this?  I was assuming the interceptor would simply do:
```go
ctx = context.WithValue(ctx, <key>, <value>)
```
...and not "merge contexts".

> Depending on your setup, if you have devs setting up interceptors manually, it's very likely that you can't enforce that your interceptor is the first, rendering the prior point untenable

How can you enforce that they will use `grpc.BaseContext(somelib.BaseContext())` (e.g.) when creating the server, but can't enforce that they list your interceptor first?

**Comment by derekperkins** [comment]
It's not uncommon to declare a base context in `main()` and inject global values into it. In order to use that context with an interceptor, you have to discard the original context in order to use your base context. `context.WithValue` isn't usable because you don't know what values were injected. These are all the same reasons that were discussed at length and ended up with a stdlib change to the `http.Server`.

```
package main

import (
	"context"

	"github.com/grpc-ecosystem/go-grpc-middleware"
)

func main() {
	baseContext := SetBaseContextValuesForTracingAndMetricsAndWhatever(context.Background())

	contextInterceptor = func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
		return handler(baseContext, req)
	}

	myServer := grpc.NewServer(
		grpc.UnaryInterceptor(grpc_middleware.ChainUnaryServer(
			contextInterceptor,

			grpc_ctxtags.UnaryServerInterceptor(),
			grpc_opentracing.UnaryServerInterceptor(),
			grpc_prometheus.UnaryServerInterceptor,
			grpc_zap.UnaryServerInterceptor(zapLogger),
			grpc_auth.UnaryServerInterceptor(myAuthFunction),
			grpc_recovery.UnaryServerInterceptor(),
		)),
	)
}
```

**Comment by todpunk** [comment]
I think specifically an Interceptor that is required to be the first in a chain is limiting just because only one can be first, and if several Interceptors in the community require this to be first for various desirable functionality add-ins, and we're expecting that behavior to be clobbering things, this is just a problem easily avoided by allowing a base context like contexts are expected to be, and letting order of Interceptors not matter for context specifically.

It limits the blast radius of contention around context manipulation, essentially. You still have contention of course, but it's in nuances of the context that exist without this issue discussion such as key/value namespacing, not in _the whole context object_ as it were.

I could be off here of course, I'm no expert and am happy to be corrected in my thinking.

**Comment by dfawley** [comment]
> I think specifically an Interceptor that is required to be the first in a chain is limiting just because only one can be first, and if several Interceptors in the community require this to be first for various desirable functionality add-ins

This is always going to be a potential concern, and not one that can be solved by this.

> and we're expecting that behavior to be clobbering things,

There should be no clobbering.  Any interceptor that doesn't return a child of the provided context is very risky territory.

For the sample code above, it _should_ be rewritten as:

```go
func main() {
	contextInterceptor = func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
		ctx = SetBaseContextValuesForTracingAndMetricsAndWhatever(ctx)
		return handler(ctx, req) // does not discard or ignore ctx
	}
	...
}
```

The only compelling reason I could see to inject a context would be for cancelation reasons ("`baseContext.Cancel()` shuts down everything in my application cleanly"), which would be a nice property.  But that wouldn't actually help, here, since closing the listener is necessary to make `Serve` exit.  For simple state propagation, an interceptor seems like a perfectly suitable way of doing this.  Yes, ordering matters more when you do this, but I don't see any way around that.  Ordering of interceptors is always going to matter (e.g. don't put your logging interceptor before your rate limiting or auth interceptors), which might be one reason why the original API for gRPC-Go only had a single interceptor and left it up to the user to write a wrapping interceptor that delegates to the other interceptors.

**Comment by derekperkins** [comment]
> For the sample code above, it should be rewritten as

I understand that for my trivial code example, but that's not always possible. I was trying to keep our specifics out of it, but for anyone doing Go well, they almost guaranteed have some sort of wrapper in main that handles a lot of boilerplate: listening for `os.Signal`, context initialization, serving health checks, pprof, metrics, tracing defaults, etc. For us, this is what that looks like, and it does include a global context cancelation during the shutdown process.

```go
func main() {
	daemon.Main(func(c context.Context, d *daemon.Daemon) error {
		return doUserThings(c)
	})
```

There is literally no way to support that in the grpc server today without clobbering the context in the first interceptor.

**Comment by dfawley** [comment]
How about something like this to merge the values in `baseContext` with the context passed to your interceptor?

https://go.dev/play/p/vLeZ5QpqnME

**Comment by derekperkins** [comment]
I suppose you could do something like that, though I think you'd also have to spin up a goroutine to watch for both cancelations. Seems counter to how context was intended to be used.

Do you not find the change to `http.Server` compelling? Personally I'd consider a change to the stdlib to have a higher bar to entry than anything else, given the compatibility promise. IMO that change was less important than this change, because http middleware never had context, so I was able to close over the base context in the first middleware like in my example above without clobbering the initial context. Interceptors introduce a new problem because they are sending through a context.

**Comment by dfawley** [comment]
> you'd also have to spin up a goroutine to watch for both cancelations

As mentioned previously, cancelation propagation wouldn't work properly if this was built in, anyway.  Sure you could signal your handlers to quit, but the listener would keep allowing new RPCs which your handlers would immediately fail.  This would not be a good state at all.

> Do you not find the change to http.Server compelling?

From digging a bit deeper, it seems the justification for doing it in `http.Server` is because they have the "default/global mux", whereas we have no such concept in grpc-go.  It's much harder to guarantee you're the first handler registered in that universe, and even if you can, you then need to use magic to transfer values from your `main` to the global handler function in order to inject them.  In grpc-go, it seems to me that if you have the power to inject a `grpc.BaseContext` server option, then you should _also_ have the power to inject an interceptor properly.

Another concern I have with this kind of option is that it presumes there's only one source of `baseContext`.  What if multiple producers wish to inject a context?  Now there's a composability problem.

**Comment by derekperkins** [comment]
> What if multiple producers wish to inject a context? Now there's a composability problem.

I assume that's the reasoning behind the stdlib using a function, so you can move composition into a function. `func(net.Listener) context.Context`

> it seems to me that if you have the power to inject a grpc.BaseContext server option, then you should also have the power to inject an interceptor properly.

I'm having a hard time reading you. Are you pretty firmly against the idea of a base context, and I should hack in that merge context business into our own code, or are you just vetting the idea and exploring the solution space? I'm a maintainer of the Vitess project, so I completely understand pushing back and not just accepting feature requests as always being a net-positive.

**Comment by dfawley** [comment]
> Are you pretty firmly against the idea of a base context, and I should hack in that merge context business into our own code, or are you just vetting the idea and exploring the solution space?  

I'm leaning against adding something like this, but intending to allow opportunity to be proven wrong on my reasoning.  So far, to me it looks like there is replacement functionality (an interceptor) that works well enough for all use cases.  Expanding the API just to make something more ergonomic for rare use cases doesn't seem to be worth it -- particularly when there is the opportunity to cause more problems than it solves.  Specifically, out of band cancelation of the returned context could potentially lead to bugs in our server implementation, which has never needed to worry about this before, and there may be mistaken assumptions by users about what cancellation means and how the server should be responding when that happens.

**Comment by todpunk** [comment]
I think I might go the opposite way and be explicit about what context means or doesn't mean in the grpc server by taking contexts out entirely. If each RPC call is supposed to be explicitly handled with different contexts, that's an API constraint with grpc handler. If we're using context in the same way as the http server, and we're not going to allow base context to be handed in, the answer should probably be not using contexts at all since this isn't the intended use case.

So bugs if we handle a base context because it's a new set of assumptions means we either have bad assumptions or we should be explicit about the bugs we're expecting because of merged/replaced contexts. The assumptions the community have about context usage are at play here.

I think we might just be using context wrong. Granted, full disclosure that my understanding of context is mostly in line with this article: http://p.agnihotry.com/post/understanding_the_context_package_in_golang/

My understanding could be off from context package intention and I could be communicating cargo culting. I'm more than happy to get more authoritative feedback on how I'm wrong so I align to more stdlib thinking.

I'm curious how one would implement a grpc _and_ other protocol server in the same process without a shared context (or managing multiple contexts like one would manage different processes, thus negating the point). Maybe that's an antipattern and I should just run two things with a shared lib in all cases.

**Comment by dfawley** [comment]
> If each RPC call is supposed to be explicitly handled with different contexts, that's an API constraint with grpc handler.

I don't understand this statement.  Each RPC call is obviously supposed to be handled using the context that is _passed to them as a parameter_, so apparently you mean "not a user-provided context".

> If we're using context in the same way as the http server, and we're not going to allow base context to be handed in, the answer should probably be not using contexts at all since this isn't the intended use case.

I don't think we are using context in the same way as the http server.  We don't have a concept of the "global mux".  Handlers are only registered on a server instance.  This seems to me like the only reason they eventually accepted the proposal, because before this use case was described, the feature request was rejected.

> My understanding could be off from context package intention and I could be communicating cargo culting. I'm more than happy to get more authoritative feedback on how I'm wrong so I align to more stdlib thinking.

I'm sure I'm not the authority on contexts.  I'm also sure grpc-go is not using contexts optimally in many instances, but unfortunately we're largely stuck with the API we have.

> I'm curious how one would implement a grpc and other protocol server in the same process without a shared context (or managing multiple contexts like one would manage different processes, thus negating the point). Maybe that's an antipattern and I should just run two things with a shared lib in all cases.

I am not sure if I understand the question.  If you mean "it's hard to pass around state using contexts", then that may be true, but I also feel like this is a bad programming model in the first place, as it encourages storing anything and everything you might need later in contexts.  If your server needs data, why not explicitly initialize it with the data it needs?  If it's the interceptors that need data, then they can be initialized when they are created.  Passing data through contexts is not intended to be common.  The guideline in the context package is "Use context Values only for request-scoped data that transits processes and APIs, not for passing optional parameters to functions".  It sounds like what you're trying to pass around is not really "request-scoped", but "global state", which does sound like an antipattern to me.

**Comment by derekperkins** [comment]
> I don't think we are using context in the same way as the http server. We don't have a concept of the "global mux". Handlers are only registered on a server instance. This seems to me like the only reason they eventually accepted the proposal, because before this use case was described, the feature request was rejected.

Unless you're seeing this in the referenced internal Google issue, I don't see that in the linked GitHub issues. I think the grpc server is using context in an almost identical way for an identical purpose as the stdlib http server.

Clearly we're at an impasse, and that's fine. I'd like to leave the issue open to see if anyone else is interested in this. I still believe the use case I described above (https://github.com/grpc/grpc-go/issues/5016#issuecomment-990410855) is valid, and to my interpretation of the stdlib conversation, is approximately the same use case that triggered that change. I don't love the `mergeContext` hack you proposed, but at least it is a workaround.

For reference, someone linked to a package that does context merging in a similar fashion to the linked playground, including respecting context cancelation. https://pkg.go.dev/lab.nexedi.com/kirr/go123/xcontext#Merge

**Comment by todpunk** [comment]
> Passing data through contexts is not intended to be common. The guideline in the context package is "Use context Values only for request-scoped data that transits processes and APIs, not for passing optional parameters to functions". It sounds like what you're trying to pass around is not really "request-scoped", but "global state", which does sound like an antipattern to me.

Not global state data, but context cancellations and maybe other events. Like if I wrote a game server that also had a grpc API for some out-of-band things like stats, shutdowns of the server can't be handled in a stream unless I do merging carefully, where derived contexts are built for that sort of thing.

That's not a need I have, I'm just thinking through scenarios however contrived they may be. Cancellation and observability items were my actual use case that brought me here. I just got thinking down other roads from the discussion.

**Comment by dfawley** [comment]
> Unless you're seeing this in the referenced internal Google issue, I don't see that in the linked GitHub issues.

I can't remember exactly now, but I believe I made this conclusion because of https://github.com/golang/go/issues/30694#issuecomment-473228830:

"For our use case, we expressly need to be the first to attach data to the request-scoped contexts —thanks to massive legacy use — as we cannot reliably guarantee to be the first callee by handlers enrolled with the http package (think handler chaining)."

> I still believe the use case I described above (#5016 (comment)) is valid

The context cancelation at process shutdown part is what is concerning.  What does it mean to inject a context into the request flow that is canceled independently of the server, or potentially already canceled?  This means that your handlers will immediately exit RPCs with `Canceled` status, but your server will keep accepting them.  This seems like a pretty bad state to be in.  IMO if we were to plumb in a context somehow, it should be done at a level that would shut down the whole server (or listener), not just the handlers.

> Like if I wrote a game server that also had a grpc API for some out-of-band things like stats, shutdowns of the server can't be handled in a stream unless I do merging carefully, where derived contexts are built for that sort of thing.

As mentioned several times in this issue (and once more in this comment), cancelation isn't going to work without an API change.  The "best" way I can see would be to have a `ServeContext(context.Context, net.Listener)` method on `grpc.Server`.  It would need to spin up a goroutine to monitor for context cancelation.  That could close the listener and cancel the handlers pretty easily.  Some extra work would be needed to close all the connections that came from that listener.  That step brings up a race between terminating the handlers as gracefully as possible and closing the connections.  (This is why there are separate `GracefulStop` and `Stop` methods.)

Honestly, I think cancelation is too hard / impossible to get "right".  If there's no obvious way to do it correctly, then I'd rather err on the side of "don't do it at all".  All the tools are already present for users to do what they need, whatever that may be.  It's easy enough to monitor the context for cancelation _outside_ the `grpc.Server` and initiate whatever shutdown process is desired at that time (hard `Stop` immediately or do `GracefulStop` for 10 seconds before doing a hard `Stop`, e.g.).  It's also possible to inject a "base" context's values into each RPC using an interceptor, as described above.  So considering all the functionality being request is already possible, and the exactly semantics around how cancelation should work are unclear, I don't think this is something we should pursue.

**Comment by derekperkins** [comment]
If I can turn the question around on the context clobbering. Why shouldn't I just replace the context in my first interceptor if it isn't used for cancelation? What value am I getting from propagating the `context.Background` that the server is sending through - is it just for `metadata.FromIncomingContext`?

**Comment by dfawley** [comment]
> Why shouldn't I just replace the context in my first interceptor if it isn't used for cancelation?

The one passed to the handler _is_ canceled when the RPC deadline expires or if the client initiates cancelation or if the connection is lost.

Also it has the incoming metadata, as you mentioned, and other information about the peer (https://pkg.go.dev/google.golang.org/grpc@v1.43.0/peer#FromContext), and anything added by a stats handler (https://pkg.go.dev/google.golang.org/grpc/stats#Handler - TagConn).

**Comment by dfawley** [comment]
I'm going to close this as I don't think it makes sense for us to do.  To properly deal with cancelation of a base context would be nontrivial and it's unclear to me how it would work without thinking through all the possibilities.  The difference between this feature request and what the HTTP server has is that the context here would not be scoped per-request, as it is in the HTTP server, but per-connection/transport or per-server.  In addition, a standard interceptor can provide the functionality requested, even if it requires a little work to create a wrapper context that merges the values from the two.
