### ISSUE TITLE
Allow GrpcServer.RegisterService to specify ServerOption's

### ISSUE THREAD

**Issue by steeling** [grpc/grpc-go#5113]
I often serve multiple API's on the same grpc port, however unless I write an inverse multiplexer I believe I have no option but to use separate ports if I want to set different ServerOption's for different API's.

This may be in the form of rate limiting (WriteBufferSize), or different Interceptors for different API's.

The solution could be to modify the interface of `ServiceRegistrar` from

```go
RegisterService(desc *ServiceDesc, impl interface{})
```

to 

```go
RegisterService(desc *ServiceDesc, impl interface{}, ...ServerOption)
```

Variadic args has the added benefit of not breaking the existing API.

The simplest alternative in the meantime is multiple ports, but it'd be nice to be able to use this, particularly since it makes management for any downstream users who have to run my binaries much simpler.

Cheers!

**Comment by easwars** [comment]
A [ServerOption](https://pkg.go.dev/google.golang.org/grpc#ServerOption) configures options for *a* gRPC-server as a whole, which is why they are passed at [server creation time](https://pkg.go.dev/google.golang.org/grpc#NewServer). If options are to apply on a per-service level (which is what you are suggesting with your proposed API), I think that would require more intrusive changes than just the registration API change.
