### ISSUE TITLE
 Can  add a SetContext method in serverStream interface？

### ISSUE THREAD

**Issue by haiyux** [grpc/grpc-go#5124]
Please see the FAQ in our main README.md before submitting your issue.

### Additional Context

https://github.com/grpc/grpc-go/blob/9353ae3bb432cf1075bf9329ab264421b8e01394/stream.go#L1367

**Comment by menghanl** [comment]
Can you explain why you want the method?

If you are proposing to add a `SetContext` to the interface, it doesn't work:
1. The server stream context is derived from the transport, and has important information. `SetContext` to replace the context will not work.
1. We cannot change the `ServerStream` interface because that's an API change.

If you want to add things to the context, the recommended way is to use interceptors.
https://pkg.go.dev/google.golang.org/grpc#WithStreamInterceptor
See the example here: https://github.com/grpc/grpc-go/blob/master/examples/features/interceptor/server/main.go#L126

**Comment by haiyux** [comment]
I want  use context.WithValue at server Interceptor,  and use value in method.Can this be done？

**Comment by haiyux** [comment]
I solved it. Thank you very much @menghanl
