### ISSUE TITLE
segmentation violation in xdsclient controller package

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5142]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf659e4]

goroutine 1619 [running]:
google.golang.org/grpc/xds/internal/xdsclient/controller.(*Controller).run(0xc000648360, {0x1318518, 0xc00087a240})
	/home/runner/work/grpc-go/grpc-go/xds/internal/xdsclient/controller/transport.go:84 +0x304
created by google.golang.org/grpc/xds/internal/xdsclient/controller.New
	/home/runner/work/grpc-go/grpc-go/xds/internal/xdsclient/controller/controller.go:163 +0xc9e
FAIL	google.golang.org/grpc/xds/internal/xdsclient/controller	2.695s
```

**Comment by dfawley** [comment]
https://github.com/grpc/grpc-go/blob/aad573d86b2d03258984e4bee507307e1671cfc0/xds/internal/xdsclient/controller/transport.go#L84

**Comment by dfawley** [comment]
These tests seem to be passing a `nil` `UpdateHandler` but the code will unconditionally call methods on it.

**Comment by menghanl** [comment]
- `UpdateHandler` is a required parameter in `New()`, so nil check shouldn't be necessary
- Some tests pass `nil` to `New()`, because they are "unit" tests, and no updates are sent, so the update handler isn't expected to be called
  - **this is what should be fixed**. All tests should use a non-nil update handler
- but, this nil panic happened in error cases (failing to create the ADS stream)
- this is flaky, and only happens in unstable (or slow?) environments
