### ISSUE TITLE
Help!!!  The context in gRPC client and server may timeout in the different time sometimes

### ISSUE THREAD

**Issue by git-qfzhang** [grpc/grpc-go#5206]
I send request including context with timeout  from gRPC client to server. Also, I listen the context in both server and client. 

When the context deadline exceeds, the server would response "server action is canceled for context deadline exceeds " error to client, which should not be received by client for the client would break the connection with error: "context deadline exceeds".

Most of the time things happen as I expected. However, I found that the "server action is canceled for context deadline exceeds" error was received by client yesterday, which made my system behave unexpectedly.

I suspect that the context in gRPC client and server may timeout in the different time sometimes. Am I right?

**Comment by menghanl** [comment]
There _could_ be races like you described. But I expect it to be **rare** for the client to still receive the server status. Though that also depends on other aspects, including goroutine scheduling.

From what you said, I assume you want to reliably detect when an RPC is canceled due to timeout. The recommend way is to check the RPC status code: https://pkg.go.dev/google.golang.org/grpc/status#Code

No matter which error is returned by the RPC, they should both have code [`DeadlineExceeded`](https://pkg.go.dev/google.golang.org/grpc/codes#Code).
- client side context error `context.DeadlineExceeded` is automatically converted to a status with code `DeadlineExceeded`.
- server side, if you wrap the error to prepend "server action is canceled for", make sure to use [`status.Errorf`](https://pkg.go.dev/google.golang.org/grpc/status#Errorf), not `fmt.Errorf`

**Comment by git-qfzhang** [comment]
> 

Unfortunately，the error code returned by the gRPC server is not `DeadlineExceeded` for my system would return `ContextCanceled` error in the situation. Also, the gRPC client received the error even if it is expected to be rare for the client to still receive the server status.

I plan to make gRPC server in my system return `DeadlineExceeded` error when the context deadline exceeds. 

Thnx for your suggestions!

**Comment by git-qfzhang** [comment]
> There _could_ be races like you described. But I expect it to be **rare** for the client to still receive the server status. Though that also depends on other aspects, including goroutine scheduling.
> 
> From what you said, I assume you want to reliably detect when an RPC is canceled due to timeout. The recommend way is to check the RPC status code: https://pkg.go.dev/google.golang.org/grpc/status#Code
> 
> No matter which error is returned by the RPC, they should both have code [`DeadlineExceeded`](https://pkg.go.dev/google.golang.org/grpc/codes#Code).
> 
> * client side context error `context.DeadlineExceeded` is automatically converted to a status with code `DeadlineExceeded`.
> * server side, if you wrap the error to prepend "server action is canceled for", make sure to use [`status.Errorf`](https://pkg.go.dev/google.golang.org/grpc/status#Errorf), not `fmt.Errorf`

I wonder that the possible reason for the context race between gRPC client and server, which confused me these days. Could you give me some thoughts on the scenes? Have you ever encountered the situation?
I found that gRPC client sends the context timeout through http2 request frame instead of metadata. Were there any concerns about putting the timeout in the metadata?

**Comment by menghanl** [comment]
Yes, timeout is sent to the server, so the service handler will have the same deadline as the client.

If the deadline actually happens, I would expect the client to see it before the server.
In Go, it is checked by reading from `ctx.Done()`.

But the problem is that, if `ctx.Done()` is not checked at the right time, we might miss that the context has already timed out.
E.g. if `ctx` is checked right before timeout, then the code moves on to read from TCP. At the same time, server side sees the timeout and sends the status. Then the client will see the timeout error from the server, but not the client.
Or, a more common error is in a `select { case<-ctx: ...; case<-messages: ... }`, where one case is `ctx.Done()`, and the other is the message received from the server (if both channels have elements, there's a 50/50 chance that the `ctx.Done()` is not read from).

This is something we should avoid as much as possible, and can be considered a bug if it ever happens. There was efforts to eliminate them (so client side timeout is always returned), but there could be some code path that was missed.
This is usually hard to reproduce, because the race window is so small. If you can make a test to reproduce the error, we can take a look if there's a real bug in the client code.

**Comment by git-qfzhang** [comment]
> 

Thanks for sharing the information with me.
