### ISSUE TITLE
Add documentation/examples on client side best practices

### ISSUE THREAD

**Issue by ppg** [grpc/grpc-go#526]
I think I understand the server-side best practices, mainly since grpc is the request multiplexer, so I'm just implementing the api endpoints, cognizent that there are multiple calls in flight at once potentially. However, all the client-side examples I've found thus far are in the form of a very simple CLI-style application where it starts, dials the server, makes some calls, then exits. I'm looking for some examples and/or documentation on the best practices when the client itself is more complex, namely when its a request oriented service like an API server and will be making multiple requests to the backend gRPC server. Some of the specific questions I'm curious about:

1. Are `ClientConn` objects mean to be long lived? I.e. should I dial my backend gRPC servers at startup and then share that connection with all incoming requests? I think so, to avoid the overhead of dialing each request, but it wasn't clear to me (contrary to say DB drivers where they explicitly say their connection object is long lived and should be shared).
1. What would be the effect/preference of doing client side load balancing via `WithDialer` vs. `WithPicker`, especially if I don't have dynamic discovery yet and are doing something like setting the potential upstream gRPC server addrs on startup, so that its known and they don't change?

Thanks,
\Peter

PS If there's a better place to ask this question I can head there, although I do think this info should be in the examples or documentation folder.

**Comment by iamqizhao** [comment]
We are working on better document but providing "realistic" but not too serious examples is not a easy job. :) Probably you can check some projects which have been or are adopting grpc-go to get some better idea (e.g. cloud bigtable, etcd). grpc-io@googlegroups.com is probably the best place to ask this kind of questions.

1. ClientConn can be long lived and many rpcs can be multiplexed on that. It is still case-by-case though. For example, some applications (e.g., some android apps) may want to tear down the ClientConn when it knows it won't send out any rpcs for a while. I would say the application is the best decision maker here.
2. In general, WithDialer is used to connect the server with some special custom code (e.g., unix domain socket, Google app engine). It is not designed for load balancing. WithPicker is designed for load balancing and naming. I saw some users use WithDialer to implement some simple load balance (mainly because Picker was not available at that moment).  I am not gonna stop them. But I would suggest using Picker.
