### ISSUE TITLE
Version v1.46.0 is incorrectly tagged

### ISSUE THREAD

**Issue by subtlepseudonym** [grpc/grpc-go#5322]
### What version of gRPC are you using?
v1.46.0

### What version of Go are you using (`go version`)?
v1.18

### What operating system (Linux, Windows, …) and version?
darwin

### What did you do?
Upgraded from v1.45.0 to v1.46.0

### What did you expect to see?
No breaking changes

### What did you see instead?
Version v1.46.0 [removes DialOption.WithBalancerName](https://github.com/grpc/grpc-go/releases/tag/v1.46.0), which is a breaking change. This version should either be tagged v2.0.0 or the removed method should be reinstated and the project tagged to v1.46.1

**Comment by dfawley** [comment]
Please refer to our published versioning guide:

https://github.com/grpc/grpc-go/blob/master/Documentation/versioning.md

> * MINOR releases will not break backward compatibility, except in the following circumstances:
>   * An API was marked as EXPERIMENTAL upon its introduction.

This API was introduced as EXPERIMENTAL and has been labeled as deprecated for 3+ years.

**Comment by dfawley** [comment]
> I would suggest that, when an experimental API is deprecated, we maintain the documentation stating that it is experimental. I had to go back to the docs for [v1.22.0](https://pkg.go.dev/google.golang.org/grpc@v1.22.0#WithBalancerName) to find the experimental tag (which was removed in [v1.23.0](https://pkg.go.dev/google.golang.org/grpc@v1.23.0#WithBalancerName)).

We do mostly maintain a distinction between "deprecated because we don't recommend using this" and "deprecated and may be removed".  We didn't always do this, so you may find places where it's missing, but you can see examples here:

https://github.com/grpc/grpc-go/blob/e8d06c51a523ba75f052cfaa56a1b8e0583ac589/backoff.go#L40

https://github.com/grpc/grpc-go/blob/e8d06c51a523ba75f052cfaa56a1b8e0583ac589/dialoptions.go#L198-L201

Generally I think we are better about labeling the former case, so if something says "deprecated" but does not indicate it will be supported throughout 1.x, you should assume it was experimental originally and could be removed in a future minor version. 
Thanks for the feedback, though.  We will try to do a better job going forward of labeling as in in the latter case.
