### ISSUE TITLE
Allow client-side parsing of the `grpc-status-details-bin`

### ISSUE THREAD

**Issue by koiuo** [grpc/grpc-go#5485]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?

Integrating go service into an existing infrastructure with proto services written in C++, Java, Python, where the format of the grpc-status-details-bin is not enforced.

This would be consistent with other clients, that only suggest the expected format, but do not enforce it.

### Proposed Solution

Right now we can't even detect, whether `grpc-status-details-bin` can be parsed correctly.
The simplest solution would be a flag to disable the extended errors support entirely

```
func (t *http2Client) operateHeaders(frame *http2.MetaHeadersFrame) {
  ...
case "grpc-status-details-bin":
  if grpcStatusDetailsEnabled {
    statusGen, err = decodeGRPCStatusDetails(hf.Value)
    if err != nil {
      headerError = fmt.Sprintf("transport: malformed grpc-status-details-bin: %v", err)
    }
  } else {
    mdata[hf.Name] = append(mdata[hf.Name], hf.Value)
  }
...
```

**Comment by edio** [comment]
Doug, thanks a lot for your quick response.

> Why not use a custom trailer key instead?

It's an existing ecosystem of thousands of apps developed in other languages which already use `grpc-status-details-bin` to pass  custom proprietary entity.

Effectively we can't use Go in this ecosystem due to how grpc-go handles `grpc-status-details-bin` (well, we maintain our own fork, which highly unsustainable).

> Since this is a reserved header, I don't believe we should be passing it to the application.

Can you suggest any workarounds for this?

It would be very helpful to get access to reserved metadata on some level.
One option I can think of is to expose such metadata in the interceptor. And it can be cleaned up somewhere later in the processing chain.
Another is exposing a flag (grpc.CallOption or even env var) to pass reserved metadata to the caller (for those clients who know, what they are doing).

---

Another issue I'd like to hightlight about the current implementation, is that it can not identify unmarshalling issues. It unmarshalls our proprietary instance into `google.rpc.Status` without errors, but later, since the data does not make sense, entire request fails with `Unexpected EOF` (not even an invalid header format error). I can file a separate issue with a reproducing scenario to improve invalid headers handling if you think it's something worth investigating/fixing.

**Comment by dfawley** [comment]
I brought this issue up with the other language leads.  We didn't decide on anything concrete yet, but we will discuss it further later this week and come up with a plan that can work for all the languages.  I'm hopeful we'll be able to make things work more gracefully with the implementations that allowed arbitrary binary data without breaking existing users.

> Another issue I'd like to hightlight about the current implementation, is that it can not identify unmarshalling issues. It unmarshalls our proprietary instance into google.rpc.Status without errors, but later, since the data does not make sense, entire request fails with Unexpected EOF (not even an invalid header format error).

I'm definitely curious about this, as it's surprising to me that it would get past the unmarshalling step but eventually fail the RPC due to the status.

**Comment by dfawley** [comment]
Sorry for the late response here.  We would like to provide a way for the user to access the raw `grpc-status-details-bin` via a new field in the `status.Status`, and not error if it's of the "wrong" type, but our team doesn't have the time to take on this task right now.  In the short to medium term, if someone would like to submit a mini-design and then do the work here, we can guide & review.  Thanks!

**Comment by CemGurhan** [comment]
I'd like to give this a go! @dfawley I was wondering, when you say a new field in the `status.Status` type, do you mean the type defined  in internal [here](https://github.com/grpc/grpc-go/blob/1e0d82e9f00e430f9d6c903b814d1aea0a6566e8/internal/status/status.go#L42-L44), or do you mean the proto definition, which I'm assuming is defined [here](https://github.com/grpc/grpc/blob/5c9e4050c1e8c66b1b8b4e93d48b8e23ff1ea818/src/proto/grpc/status/status.proto#L80-L92)?

**Comment by dfawley** [comment]
So sorry I missed your message @CemGurhan ..  I'm going to try to take this on this week to clean up some other discrepancies I found between languages in the general handling of statuses.

**Comment by CemGurhan** [comment]
No problem at all. If you need any help, feel free to let me know!
