### ISSUE TITLE
`(*Conn).transportMonitor` shutdown behaviour is inefficient

### ISSUE THREAD

**Issue by tamird** [grpc/grpc-go#559]
There are two problems with this behaviour:
- It tries to reconnect after the stream is closed with EOF. This should not happen, since EOF is a natural consequence of the remote hanging up. In my logs, I see something like:
```
transport: http2Client.notifyError got notified that the client transport was broken EOF.
```
but the `transportMonitor` goroutine is still running, and our leak checker fails.
- `(*Conn).Close` is asynchronous, so even if I try to force-close these connections during shutdown, they still end up leaking and failing my tests.

cc @bradfitz @bdarnell @tschottdorf

**Comment by iamqizhao** [comment]
To be clear, a stream being closed with EOF is nothing to do with EOF in the log you posted. The log you posted is because the server is leaving.

In grpc, we always assume the client should always reconnect and the server should never actively shutdown a connection unless the entire server is down. The client should still reconnect when it gets EOF because it probably means the server is migrated to another machine.

Yes, there is some chance your checker has to wait longer to let grpc lib finish all the pending goroutine because I used some time.Sleep for some exponential back-off reconnecting logic. I plan to improve it actually.

**Comment by tamird** [comment]
Was this issue addressed somewhere?

**Comment by iamqizhao** [comment]
What is the issue? you misunderstood the "EOF" and I clarified the intended behavior.

**Comment by tamird** [comment]
> `(*Conn).Close` is asynchronous, so even if I try to force-close these connections during shutdown, they still end up leaking and failing my tests.

You replied to this with "I plan to improve it". Has the improvement been implemented?

**Comment by iamqizhao** [comment]
not yet. But it is definitely NOT about "`(*Conn).transportMonitor` shutdown behaviour is inefficient" as in the title of this issue.  It could be a new issue with something like "remove sleep behavior in reconnection".

**Comment by iamqizhao** [comment]
Move the remaining improvement to #579

**Comment by iamqizhao** [comment]
BTW, in your test, you can close your grpc.ClientConn before tearing down the server to avoid the problem.
