### ISSUE TITLE
Provide an internal-only API to report connectivity state changes on the ClientConn

### ISSUE THREAD

**Issue by easwars** [grpc/grpc-go#5818]
Currently we don't have an API to get connectivity state changes on the `ClientConn` in a lossless fashion.

Our current [state change API](https://pkg.go.dev/google.golang.org/grpc#ClientConn.WaitForStateChange) is lossy because state changes can be lost between the former returning and the caller invoking [GetState](https://pkg.go.dev/google.golang.org/grpc#ClientConn.GetState).

Other languages provide this API, and we should consider adding this sooner rather than later.

Currently, the RLS LB policy needs a way to monitor the connectivity state of the control channel. The xDS client needs a way to monitor the connectivity state of the channel to the management server.

**Comment by markdroth** [comment]
Note that no gRPC language provides a public API to get lossless connectivity state updates, and that is by design: we don't want users expecting to see every individual update, because they should not need to care about the state machinery, only the current state.  We should not add such a public API in grpc-go.

Some languages do have *internal* APIs that provide lossless connectivity state updates.  In particular, for example, I think it's quite important that LB policies get lossless updates from subchannels.  And it's fine to use such internal APIs at the channel level in cases where we are creating the channel internally (e.g., the xDS channel described in #3823).  But we should not make such APIs public for applications to use.

**Comment by easwars** [comment]
Thanks for the comment, Mark !!

We will ensure that the added API is an internal-only API.
