### ISSUE TITLE
Flaky test: Test/ConfigUpdate_ControlChannel

### ISSUE THREAD

**Issue by zasweq** [grpc/grpc-go#5845]
https://github.com/grpc/grpc-go/actions/runs/3626900442/jobs/6116288827

        grpctest.go:39: Leaked goroutine: goroutine 1395 [chan receive]:
            google.golang.org/grpc/balancer/rls/internal/test/e2e.(*bal).run(0x400020c3c0?)
            	/home/runner/work/grpc-go/grpc-go/balancer/rls/internal/test/e2e/rls_child_policy.go:130 +0x28
            created by google.golang.org/grpc/balancer/rls/internal/test/e2e.bb.Build
            	/home/runner/work/grpc-go/grpc-go/balancer/rls/internal/test/e2e/rls_child_policy.go:77 +0x1ac
        grpctest.go:60: Leak check disabled for future tests
    tlogger.go:116: INFO picker.go:283 [rls] [rls-picker 0x4000088ea0] Received RLS response for key {path:/grpc.testing.TestService/EmptyCall keys:} with targets [], headerData "", err: rpc error: code = Unavailable desc = error reading from server: read tcp 127.0.0.1:57132->127.0.0.1:41199: use of closed network connection  (t=+268.197016ms)

**Comment by easwars** [comment]
I ran this on google3:
- 0 flakes in 10k runs
- 6 flakes in [100k runs](http://sponge2/594e5b01-0263-4d16-b80a-44d25c03d7a1)

**Comment by easwars** [comment]
Found a race in the `balancergroup` which can lead to a child policy being leaked. 

This is the sequence of events which:
- `child1` is added to the `balancergroup`
- after some time, `child1` is being removed
  - but before it can actually do the removal, it loses the cpu
  - we just see the log statement here: https://github.com/grpc/grpc-go/blob/f54bba9af73267dcc87fcc4841dfa1e0de39d332/internal/balancergroup/balancergroup.go#L391
- at the same time, the `balancergroup` is closed
  - from `Close()`, we attempt to clear the `timeoutCache`, and this is done without the `outgoingMu`. See: https://github.com/grpc/grpc-go/blob/f54bba9af73267dcc87fcc4841dfa1e0de39d332/internal/balancergroup/balancergroup.go#L546
  - since `child1` has not yet been added to the `timeoutCache`, the `Clear()` does nothing
  - the fact that we call `Clear()` without `outgoingMu` is not the source of the upcoming problem. We **need** to call `Clear()` without the lock, because the evicton callback attempts to grab the lock
- before `balancergroup.Close()` can go ahead and stop the existing balancers stored in `bg.idToBalancerConfig`, we lose the cpu here
- we are back in `balancergroup.Remove()` and we end up adding `child1` to the timeout cache and removing it from `bg.idToBalancerConfig`
- we are back in `balancergroup.Close()`, and we try to iterate though `bg.idToBalancerConfig`, but we find nothing. But we end up setting `bg.outgoingStarted` to `false`
- timeoutCache callback is invoked, but it sees `bg.outgoingStarted` is false and therefore does not close the child policy. See: https://github.com/grpc/grpc-go/blob/master/internal/balancergroup/balancergroup.go#L395-L405

Hence `child1` is leaked.
