### ISSUE TITLE
Oauth2/TLS with KNative Service Mesh

### ISSUE THREAD

**Issue by erictg** [grpc/grpc-go#5934]
Are there any recommendations for how to run tls/oauth2 in a knative service mesh scenario? The issue I am running into is that the service mesh itself wants to handle tls, but in order to use oauth2 I need to mount the certs in the go code. When I tried to set the mesh to insecure on my grpc service and handle the certs manually, I got an error from my grpc client saying `tls: first record does not look like a TLS handshake.` 

My guess is that is the proxy in the service mesh sent something back before the request even made it to my grpc server service.

I want to be able to use oauth2 in this environment, but I am stuck as to how to accomplish this. TIA for any advice

**Comment by dfawley** [comment]
Sorry for the late reply.  Have you made any progress on this one?

It's definitely likely that in this environment grpc client/server actually do an HTTP/2 handshake with the mesh's proxies and not the other endpoint directly.  Which means if you set it to insecure, the handshakes will be done in plaintext.  I'm sorry to say I don't have any experience with this, however.  If there is some way to configure it to treat the traffic as raw TCP instead of HTTP, that would potentially be able to fix it.  Otherwise I'm not sure what other options are available, sorry!
