### ISSUE TITLE
Transform IncomingContext to OutgoingContext

### ISSUE THREAD

**Issue by beatrausch** [grpc/grpc-go#6010]
Hi,

I have a question regarding the forwarding of metadata in consecutive GRPC calls. In my use case, my GRPC service has to make another GRPC call to another service for the processing of an incoming call. Using the context, that the service received in the incoming GRPC call, to make an outgoing GRPC call, results in the loss of all metadata. 

The only solution, I found so far, is to extract the metadata from the incoming call and make another outgoing context using the metadata package from grpc:

```
md, ok := metadata.FromIncomingContext(ctx)
if !ok {
   // ERROR
   return
}
ctx = metadata.NewOutgoingContext(ctx, md)
```

Is there a better way to forward metadata in consecutive GRPC calls?

**Comment by dfawley** [comment]
For more info, see https://github.com/grpc/proposal/blob/master/L7-go-metadata-api.md

It's a security concern if all incoming metadata is forwarded to outgoing calls automatically, since the incoming metadata might include security keys or other private data.

This is the right way to do it, though you probably want to only forward specific metadata keys.
