### ISSUE TITLE
Connection timeouts and reconnect logic

### ISSUE THREAD

**Issue by rlubke** [grpc/grpc-go#6094]
Hey folks, I've implemented a piece of code in GRPC JS and Python that I'm having trouble getting working in Go.  I'm still coming up to speed on Go, so my apologies if I'm missing something obvious.

Firstly, I can't get connection timeouts working.  I've used the `WithConnectParams` `DialOption` with a 5-second timeout in conjunction with `WithBlock` and my test client (with no server running yet) just hangs on the dial call - no timeout appears to be triggered 

For example:
```
client, err := grpc.DialContext(ctx,
		"localhost:1408",
		grpc.WithTransportCredentials(insecure.NewCredentials())
		grpc.WithBlock(),
		grpc.WithConnectParams(grpc.ConnectParams{
			Backoff:           backoff.Config{},
			MinConnectTimeout: 5 * time.Second,
		}))
```

If I instead use a Context timeout (`context.WithTimeout(context.Background(), 5*time.Second)`) it works okay, but then what is the point of `WithConnectParams`?

Secondly, I haven't figured out what magic is necessary to enable re-connection logic.  For example, in JS/Python, when the connection state goes to IDLE or TRANSIENT_FAILURE due to a disconnect, I see (by watching channel state changes during the outage) the runtime attempting reconnects automatically without having to initiate the reconnection myself.  Searching on this topic has shown bits and pieces where this should be supported in the Go version of the library, so again, I could be missing something.

Thanks for your attention.

**Comment by dfawley** [comment]
A gRPC `ClientConn` is _not_ a single connection, and `Dial` does not _actually_ just "dial".  A `ClientConn` is a managed pool of connections that will reconnect as needed.  Those internal connections respect the `WithConnectParams` settings, but it is completely detached from the `Dial` function call.  There's a WIP PR #6034 that attempts to explain some of this better.

We don't actually recommend using `WithBlock` and `DialContext` or `WithTimeout`.  It's a bit of an anti-pattern, because connections can fail and reconnect dynamically, and your application should be able to deal with these failures as well.  There isn't anything particularly special about the first connection attempt in that regard, but these options all focus on that initial connection.

> Secondly, I haven't figured out what magic is necessary to enable re-connection logic

This will happen if: 1. you are using the round-robin LB policy, or 2. when you attempt a new RPC.  If you aren't starting new RPCs, and pick first (the default LB policy) is used, and a connection is lost, gRPC (any language) should not attempt to reconnect.  Upon issuing the first RPC, the `ClientConn`/channel will transition to `CONNECTING` (after it leaves `TRANSIENT_FAILURE` which requires the backoff to expire) and the RPC will be issued assuming it changes to `READY` as we'd expect.

Let us know if you have any further questions.

**Comment by maha-hajja** [comment]
@dfawley so if `waitForReadyState` is called, it will keep blocking and the connection will not be established unless an RPC is being called somewhere else? meaning the connection state will not change if we call `waitForReadyState` even if default backoff is used?
