### ISSUE TITLE
connparams seems not effevtive

### ISSUE THREAD

**Issue by fengyeall111** [grpc/grpc-go#6176]
version: 1.54.0
os: win11
code:
```
var DefaultStreamDialOptions = []grpc.DialOption{
	grpc.WithTransportCredentials(insecure.NewCredentials()),
	grpc.WithConnectParams(
		grpc.ConnectParams{
			Backoff: backoff.Config{ 
				BaseDelay:  time.Millisecond * 20,
				Multiplier: 4,
				Jitter:     0.1,
				MaxDelay:   time.Second * 10, 
			},
			MinConnectTimeout: time.Second * 5, 
		}),
}
conn, err := grpc.DialContext(ctx, addr, DefaultStreamDialOptions...) 
	if err != nil {
		return err
	}
start := time.Now().Unix()
stream, err := w.conn.NewStream(ctx, streamDesc,streamName, grpc.WaitForReady(false))
end := time.Now().Unix()
fmt.println("late:", end - start)
```
If  err is unavalibale,  end - start == 2,and I have traced code:
```
func (a *csAttempt) shouldRetry(err error) (bool, error) {
...
rp := cs.methodConfig.RetryPolicy
	if rp == nil || !rp.RetryableStatusCodes[code] {
		return false, err
	}
...
}
```
why must methodConfig?I think  having a globalConfig maxAttempts or maxConnectTimeout  is fine.
how about offer a calloption in NewStream, not only in method config

**Comment by dfawley** [comment]
The connect parameters are dealing with connection establishment, and you seem to be measuring the amount of time it takes the first RPC to fail if the server is down?  I don't really understand what you're trying to show.

[Retries](https://github.com/grpc/proposal/blob/master/A6-client-retries.md) are configured by the service config, which is by design to give control to the service owner.  You can set a [default service config](https://pkg.go.dev/google.golang.org/grpc#WithDefaultServiceConfig) client-side if you need one.  If you want another way to do retries outside of service config, you'll want to file a multi-language issue in github.com/grpc/grpc.
