### ISSUE TITLE
missing go.sum entry for module providing package

### ISSUE THREAD

**Issue by anassrakibi** [grpc/grpc-go#6324]
I have a dependency to the grpc package since over a year and suddenly I started to get this error

```
../pkg/mod/google.golang.org/grpc@v1.54.0/status/status.go:35:2: missing go.sum entry for module providing package google.golang.org/genproto/googleapis/rpc/status (imported by google.golang.org/grpc/status); to add:
  go get google.golang.org/grpc/status@v1.54.0
```

I have run `go mod tidy` and also `go get google.golang.org/grpc/status@v1.54.0` but both of them didn't fix the issue. 

I have even upgraded to `1.55.0` and downgraded to `1.53.0` but the issue still occurs.

is anyone facing the same issue?

**Comment by dfawley** [comment]
That's unexpected because `grpc/status` was never even its own package.

What are you trying to do?  Compile your own binary that imports gRPC?

If so, you can try some of the following (one at a time):
1. Run `go mod tidy` in the root directory of your module and then `go build <./path/to/binary>` from that same directory.
2. Delete your `go.mod` in that directory and recreate it from scratch (`go mod init` + `go mod tidy`) and then try to re-build.
3. Delete your whole `$GOPATH/pkg` directory (or move it elsewhere as a backup) and try again.

**Comment by anassrakibi** [comment]
None of the solutions have worked for me. 
When I tried the 2nd solution I get this error
`go: updates to go.mod needed; to update it: go mod tidy`
and after running it I still get the same error

**Comment by dfawley** [comment]
I'm not sure, then.  I've never seen anything like this.  Is there a `verbose` mode for `go` that outputs debugging info to explain why it's happening? Can you produce a minimal reproduction case for us?

**Comment by anassrakibi** [comment]
It's fixed.
