### ISSUE TITLE
add LocalAddr to peer.Peer client side

### ISSUE THREAD

**Issue by rittneje** [grpc/grpc-go#6577]
### Use case(s) - what problem will this feature solve?

We want to be able to log the local address in addition to the remote address from our server-side interceptors to aid in debugging.

### Proposed Solution

Add `LocalAddr net.Addr` to `peer.Peer`.

### Alternatives Considered

This information could also be made available via some other context attribute. It doesn't really matter as long as there is a way to get it.

### Additional Context

This was already added to the Java implementation several years ago. https://github.com/grpc/grpc-java/pull/4906

**Comment by arvindbr8** [comment]
Assigning this to @prestonvasquez

**Comment by CarlosRDomin** [comment]
I've been playing with master now that #6716 has been merged and it's great to have access to the local address from server code, kudos @zasweq! However, there's also useful applications of retrieving the local port a client is using (e.g. to correlate it with prometheus metrics that we expose using the client address as a label). Not sure if this was intentional, but I noticed that #6702 exposed the `LocalAddr` in `http2Client.getPeer` (see [here](https://github.com/grpc/grpc-go/pull/6702/files#diff-5334018444bcb34d15bcb3c8a3050cdf9c8a40fe41305c3a602ea4bfeb0cd178R498)), while #6716 only updates `http2_server.go`.

Would it be possible to cherry-pick that one line from #6702? I modified the code locally and can confirm that's all that's needed for client code to retrieve local port through `peer.FromContext(stream.Context())`. I'd even be happy to contribute with a tiny MR if needed.

Thanks!

**Comment by zasweq** [comment]
Oh sure, we cna keep this open and try to add that. I will update the title accordingly.

**Comment by CarlosRDomin** [comment]
Awesome thanks @zasweq! Will you take care of the changes or want me to help in any way?

**Comment by dfawley** [comment]
@CarlosRDomin - if you don't mind sending a PR, that would be great, thanks!

**Comment by CarlosRDomin** [comment]
Apologies for the delay, here it is @dfawley @zasweq #6779  
It's my first PR to this repo so please let me know if I need to follow any special instructions, naming conventions, etc
