### ISSUE TITLE
resolver.Address Type deprecated

### ISSUE THREAD

**Issue by ying-jeanne** [grpc/grpc-go#6644]
Hello,

First of all, I'd like to express my appreciation for your work on maintaining this library.

I'm currently in the process of upgrading one of our projects to gRPC version 1.58.0. In our previous version, we were using the "resolver.Address{Type: resolver.Backend}" to initialize resolver.Address. However, in the documentation for gRPC 1.55.0 and later versions, there's a note that says, "// Deprecated: use Attributes instead."

I'm seeking clarification on how to represent the address type using the new "Attributes" approach. Specifically, I'm looking for information on the key-value pairs that should be used to represent the address type.

The comment in the documentation has left me a bit uncertain, so any guidance or clarity you can provide on this matter would be greatly appreciated. Thank you. cc @dfawley 

```
resolver.Address{
				Type:       resolver.Backend,
				Addr:       net.JoinHostPort(address.IP, port),
				ServerName: fmt.Sprintf("%s.%s", k.target.serviceName, k.target.serviceNamespace),
				Metadata:   nil,
			}
```

**Comment by dfawley** [comment]
Are you using grpclb?  If not, you can just stop setting this field and everything should keep working as before.

If you are using grpclb, then you'll need to use [this](https://pkg.go.dev/google.golang.org/grpc/balancer/grpclb/state#Set) to set the names of your grpclb servers in the `State` returned by your resolver (instead of using `Type: resolver.GRPCLB` on the addresses).
