### ISSUE TITLE
grpc.Dial doesn't fail fast if service isn't available

### ISSUE THREAD

**Issue by sjpotter** [grpc/grpc-go#668]
what I mean by doesn't "fail fast" is that if there is nothing listening on the port, it will go until its timeout is reached (if specified, otherwise will just retry forever it seems)

while one can specify a very short timeout (1 nanosecond), this seems like a hack, and it be nicer to be able to say "try once and fail if can't connect"

the reasoning is, sometimes you want to make decisions based on if a service is reachble or not and delaying, even for a short period is unacceptable.

**Comment by iamqizhao** [comment]
I will have upcoming change to Picker API so that the connecting is redirected different backends in each retry. If none of the backends is up, the client blocks. In my understanding this should satisfy your use case. 

In general, grpc lib wants to take over the task of reconnecting instead of pushing it to the applications.

**Comment by sjpotter** [comment]
I want to do something different.  Im modifying cadvisor to support rkt.  Its support will be disabled if rkt's grpc service isnt running (i.e. a docker only system)  This isnt about me controlling the connection manually but making other decisions if the service isnt available.

**Comment by iamqizhao** [comment]
I can make this as the behavior when dialing time-out is set to 0. But it is hard to give u a firm ETA because of some other high-priority tasks I am working on.

**Comment by okdave** [comment]
This is somewhat related to #76.

That issue was resolved by adding the timeout option, but it didn't pursue the suggestion that dialling should [fail immediately if the failure mode is permanent](https://github.com/grpc/grpc-go/issues/76#issuecomment-76320829).

**Comment by hsaliak** [comment]
Closing this issue, since the API has evolved since. if the dial option to mark Dial as blocking is set, then a timeout can be set on it. If not, Dial returns immediately and the RPCs will either fail fast or after a specified timeout. 
@sjpotter please re-open if this API is still problematic for you.
