### ISSUE TITLE
gRPC Dial function not throwing error when have insecure options

### ISSUE THREAD

**Issue by mrtdeh** [grpc/grpc-go#6738]
Hi, when I want to call a gRPC server with the insecure option and give it a non-existent address (to give an error) like the code below:
```go
conn, err := grpc.Dial("notExistedAddress", grpc.WithTransportCredentials(insecure.NewCredentials()))
if err != nil {
	  log.Fatal(fmt.Errorf("error in dial : %s", err.Error()))
}
// do not showing any error
```

We should see the "Connection Refused" error but it doesn't throw this error and ignore it.
but when i try to remove insecure option from that and then error are throws, this code are work :
```go
conn, err := grpc.Dial("notExistedAddress")
if err != nil {
	  log.Fatal(fmt.Errorf("error in dial : %s", err.Error()))
}
// showing fatal error successfuly
```
...

**Comment by mrtdeh** [comment]
I tested this scenario on different versions of go-grpc but didn't see any difference between them: 
- 1.58.0
- 1.59.0
- 1.60.0-dev

**Comment by dfawley** [comment]
This seems like a misunderstanding of how `Dial` actually works.  (And it's our fault since "Dial" is an awful name for a function with this behavior.)

Please read this and let us know if you have further questions:

https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md#dialing-in-grpc
