### ISSUE TITLE
Formalize and export xds/resolver/internal.NewXDSClient

### ISSUE THREAD

**Issue by marcoferrer** [grpc/grpc-go#6751]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?

We have an application that acts as an xds server as well as issues rpcs to the endpoints it manages. Currently we're configuring our client to connect to xds through a loopback channel. We wanted to move towards using an inprocess solution. Either leveraging an in-process rpc channel or implementing the client interface and delegating to the xds server impl. 

### Proposed Solution

Im proposing to formalize and export an experimental API that allows users to override the `NewXDSClient` method or explicitly supply an implementation for the method. Alternatively an API that would allow users to supply an instance of the xds grpc client stub would be sufficient as well and limit the scope of what would need to be exposed from the current internal implementation

### Alternatives Considered

Continue using a loopback localhost connection. Downsides to this approach are the overhead of a network request and special considerations needed for managing the xds bootstrap configuration.

### Additional Context

If this request seems reasonable, I would me more than happy to discussion the potential options for an implementation and submit a PR for review

**Comment by dfawley** [comment]
The xds client implementation is very much internal and subject to change (upcoming changes are likely necessary to support xds server fallback), and is not something we'd want to expose externally.  I'd be pretty nervous about users implementing anything at that level.

> Alternatively an API that would allow users to supply an instance of the xds grpc client stub would be sufficient.

This seems more feasible, since this is something that would primarily be implemented at the xDS API level, which is stable.  The trouble is, the xds client is a global (not something I am fond of, personally), so I'm not entirely sure how that would work.  You'd either have to set everything up very very early (before an xds client was created) or be able to set it per-channel.
