### ISSUE TITLE
Multiple xDS servers

### ISSUE THREAD

**Issue by ne0h12** [grpc/grpc-go#6753]
Hi everyone. How can I guaranty fault tolerance xDS on client? For example, I have two xDS servers and one client. Servers have the same resource configuration and send the same data. Client had connected to the first server which then got down. How can I connect to the second xDS server to get actual resource configuration? 

I can't pass both servers addresses to bootstrap file, because only [first address](https://github.com/grpc/grpc-go/blob/master/xds/internal/xdsclient/bootstrap/bootstrap.go#L467) will be used.

**Comment by dfawley** [comment]
We are working on a design for xDS fallback that should help, even if the resources configured are different, but that is probably several months away.

But you don't need that support, since your resources are expected to be identical.  In your case there are two other options:

1. Use a proxy that does the behavior you need.
2. The `xds_servers` field contains a URI, not an address, meaning if you put multiple servers behind the same domain name (or other name resolution service), then you could also get the behavior your are looking for.  When the first address is unreachable, the second would be attempted instead.
