### ISSUE TITLE
Hang on connection, same timeout for connection and RPC?

### ISSUE THREAD

**Issue by diegodimer** [grpc/grpc-go#6812]
### What version of gRPC are you using?
v1.57.0

### What version of Go are you using (`go version`)?
go version go1.21.1 windows/amd64

### What operating system (Linux, Windows, …) and version?
Windows

### What did you do?

I want to add resiliency to a system using gRPC my goal is to have the connection being able to restore itself (if it is not available at the moment, retry x times) and the RPC calls being able to retry on failures as well as not hanging on server-side (a timeout for long operations), for that I have defined a serviceConfig to which I provide to the withDefaultServiceConfig on the client side, it is defined as follows:

With this dialOpts, I configure the call to SayHello RPC
```go
dialOpts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithDefaultServiceConfig(`
		{
			"methodConfig": [
				{
					"name": [
						{"service": "helloworld.Greeter", "method": "SayHello"}
					],
					"timeout": "2s",
					"retryPolicy": {
						"maxAttempts": 5,
						"initialBackoff": "0.1s",
						"maxBackoff": "1s",
						"backoffMultiplier": 2,
						"retryableStatusCodes": [
							"UNAVAILABLE", "DEADLINE_EXCEEDED"
						]
					}
				},
				{
					"name": [
						{"service": "", "method": ""}
					],
					"timeout": "10s",
					"retryPolicy": {
						"maxAttempts": 5,
						"initialBackoff": "0.1s",
						"maxBackoff": "1s",
						"backoffMultiplier": 2,
						"retryableStatusCodes": [
							"UNAVAILABLE", "DEADLINE_EXCEEDED"
						]
					}
				}
			]
		}`),
		grpc.WithContextDialer(func(ctx context.Context, addr string) (net.Conn, error) {
			print("dialing...")
			time.Sleep(5 * time.Second)
			return (&net.Dialer{}).DialContext(ctx, "tcp", addr)
		})}
```

As my understanding, the SayHello call will have a timeout of 2 seconds on the client side, but this code will always fails with a `DeadlineExceeded` after dialing one time for 2 seconds, and it will not retry.
Is it possible to set different timeouts for connection and RPC calls? Should I always consider this connection as part of the timeout I am setting, and then I am not able to define how log I will allow the server to perform an action? 

If I completely remove the timeout, using this service config:
```json
{
	"methodConfig": [
		{
			"name": [{"service": ""}],
			"waitForReady": true,
			"retryPolicy": {
				"MaxAttempts": 5,
				"InitialBackoff": "0.1s",
				"MaxBackoff": "10s",
				"BackoffMultiplier": 1.0,
				"RetryableStatusCodes": ["UNAVAILABLE", "RESOURCE_EXHAUSTED"]
			}
		}
	]
}
```
When I connect, using the same contextDialer I defined before, I see that the connection attempts will *never* stop. Is this the expected behavior? If I want to set only retry for my RPC calls I necessarily need to provide a timeout, otherwise my connections will hang forever?
I want to have a long-living bi-direction stream as well, if I set the timeout, will I not be able to have that? 

### What did you expect to see?
Connection retrying, and not hanging forever

### What did you see instead?
Connection hang, same timeout for everything

**Comment by zasweq** [comment]
Yes, there are different settings for connection timeouts and RPC timeouts (e.g. you can set a dial option for connection timeout, context deadline for RPC timeout). Quick question though, why do you even want to set the connection timeout? It is strongly not recommended to use connection timeouts.

**Comment by zasweq** [comment]
retryPolicy has a maxAttempts field, which can gate how many retries happen on a connection. Thus, other RPC's which may work may still happen on the connection. There is no need to hard close the connection to prevent retries.

**Comment by zasweq** [comment]
You mentioned you want to prevent RPC's from retrying indefinitely, so the retry on the connection and on operations makes sense here.

**Comment by diegodimer** [comment]
> You mentioned you want to prevent RPC's from retrying indefinitely, so the retry on the rpc operations and not connections makes sense here.

yes, but the retry on the maxAttempts doesn't seem to affect connections, as you can see in the example when I remove the timeout and leave the maxAttempts, it will not stop

**Comment by zasweq** [comment]
Yes, that is WAI. The retries are on the RPC.

**Comment by zasweq** [comment]
That feature is not present on the connection, and also doesn't make sense on the connection, as retries are an RPC concept, not a connection concept.

**Comment by diegodimer** [comment]
> That feature is not present on the connection, and also doesn't make sense on the connection, as retries are an RPC concept, not a connection concept.

this is exactly my point, if we set to rpc the retries, and we didn't specify a timeout, we will get connection hanging forever. This is a dependency that doesn't really make sense.

**Comment by frbvianna** [comment]
> Yes, there are different settings for connection timeouts and RPC timeouts (e.g. you can set a dial option for connection timeout, context deadline for RPC timeout). Quick question though, why do you even want to set the connection timeout? It is strongly not recommended to use connection timeouts.

@zasweq, what dial option can be used to apply a connection timeout?

What I see is also that if a timeout is **not** set in the gRPC service config (and neither in the RPC context), then in case of a connection error, the RPC seems to hang indefinitely in connection backoff. There may even be some backoff max delay defaults but it does not seem to be clearly documented.

There doesn't seem to be a configuration for a total time span limit of the connection backoff itself, such as 'max backoff' or simply a 'timeout'. I tried to use the `grpc.WithConnectParams` to specify connection backoff configs but it only allows to specify a `MinConnectTimeout` which is not clear what it does but also does not limit the actual connection backoff. The `MaxDelay` also seems to limit the maximum delay between two backoff attempts, and not the actual backoff total time span.

https://github.com/grpc/grpc-go/blob/686fdd8da147d7bf91690d02c8dd0c7d572f2f6d/dialoptions.go#L253-L268

So it feels like the timeout in the service config (or a deadline in the RPC context) is necessarily required if one wishes to control the maximum time for a connection backoff, otherwise it could hang for a very long time in case of a connection error. But this same timeout necessarily applies to the entire RPC as well (which may be a long-living stream) and that may be conflicting if we want to specify different timeouts for connections and RPCs.

Is there really a way to specify a timeout for the connection separately from the RPC?

**Comment by zasweq** [comment]
I mentioned earlier how to set the two timeouts, but like I mentioned the Conn timeout really shouldn't be used in most cases.

**Comment by frbvianna** [comment]
> > retryPolicy has a maxAttempts field, which can gate how many retries happen on a connection. Thus, other RPC's which may work may still happen on the connection. There is no need to hard close the connection to prevent retries.
> 
> yeah, but the "maxAttempts" was not working for connection, only for operations

Like @diegodimer, maxAttempts does not affect connection retries. So this does not answer my question.

**Comment by frbvianna** [comment]
>  but like I mentioned the Conn timeout really shouldn't be used in most cases.

That makes no sense to me. The issue reported here is that, once a service config is set, the app **has** to set an RPC timeout as well to implicitly limit the connection backoff, otherwise, with no RPC timeout defined, the connection backoff would have been limited and would keep retrying for an indefinite amount of time.

**Comment by zasweq** [comment]
An RPC has to happen on a connection. What is wrong with an RPC failing with the information that the connection has not been established? What additional value would you get out of the connection timeout that you don't get from the RPC timeout?

**Comment by zasweq** [comment]
A connection backing off is WAI and built into the gRPC protocol. See https://chromium.googlesource.com/external/github.com/grpc/grpc/+/release-0_9/doc/connection-backoff.md for more information. Thus, connections retrying is capped by the minimum connection timeout, and the time between attempts continues to increase "to avoid flooding the network or the server with requests"

**Comment by zasweq** [comment]
The WithConnectParams linked can control the knobs of this connection timeout. For RPC timeouts, you can use the context passed into the RPC. For RPC *Retries* you can use the service config knobs linked in the service config.

**Comment by frbvianna** [comment]
> An RPC has to happen on a connection. What is wrong with an RPC failing with the information that the connection has not been established? What additional value would you get out of the connection timeout that you don't get from the RPC timeout?

Nothing wrong with an RPC failing due to the connection failing.
The issue is that we have no apparent or simple way to specify a **separate connection timeout in the client-side** than the RPC / context timeout. 
For instance, if I have a stream RPC and I wish this stream RPC to have a long timeout (e.g. 200 seconds), then in case the server is down for a long time period, my client will remain in connection backoff for the whole 200 seconds of RPC timeout.

Why not have a ClientOption for `ConnectTimeout` similar to the [server option](https://github.com/grpc/grpc-go/blob/master/server.go#L529) or have that as a parameter in the existing `WithConnectParams`? This way we could separately control how long the operation can remain in connection backoff instead of implicitly limited by the RPC timeout or limited by the server option.
Otherwise, if I want to e.g. limit my connection backoff to a total of 10 seconds, how might I achieve this with the existing connection parameters on the client-side?
