### ISSUE TITLE
Could not block a goroutine in unary rpc method?

### ISSUE THREAD

**Issue by ruinanchen** [grpc/grpc-go#697]
Currently, a goroutine in a rpcclient will block the goroutine in unary rpc method. Until rpc server return response or error occur, the goroutine execute next code.But, I want to a new way: Call unary rpc method and register a callback function. I think, do in this way, less real-time goroutines exists and a better performance got.

**Comment by iamqizhao** [comment]
gRPC-Go API is pretty Go idiomatic so that it only has blocing/sync API. This is the whole point of Go's concurrency pattern to make things simpler to code and maintain. It may or may not have performance impact depending on your use cases. We do not have plan to add async API. If you are really demanding on performance and like async RPCs, you can probably try gRPC-C/C++.
