### ISSUE TITLE
StreamServerInterceptor context alteration

### ISSUE THREAD

**Issue by alexdeefuse** [grpc/grpc-go#700]
Hi,

I am looking for a way to change the Stream Context on a per-request basis.
Ideally I am looking to have a separate database connection for each stream handler and I see no way to pass that to the handler (mgo.Session.Copy()).

I've looked at the StreamServerInterceptor that gets as a param ServerStream that indeed has a way to get the request context (the Context method) but I see no way of actually changing that context. Is there a way to do this?

Best,
Alex

**Comment by iamqizhao** [comment]
Since you implement your own ServerStream you can attach whatever context you want.

**Comment by alexdeefuse** [comment]
Sorry, I've read your comment a number of times, then looked at the code and I don't get what you are saying. Could you elaborate?

**Comment by iamqizhao** [comment]
when you implement https://github.com/grpc/grpc-go/blob/master/interceptor.go#L74, you get a "ss". You can use "ss" to implement your own ServerStream. In this step, you can decide what context ServerStream.Context() returns. Then when you call the grpc.StreamHandler (e.g., https://github.com/grpc/grpc-go/blob/master/test/end2end_test.go#L1804), you can pass in your own ServerStream instead of the original "ss".

**Comment by alexdeefuse** [comment]
Thank you for taking the time to write further explanations.
I now understand how you see this implemented.

The reason I was in the dark is because the manner in which context would be used here goes against: https://github.com/golang/net/blob/master/context/context.go#L18 (grpc-go/transport/transport.go).
