### ISSUE TITLE
grpc processes connection data to start multiple Goroutines, and whether Goroutines can be merged to reduce additional overhead

### ISSUE THREAD

**Issue by LinJim** [grpc/grpc-go#7031]
The handleRawConn(lisAddr string, rawConn net.Conn) method is itself a goroutine, and at the end of the method a goroutine is created to handle the data. But the method itself is coming to an end, so why not just use the method's original goroutine instead of restarting a goroutine to process the data? goroutine switching also consumes resources, albeit very little

```
// handleRawConn forks a goroutine to handle a just-accepted connection that
// has not had any I/O performed on it yet.
func (s *Server) handleRawConn(lisAddr string, rawConn net.Conn) {
	if s.quit.HasFired() {
		rawConn.Close()
		return
	}
	rawConn.SetDeadline(time.Now().Add(s.opts.connectionTimeout))

	// Finish handshaking (HTTP2)
	st := s.newHTTP2Transport(rawConn)
	rawConn.SetDeadline(time.Time{})
	if st == nil {
		return
	}

	if cc, ok := rawConn.(interface {
		PassServerTransport(transport.ServerTransport)
	}); ok {
		cc.PassServerTransport(st)
	}

	if !s.addConn(lisAddr, st) {
		return
	}
	go func() {
		s.serveStreams(context.Background(), st, rawConn)
		s.removeConn(lisAddr, st)
	}()
}
```

**Comment by arvindbr8** [comment]
The reason for spinning a new goroutine is so that `handleRawConn` is not blocking and returns right after setting everything required to serveStream and continue handling other connections in the server listener.  The tradeoff here is the concurrency of server.Serve() to handle multiple concurrent connections for a small overhead of spinning a new goroutine.

Feel free to suggest an alternative if you feel this can be done better. Send us a PR with the suggested changes and we can take a look at it.
