### ISSUE TITLE
should restrict ENUM values input

### ISSUE THREAD

**Issue by Achillesss** [grpc/grpc-go#724]
I have the following proto

```
service GetWeekDayService {
    rpc GetWeekDay (Day) returns (DayResponse){};
}

message Day {
    enum WeekDay {
        Monday = 0;
        Tuesday = 1;
        Thursday = 2;
        Wensday = 3;
        Friday = 4;
        Saturday = 5;
        Sunday = 6;
    }
    WeekDay day = 1;
}

message DayResponse {
    bool isWeekDay = 1;
}
```

while I can make the following call:

```
day = &pb.Day{Day: pb.Day_WeekDay(10000)}
client.GetWeekDay(context.Background(), day)
```

I was expecting gRPC would raise an InvalidArguments error when I send Day(10000), cuz there's just 7 numbers in your enum.

PS: you can find demo of this problem in project:https://github.com/Achillesss/gRPC_enum_bug

**Comment by menghanl** [comment]
gRPC cannot do this check for you.

I would suggest you do the check by yourself using map `Day_WeekDay_name`. Add a check for the incoming `day.Day` to your server code, and return an error if `day.Day` is not valid.

Another suggestion is to use consts defined by protobuf when constructing `Day_WeekDay`, like `Day_Monday`, instead of integers.

**Comment by Achillesss** [comment]
Since I can not ensure using Day_WeekDay on client side, I may check by Day_WeekDay_name.

Thanks for your help.
