### ISSUE TITLE
grpc.NewClient with namedpipe on Windows throws resolverError

### ISSUE THREAD

**Issue by ensonsan** [grpc/grpc-go#7288]
Hi, 
Recently I have been building a grpc service over namedpipe on Windows.

The namedPipe is created with the Microsoft winio packge.

Firstly I followed the grpc doc to use the recommanded NewClient method for creating a client, however I got `rpc error: code = Unavailable desc = name resolver error: produced zero addresses`

Then I switched to the deprecated Dial method which then I got the expected result.

I am wondering if namedpipe can be supported with the recommanded method since it is in the doc.

Thanks!

**Comment by dfawley** [comment]
How are you creating your client?

You can most likely use `NewClient("passthrough:///"+whateverYouWereDialingBefore)` to resolve the problem.  The issue is that the default name resolver used to be "passthrough", which isn't desirable for most users, but is needed if you are using a custom dialer and are expecting the target to be passed to the dialer.

Related: https://github.com/grpc/grpc-go/issues/7091
