### ISSUE TITLE
Make transport.SetConnection public?

### ISSUE THREAD

**Issue by Zenithar** [grpc/grpc-go#7333]
> TLDR: Could you expose the SetConnection function to allow Connection injection from public packages like `peer.NewContext`?

I'm currently working on a gRPC Authz policy test runner used to audit policy from files and given test cases without starting the complete stack.

I've made significant progress preparing the context to run the interceptor directly. However, I've hit a roadblock with the `transport.SetConnection` function, which is inaccessible from the 'outside' of the grpc-go package due to its internal exposition. https://github.com/grpc/grpc-go/blob/c04b085930ce33ee83cc3f92dbe7632031e127a9/internal/transport/http2_server.go#L1460

The transport is required here in the interceptor to retrieve the local address and the destination port.
 https://github.com/grpc/grpc-go/blob/c04b085930ce33ee83cc3f92dbe7632031e127a9/internal/xds/rbac/rbac_engine.go#L225
  
Alternatively, I tried to set up a full stack, but it increases the preparation complexity and make the test slow. I also investigated using the RBAC engine directly, but the same issue: the package is internal and can't be imported.

I understand that there are many reasons to keep these packages private. Could you expose the SetConnection function to allow Connection injection from public packages like `peer.NewContext`?

**Comment by atollena** [comment]
It's likely that we don't want setting the connection in the context to be a public API just to simplify testing of the usage of RBAC interceptors. The functionality to obtain local and peer addresses are otherwise available via the [peer package](https://pkg.go.dev/google.golang.org/grpc/peer). I do wonder though why the RBAC filter does not simply use the public `peer.LocalAddr` which is available in the context.

> Alternatively, I tried to set up a full stack, but it increases the preparation complexity and make the test slow.

A lot of the tests in grpc-go work like this, so that's the approach I would recommend. You can look at examples in https://github.com/grpc/grpc-go/blob/c04b085930ce33ee83cc3f92dbe7632031e127a9/authz/grpc_authz_end2end_test.go. Each test that starts a client and a server run in less than 1-2 millisecond. There's maybe a bit more boilerplate for setup, but that's enough to justify making this API public.

**Comment by atollena** [comment]
@zasweq do you happen to remember why we directly want to use the `conn.LocalAddr` rather than `peer.LocalAddr` in the RBAC filter code: https://github.com/grpc/grpc-go/blob/c04b085930ce33ee83cc3f92dbe7632031e127a9/internal/xds/rbac/rbac_engine.go#L223-L228 ?

**Comment by atollena** [comment]
Anyways, I think your best option for your use case seems to be end to end tests that don't rely on how the RBAC filter communicates with gRPC's transport. Let us know if that doesn't work for you, and why.

**Comment by Zenithar** [comment]
Ok, thank you. I will find another way to build a policy tester without setting up the complete gRPC stack.
