### ISSUE TITLE
Support for custom code check

### ISSUE THREAD

**Issue by SaiTejaSuvvari02** [grpc/grpc-go#7414]
https://github.com/grpc/grpc-go/pull/7413
We don't have a simple way to check if code is a custom code (not gRPC defined). Above PR adds support to have that check. Please let me know your thoughts on this.

@aranjans @easwars

**Comment by purnesh42H** [comment]
@SaiTejaSuvvari02 could you provide more details on what is your usecase for requesting this feature? Also, we link the issue in the PR description mentioning it as fix, not the other way round

**Comment by SaiTejaSuvvari02** [comment]
Understood linking issue in PR description, will fix it. Came across a usecase where we want to decide logger level based on grpc status code. Specifically, we want to define a specific log level for all custom codes defined. This required a method implemented out of the grpc library to decide if a code is not grpc defined. Hence wanted to check if this support can be added as part of the library or is there any better alternative for this. @purnesh42H

**Comment by purnesh42H** [comment]
@SaiTejaSuvvari02 will discuss with team and get back to you

**Comment by purnesh42H** [comment]
@SaiTejaSuvvari02 based on discussion with team, although this is a good to have feature we currently don't want to add new functionalities to `codes` as that will require maintenance as well

**Comment by dfawley** [comment]
> custom codes

This is the main problem with this proposal: any values outside of those defined by gRPC are not supported:

https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

> Applications should only use values defined above. gRPC libraries that encounter values outside this range must either propagate them directly or convert them to UNKNOWN.

Some languages' libraries will convert anything outside the range to UNKNOWN, so if you are relying on this behavior then you will have problems when migrating to other languages or adding new clients or servers in other languages.  In addition, we consider it a mistake that we did not implement this conversion in Go in order to discourage the use of "custom codes".

You should not rely on this and find another way to do what you want.  If you let us know more about your use case we can try to help.

**Comment by dfawley** [comment]
For more info see: #6662 (which implemented this conversion, but was rolled back due to the breaking behavior change) and #6673 which re-applied the rest of the changes without that part.
