### ISSUE TITLE
Why does connection to `localhost`  fail on local ?

### ISSUE THREAD

**Issue by manuraj17** [grpc/grpc-go#7429]
I faced this issue when I was testing out a simple application; Not able to put a finger on what exactly am missing.

My client code is returning with this error
```sh
could not greet: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

I have my server running as 
```go
const (
	port = ":50051"
)

// server is used to implement helloworld.GreeterServer.
type server struct {
	helloworld.UnimplementedGreeterServer
}

// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *helloworld.HelloRequest) (*helloworld.HelloReply, error) {
	log.Printf("Received: %v\n", in.GetName())
	return &helloworld.HelloReply{Message: "Hello " + in.Name}, nil
}

func main() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	helloworld.RegisterGreeterServer(s, &server{})
	log.Printf("server starting at %v\n", lis.Addr())
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
```

Client connecting to `localhost` as 
```go
const (
	address = "localhost:50051"
	// address     = "[::1]:50051"

	// address     = "127.0.0.1:50051"
	defaultName = "world"
)

func main() {
	// Set up a connection to the server.
	conn, err := grpc.NewClient(address, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
	c := helloworld.NewGreeterClient(conn)

	// Contact the server and print out its response.
	name := defaultName
	if len(os.Args) > 1 {
		name = os.Args[1]
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	r, err := c.SayHello(ctx, &helloworld.HelloRequest{Name: name})
	if err != nil {
		log.Fatalf("could not greet: %v", err)
	}
	log.Printf("Greeting: %s", r.GetMessage())
}
```

This code fails.

But when I connect with either of 
```
	address     = "[::1]:50051"
	address     = "127.0.0.1:50051"
```

It works. I am trying to understand what am missing here.  Can anyone help me understand? TIA!

Full application code available [here](https://github.com/manuraj17/sample-grpc)

## UPDATE (More Info):

Some more information
Version
```
google.golang.org/grpc v1.65.0
```

I am able to connect if I am using `127.0.0.0` and `[::1]` 
The issue specifically seems to occur when `localhost` is used. 

`etc/hosts` is below
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
127.0.0.1       mail.local
255.255.255.255 broadcasthost
::1             localhost
```
I am running the server at `add = :50051` and initialising like
```
	lis, err := net.Listen("tcp", port)
```

### It works with Dial
When I use `Dial` it works
```go
	conn, err := grpc.DialContext(ctx, addr,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithBlock(),
	)
```

I have tried all variations to connect without using Dial, and everything except `localhost` works. The resolution of localhost also seems to be working correctly. I get the following logs
```
 localhost resolves to: [::1 127.0.0.1]
 ```
 NOTE: IPV6 gets resolved first.
 
 Though I am not able to figure what failed here. I will have end up not using localhost for now. Though, curious what is happening here.

**Comment by purnesh42H** [comment]
Thanks for the question @manuraj17. `localhost` typically resolves to the loopback address 127.0.0.1 for IPv4 and ::1 for IPv6. The exact behavior can depend on your system's configuration (e.g., /etc/hosts file on Unix-based systems). As you mentioned specifying localhost might be resolving to an IPv6 address by default (::1) so If your server is not properly listening on both IPv4 and IPv6 addresses, the client might not be able to connect.

Explicitly specifying 127.0.0.1 or [::1] ensures that the client uses IPv4 or IPv6 respectively

**Comment by purnesh42H** [comment]
@manuraj17 I was also able to repro on my local with `localhost`. Will discuss with team and update on what is the best course of action here. Thanks once again for catching this.

**Comment by manuraj17** [comment]
@purnesh42H Thanks for checking on this. Will wait for the update 👍🏽

**Comment by purnesh42H** [comment]
Client logs with 1 second timeout when using `localhost` with `grpc.NewClient`

```
2024/07/23 21:08:08 INFO: [core] original dial target is: "localhost:50051"
2024/07/23 21:08:08 INFO: [core] [Channel #1]Channel created
2024/07/23 21:08:08 INFO: [core] [Channel #1]parsed dial target is: resolver.Target{URL:url.URL{Scheme:"dns", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"/localhost:50051", RawPath:"", OmitHost:false, ForceQuery:false, RawQuery:"", Fragment:"", RawFragment:""}}
2024/07/23 21:08:08 INFO: [core] [Channel #1]Channel authority set to "localhost:50051"
2024/07/23 21:08:08 INFO: [core] [Channel #1]Channel exiting idle mode
2024/07/23 21:08:13 could not greet: rpc error: code = DeadlineExceeded desc = context deadline exceeded
exit status 1
```

**Comment by manuraj17** [comment]
@purnesh42H 
Could share what changed between from being able to reproduce to now? Just curious on what happened earlier and what is happening now.

**Comment by purnesh42H** [comment]
@manuraj17 the problem seems to be in `grpc.NewClient`. The address solution is taking longer when using `localhost` and that's why you experience timeout. If you try the same example with 10s timeout, rpc will succeed. We are still debugging the root cause.

**Comment by purnesh42H** [comment]
this call is blocked for longer https://github.com/grpc/grpc-go/blob/2bcbcab9fbeec8a475631e8f06bd0cb45eb92dc8/stream.go#L212

**Comment by dfawley** [comment]
Are you still able to reproduce this?  Can you run with full debug logging enabled and include the logs?

https://github.com/grpc/grpc-go#how-to-turn-on-logging

**Comment by manuraj17** [comment]
@dfawley Will check and update; Though any idea on what is happening in this scenario? 
@purnesh42H was able to identify and figure it's a resolution issue. Curious as to what information you folks have regarding this.

**Comment by dfawley** [comment]
> @dfawley Will check and update; Though any idea on what is happening in this scenario?

No idea.  If your machine can't resolve `localhost`, or properly connect to an address it returns, then that sounds like a configuration issue to me.

**Comment by manuraj17** [comment]
> No idea. If your machine can't resolve localhost, or properly connect to an address it returns, then that sounds like a configuration issue to me.

If it's my machine issue wouldn't it fail for 
- `Dial` method
- every other app that is running in localhost

Not sure what what you are on to here coz it still doesn't clariy how @purnesh42H was able to reproduce it for a while; did he have some configuration issue?

**Comment by purnesh42H** [comment]
@manuraj17 can you pull the latest and then try running with `grpc.NewClient` and `localhost` with the logging turned on https://github.com/grpc/grpc-go#how-to-turn-on-logging? Since, this is not always reproducible, we need more information to verify if its a library or configuration issue.

To clarify, even for me the resolution was just taking a bit longer with `localhost` but that's not happening anymore

**Comment by manuraj17** [comment]
@purnesh42H 
> can you pull the latest
Are you suggesting the latest from the grpc main branch?

**Comment by purnesh42H** [comment]
> Are you suggesting the latest from the grpc main branch?

Yes

**Comment by ciaphas01** [comment]
We ran into this issue running code using the latest grpc-go release as of 8 August 2024. While I unfortunately cannot provide any logs or code, I can say we only started seeing the issue when switching from using `Dial` to `NewClient`, as previously commented, and only *when all nameservers listed in `/etc/resolv.conf` were unreachable*. (Figuring this part out took a while!)

Similar to the reporter, changing from localhost to 127.0.0.1 for the server and client also avoided the error, even with all invalid/unreachable nameservers in `/etc/resolv.conf`.

**Comment by ciaphas01** [comment]
Apologies for the double post, forgot the @purnesh42H and I'm not sure editing mentions into comments actually works lol

**Comment by ciaphas01** [comment]
Update: curiously, the problem seems to stop manifesting immediately when the machine is physically disconnected from all networks. Perhaps somewhere there's code that's causing this DNS record lookup to get skipped if all network interfaces are down, allowing the localhost entry in /etc/hosts to take over and the health check to proceed?

**Comment by purnesh42H** [comment]
In new `grpc.NewClient` the default name resolution is `dns` as opposed to `passthrough` in deprecated `grpc.Dial`. Try `NewClient` with `passthrough` as the resolver and it should behave the same. 

This type of issue with dns resolution is more likely related to system configuration rather than a problem with the gRPC library itself as it relies on the underlying system for DNS resolution. If the system takes time to resolve localhost, this delay will be reflected in gRPC client behavior as well.

**Comment by ClaudioAlbertin** [comment]
We are seeing the same issue, and indeed using `passthrough` works. But even with passthrough `net.Dial` will eventually perform the DNS resolution, and this seemingly works just fine, so I think there is an open question about what the grpc-go DNS resolver does differently to provoke this issue (both use `net.Resolver` eventually).
I'm not sure it should just be written off to system misconfiguration. Even if that was a factor, the people encountering this seem to have no other issues with DNS resolution (we don't) and are slowed down while trying to switch to `NewClient` with the recommended default resolution scheme. It'd be great to at least find a more satisfying explanation.

**Comment by arjan-bal** [comment]
@ClaudioAlbertin can you provide the [gRPC logs](https://github.com/grpc/grpc-go?tab=readme-ov-file#how-to-turn-on-logging) when the DNS resolver fails?

**Comment by purnesh42H** [comment]
> @ClaudioAlbertin can you provide the [gRPC logs](https://github.com/grpc/grpc-go?tab=readme-ov-file#how-to-turn-on-logging) when the DNS resolver fails?

@ClaudioAlbertin ping on this

**Comment by ClaudioAlbertin** [comment]
Unfortunately I can only reliably reproduce the issue on our CI server in some tests with very noisy output, but I'll see what logs I can get out of it.

It may be worth noting for @manuraj17 that the grpc-go DNS resolver also performs a lookup for a TXT record (in the hope of finding a Service Config), which does not happen if an IP address or the passthrough resolver is used. This lookup contacts an actual DNS server, whereas resolving `localhost` otherwise just involves reading local files. This could contribute to the RPC taking much longer with `grpc.NewClient` vs `grpc.Dial`. You can test whether this is your issue by disabling service configs and by extension the TXT lookup using the `grpc.WithDisableServiceConfig()` dial option. This did not fix the issue for us, however.

**Comment by arjan-bal** [comment]
@manuraj17 as suggested by @ClaudioAlbertin, can you try disabling service config using the `grpc.WithDisableServiceConfig()` dial option and seeing if `localhost` resolution works with `grpc.NewClient`? If it does, it means that all the nameservers present in the `/etc/resolv.conf` are probably un-reachable.

**Comment by arjan-bal** [comment]
@ClaudioAlbertin to be sure, are you seeing the issue with `localhost` or another hostname? 

Also, do you happen to be using an http proxy? If yes, there is a known issue (https://github.com/grpc/grpc-go/issues/7556) which cause DNS resolution to happen on the client instead of the proxy which could cause timeouts if the client can't reach the DNS itself.

**Comment by cakoolen** [comment]
@ClaudioAlbertin wrote:
> We are seeing the same issue, and indeed using `passthrough` works.

How do I use `passthrough` through the API then? Looking at the code of `Dial` it uses a private option called `withDefaultScheme("passthrough")` but since that is private, I cannot use it. It would be helpful if the deprecated function was implemented in such a way that we could fully reproduce it in the code that uses it to get rid of the deprecated code!

**Comment by purnesh42H** [comment]
> @ClaudioAlbertin wrote:
> 
> > We are seeing the same issue, and indeed using `passthrough` works.
> 
> How do I use `passthrough` through the API then? Looking at the code of `Dial` it uses a private option called `withDefaultScheme("passthrough")` but since that is private, I cannot use it. It would be helpful if the deprecated function was implemented in such a way that we could fully reproduce it in the code that uses it to get rid of the deprecated code!

`grpc.Dial` by default uses `passthrough` scheme so you don't have to do anything but if you are using `grpc.NewClient` then you can prefix your url with `passthrough:///` to skip the dns resolution on the client.

**Comment by peterchenadded** [comment]
Can someone explain why this isn't a bug. The 127.0.01 localhost entry is in the /etc/hosts file so why is it trying to look through the nameservers to resolve it.

I understand that the name servers maybe misbehaving and not responding, that's a separate issue.

This is a problem because some upstream repos such as OTEL don't even allow you to use passthrough:/// so you can't fix the issue unless you have root access to the server to fix up the name servers in /etc/resolv.conf.

**Comment by dfawley** [comment]
@peterchenadded,

By default gRPC-Go uses the `net.DefaultResolver`.  If that's not using `/etc/hosts` for you, then that could be an issue with your system configuration or Go's implementation (less likely).  It looks like the logic for the latter is around here: https://cs.opensource.google/go/go/+/master:src/net/conf.go;l=241;drc=6536c207c2309da7c1c21e3669f8ddf491e31f5b

Also, make sure you are not importing `grpc/balancer/grpclb` anywhere in your binary, or else SRV record lookups will be attempted, which you presumably don't want, since that can't be retrieved from the local filesystem.

If you are still having problems with gRPC and you can't reproduce the issue using `net.DefaultResolver.LookupHost("localhost")`, then please file a new issue instead of using this one.

**Comment by peterchenadded** [comment]
Thanks @dfawley

I confirmed I don't have grpclb anywhere in my go.mod

I also confirmed net.DefaultResolver.LookupIP(...) works with no issues and comes back straight away.

Will raise a new issue as you suggested and provide the link.
