### ISSUE TITLE
google.protobuf.Empty as response serializes to not empty response depending on request headers

### ISSUE THREAD

**Issue by abraxasjoshuricke** [grpc/grpc-go#7459]
### What version of gRPC are you using?
v1.59.0

### What version of Go are you using (`go version`)?
v1.22

### What operating system (Linux, Windows, …) and version?
Linux alpine3.19

### What did you do?
We are using protobuf with grpc-gateway for our go application. When returning google.protobuf.Empty we are getting an not empty response. This happens depending on what request headers are being sent.
These two headers in combination result in the faulty behaviour:
'Accept: text/html'
'Content-Type: application/x-www-form-urlencoded'

### What did you expect to see?
An empty response, regardless of what headers are being sent.

### What did you see instead?
Flags=3&denseCoderFields=null&initDone=1&isMessageSet=false&needsInitCheck=false&numRequiredFields=0&sema=0&sizeCache=0&state=0&unknownPtrKind=false

I debugged pretty deep into the source code and found out that the fields getting serialized to the response are from the message field 'coderMessageInfo' -> https://github.com/protocolbuffers/protobuf-go/blob/v1.31.0/internal/impl/codec_message.go#L22
Sadly I was not able to figure out where and why these fields are getting serialized.

Thanks for your help!

Kind Regards
Joshu

**Comment by arjan-bal** [comment]
Hi @abraxasjoshuricke, from your description it seems like the non-empty response is received by a REST client from `grpc-gateway`, it this correct? 
gRPC should be returning messages of type `google.protobuf.Empty` and I believe the behaviour you described is due to the gRPC->REST conversion happening in `grpc-gateway`.  The [grpc-gateway project](https://github.com/grpc-ecosystem/grpc-gateway) is not maintained by the [gRPC organization](https://github.com/grpc), so I suggest asking the question on the `grpc-gateway` repo or stackoverflow.
