### ISSUE TITLE
timeouts, addresses, and networks are a mess

### ISSUE THREAD

**Issue by tamird** [grpc/grpc-go#758]
In the public API, there are a number of "oddities".
- `net.Dial` does not do cancellation correctly (#751).
- `grpc.Dial` takes only a "target" string, compared to `net.Dial` which takes "network" and "address" strings. This makes it necessary to supply a "dialer" which is hardcoded to "unix" in some tests.
- `grpc.WithTimeout` is used to control `grpc.Dial`, but `context.Context` is used to control timeouts on individual RPCs.

I'm considering working on a PR that refactors these interfaces to use context.Context throughout, but I wanted to get feedback before getting too deep into the implementation.

My understanding is that GA is approaching quickly, and that this refactoring will not be possible after GA.

@iamqizhao @bradfitz

**Comment by iamqizhao** [comment]
> net.Dial does not do cancellation correctly (#751).
Your proposal is not sufficient. There are some use cases which requires some special dialing ways (e..g, dialing from a GAE) that cannot be achieved by net.Dialer. We need a better solution. But technically, not all the dialing operations can be cancelled.
> grpc.Dial takes only a "target" string, compared to net.Dial which takes "network" and "address" strings. This makes it necessary to supply a "dialer" which is hardcoded to "unix" in some tests.
As a rpc lib, users usually typically only has a service DNS name and do not know what network they should use. This makes it different from net.Dial case. This also leaves the possibility grpc internals can choose the optimal network type for the users in the future (e.g., for intra-cluster traffic, use RDMA, for inter-cluster traffic, use TCP, etc.). Maybe we can add a grpc.DialNet API for you if you really want to specify network.
> grpc.WithTimeout is used to control grpc.Dial, but context.Context is used to control timeouts on individual RPCs.
context is request scoped and I am not convinced it applies to connection. In addition, I think it introduces the confusion to the users.

**Comment by iamqizhao** [comment]
> OK, let's discuss that in #751. In particular, what special dialing requirements are you thinking of?

Sure, replied there already. Some of them cannot be canceled.

> Seems like putting the cart before the horse. Take a look at some of the tests which already have to jump through hoops to get unix sockets working.

My stand is that golang net package is like the socket lib in C/C++ which provides the functionality for users to develop various communication apps/tools. RPC lib is one of them and builds on top of golang net. Since it is an application of golang net instead of a counterpart, it is reasonable to hide some config details (e.g., network type) inside just like we do not expose all socket type and options to our users when developing using socket. In my opinion, it is not necessary to let users specify the network type since most of them do not care. A small number of advanced users can use WithDialer option to achieve that purpose when they want. In addition, even if we add "network" to grpc.Dial, it is not equivalent to net.Dial because grpc does not support UDP and IP but instead it can support "in-process" and net.Pipe which are not supported by net.Dial. Thus we need to define our own list of "network". And again all of these sound overwhelming to common users.

> Is it? Go 1.7 introduced net.DialContext, so it seems that upstream disagrees with you. Perhaps @bradfitz could provide some guidance.

Good to know. Interestingly if you look at https://github.com/grpc/grpc-go/blob/a0ff1e78a98cd140c2d18a0210ab0a2a183a2b4c/transport/http2_client.go#L70, you can see I had the similar concept but it was rejected by them. But now it seems they have changed their opinon. I think we could add another API (something like grpc.DialContext(...)) or DialOption while keeping the existing API intact if this is really helpful (for cancellable dial).

**Comment by tamird** [comment]
Sounds good. I've updated #751 and I'll let you know when I've had a chance to explore a context-based enhancement.

**Comment by broady** [comment]
Yes, I disagree that `context.Context` is request scoped. I know of several significant projects that use Contexts that span various parts of an application lifecycle.

**Comment by tamird** [comment]
One more thing: after spending some time in this code with #796, I'm realizing that grpc is a soup of channels and extremely hard to reason-about cancellation propagation.

We should refactor this pretty extensively to use context-based cancellation so that it is propagated properly instead of the current soup of parents having to signal closure to their children (e.g. ClientConn -> addrConn -> transport, Server -> transport).

**Comment by dfawley** [comment]
I did a good amount of refactoring with #1533 to help improve context propagation and cancellation.  If there's anything more of concern here, please let us know.
