### ISSUE TITLE
parseServiceConfig should fail when unknown fields are present

### ISSUE THREAD

**Issue by lavacat** [grpc/grpc-go#7818]
### Use case(s) - what problem will this feature solve?

When [parsing](https://github.com/grpc/grpc-go/blob/18d218d14d5076fae0995363a85fb2accb7b4979/service_config.go#L176) service config that has typos, config will be ignored. No error will be logged.
I found this when experimenting with etcd service config in [this](https://github.com/etcd-io/etcd/blob/75274b24e22f9b3e66fa2afdf8dc5063a9dbf22b/tests/e2e/failover_test.go#L67) test.

### Proposed Solution
https://baharbshah.medium.com/gos-unmarshal-errors-might-not-work-the-way-you-think-they-do-949f8fe15a09
Use `DisallowUnknownFields`
Add tests

**Comment by aranjans** [comment]
@lavacat In gRPC-go, ignoring unknown fields in service config JSON is actually the intended behavior. This is by design for several reasons:

- Interoperability: Different gRPC implementations (Go, Java, C++, etc.) might support different features and configuration options. Ignoring unknown fields allows configs to work across different implementations.
- Error Handling: The parser does fail on invalid values for known fields. For example:
``` 
if sc.retryThrottling != nil {
        if mt := sc.retryThrottling.MaxTokens; mt <= 0 || mt > 1000 {
            return &serviceconfig.ParseResult{Err: fmt.Errorf("invalid retry throttling config: maxTokens (%v) out of range (0, 1000]", mt)}
        }
        if tr := sc.retryThrottling.TokenRatio; tr <= 0 {
            return &serviceconfig.ParseResult{Err: fmt.Errorf("invalid retry throttling config: tokenRatio (%v) may not be negative", tr)}
        }
    }
```
If you wish, you can write validation on your side against the ServiceConfig proto to make it work that way. 

Thanks,
