### ISSUE TITLE
passthrough scheme not documented

### ISSUE THREAD

**Issue by rittneje** [grpc/grpc-go#7856]
As far as I can tell, the `passthrough:///` scheme does not appear to be documented anywhere. It is needed in order to properly use the bufconn package.

It is mentioned in this comment: https://github.com/grpc/grpc-go/issues/7091#issuecomment-2037663115

It is not mentioned in the language agnostic gRPC docs. https://github.com/grpc/grpc/blob/master/doc/naming.md

**Comment by purnesh42H** [comment]
@rittneje yes, passthrough is only applicable in grpc-go and is already deprecated https://github.com/grpc/grpc-go/blob/master/resolver/passthrough/passthrough.go#L22. It only exist for backward compatibility right now.

**Comment by rittneje** [comment]
@purnesh42H First, the file you linked only mentions the _package_ is deprecated and should not be imported. It doesn't mention anything about the scheme itself. Second, it is the only way to get bufconn to work, so you can't just deprecate it without a proper replacement. Please re-open this issue.

**Comment by dfinkel** [comment]
FWIW, my team switched our bufconn uses to `localhost` as the address, since that's guaranteed to resolve with the DNS resolver.

**Comment by purnesh42H** [comment]
yeah, its not explicitly documented that passthrough is deprecated apart from source code but that's because it is internal to grpc-go. In release 1.64, we deprecated `grpc.Dial` to use `grpc.NewClient` https://github.com/grpc/grpc-go/releases/tag/v1.64.0. With `grpc.Dial` the default resolution scheme is passthrough which uses passthrough resolver that i linked above. With `grpc.NewClient` the default scheme is `dns`. If you want to use passthrough with `grpc.NewClient`, you need to pass the adderss prefixed with `passthrough:///`.

Could you describe what issue you are facing with bufcon though?

**Comment by rittneje** [comment]
@purnesh42H With bufconn, we need to use `grpc.WithContextDialer` to wire it up correctly. In this case, the target passed to `grpc.NewClient` is immaterial, but we need to prefix it with `passthrough:///` or else it will try to do a DNS resolution anyway and fail.

As `passthrough:///` is not documented (and apparently deprecated with no replacement) the only way to figure this out is to stumble across the GitHub comment I originally mentioned. Instead:
1. the package documentation for google.golang.org/grpc/test/bufconn should directly tell you what to do
2. either `passthrough:///` needs to be un-deprecated, or a proper replacement needs to be added and mentioned in the documentation
