### ISSUE TITLE
NewClient doesn't handle link-local IPv6 addresses

### ISSUE THREAD

**Issue by thallgren** [grpc/grpc-go#7882]
### What version of gRPC are you using?
v1.68.0

### What version of Go are you using (`go version`)?
go version go1.23.2 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Darwin MacBookPro 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:27 PDT 2024; root:xnu-11215.41.3~2/RELEASE_X86_64 x86_64 i386 Darwin

### What did you do?

I use `grpc.NewClient()` to connect using an address without an IP e.g. ":1234", and then make a call to a gRPC method.

### What did you expect to see?
A successful call (it works on Linux)

### What did you see instead?

I get an error saying: "dns: error parsing A record IP address fe80::1%lo0"

The problem is that the [dnsResolver.lookupHost](https://github.com/grpc/grpc-go/blob/master/internal/resolver/dns/dns_resolver.go#L317) assumes that all IPs found for "localhost" in `/etc/hosts` can be parsed by `net.ParseIP` (in `formatIP`). On many macOS systems this is not the case, because they contain an entry similar to `fe80::1%lo0  localhost`.

**Comment by thallgren** [comment]
The `net.ParseIP` will delegate to `netip.ParseAddr` and then fail if the parsed address contains a zone.

**Comment by arjan-bal** [comment]
Hi @thallgren, thanks for reporting the issue. It looks like the DNS resolver (which is the default when using grpc.NewClient) doesn't handle link-local IPv6 addresses correctly due to the presence of the `interface`. The format of link-local IPv6 addresses is `[IPv6-address%interface]:port`. `net.Dial` is able to connect to such addresses, so using the deprecated `grpc.Dial()` should work.

Let me discuss the scope of the fix with other maintainers and get back.
