### ISSUE TITLE
should we need to pre-validate the sendmsg size and validate it using fixed value math.MaxUint32

### ISSUE THREAD

**Issue by Chaunceyctx** [grpc/grpc-go#7897]
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
grpc v1.59.0
### What version of Go are you using (`go version`)?
go1.22.0
### What operating system (Linux, Windows, …) and version?
linux amd64
### What did you do?
If possible, provide a recipe for reproducing the error.

I used `grpc.MaxSendMsgSize(math.MaxUint64)` to create grpcServer. But 
https://github.com/grpc/grpc-go/blob/5565631455d326987ad3f9dba6d45478cc426c9f/rpc_util.go#L695
this method validates the send msg size with fixed MaxUint32. This is less than math.MaxUint64. So may be we need to remove this code chunk and validate the send msg size after compressing and involving header data in 
https://github.com/grpc/grpc-go/blob/5565631455d326987ad3f9dba6d45478cc426c9f/server.go#L1140

### What did you expect to see?
math.MaxUint64 value will work
### What did you see instead?
get error `grpc: message too large`

**Comment by arjan-bal** [comment]
Hi @Chaunceyctx, the the [gRPC over HTTP/2 protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) requires a 4 byte header in every message.
> The repeated sequence of Length-Prefixed-Message items is delivered in DATA frames
Length-Prefixed-Message → Compressed-Flag Message-Length Message
Compressed-Flag → 0 / 1 ; encoded as 1 byte unsigned integer
Message-Length → {length of Message} ; encoded as 4 byte unsigned integer (big endian)
Message → *{binary octet}

gRPC Go only supports HTTP/2 transports presently. This puts an upper limit of 4GB (2^32 bytes) on the message size. This is the reason for the `math.MaxUint32` check in the `encode` function.

There is a lower [limit of 2GB](https://protobuf.dev/programming-guides/proto-limits/#total) when using the protbuf codec.

We could move the`uint(b.Len()) > math.MaxUint32` check after the compression is performed and while complying with the gRPC protocol. This would give a little more headroom for large messages, however since you're relying on compression to bring the size below the threshold, you may see significant failures when compression ratio is low. We don't want to make this behaviour change without a strong motivation to do so.

**Comment by Chaunceyctx** [comment]
@arjan-bal got it! thanks :)
