### ISSUE TITLE
There is no `sync.Pool`, but so many `defer`

### ISSUE THREAD

**Issue by dup2X** [grpc/grpc-go#816]
Profile shows that.

**Comment by menghanl** [comment]
Can you elaborate on what the issue is?

**Comment by dup2X** [comment]
Less objects and less gc-latency. What is the reason for not using sync.Pool ? Thanks for your explanation.

**Comment by hsaliak** [comment]
`sync.Pool` is a potential performance optimization, it is one tool that can be used when object pools are a good solution. However, we can only determine whether it's a good solution to a problem at hand after analyzing the problem,benchmarking and profiling.

`defer` is a language construct that lets you schedule a function to be run on the exit of the current scope. I am not sure how they relate. 

Does that help?

**Comment by apolcyn** [comment]
@dup2X we do actually use `sync.Pool` in the the default "protobuf" `Codec` (see https://github.com/grpc/grpc-go/blob/master/codec.go#L114), since those `protobuf.Buffer` objects were showing up as a pain point in some benchmarks.

We might be able to do this in more places if there are more objects costing a lot that are doable to cache.

What's the scenario and what object allocs are you seeing?

**Comment by dup2X** [comment]
@hsaliak Thanks a lot.
@apolcyn I saw the same to you. 
And the field of pb_struct is ptr, that maybe incr gc...
