### ISSUE TITLE
Watcher is ignored after returning error from Next

### ISSUE THREAD

**Issue by dmvk** [grpc/grpc-go#844]
Hi,

first of all, thanks for an amazing job you guys are doing. I've implemented custom naming resolver and there is one think that doesn't make much sense to me. The think is, when watcher's `Next` method returns error ("unrecoverable error"), balancer just ignores watcher ever since. This is very unpredictable state from my point of view.

https://github.com/grpc/grpc-go/blob/master/balancer.go#L225

Do you think this case can be handled? Start/Stop watcher, closing channel. At least, it should be more transparent to a client.

Thanks,
D.

**Comment by iamqizhao** [comment]
The current code leaves the watcher until the Balancer is closed. In this way, we do not enforce the impl of Watcher.Close to be re-entrant since Close is called only once. We can call Close() when Next returns an error or even Next impl can call Close by itself if we require Close is re-entrant. The current way is chosen for simplicity and safety. Do you have any concrete scenario to show us which option you think is better?

**Comment by dmvk** [comment]
From method contract:

```
It should return an error if and only if Watcher cannot recover.
```

Can you please give an example of such error? Only relevant thing I can come up with is unreachable DNS, which is still recoverable. 

Other thing is that `error` is used for flow control. When you close the watcher, it is the only way to exit from the goroutine executing `Next` method.

Thanks,
D.

**Comment by menghanl** [comment]
This issue becomes obsolete with the new balancer and resolver APIs (#1388). Closing this now.
