### ISSUE TITLE
bogus greeting error when going to trace ui

### ISSUE THREAD

**Issue by vrecan** [grpc/grpc-go#881]
transport: http2Server.HandleStreams received bogus greeting from client: "GET /debug/requests HTTP

I have thrown together a simple server and client and wanted to look at the trace ui. The documentation doesn't really explain where this should be other then /debug/requests so I hit the server port and got this error.

**Comment by edrex** [comment]
I'm also wondering how to get those endpoints working. I've tried with the hello example (no tls, error similar to above) as well as the route_guide example (`transport: http2Server.HandleStreams failed to receive the preface from client: EOF`). Some basic working example of tracing would be very helpful.

**Comment by iamqizhao** [comment]
Currently we do not share the grpc port with httpserver so that you need to setup a httpserver on another port to make tracing work. You can use https://github.com/grpc/grpc-go/blob/master/benchmark/client/main.go#L152 as an example. Yes, we should have a howto doc but since the tracing part is under rewriting we hold off for now.

**Comment by hsaliak** [comment]
Is this still an issue? @vrecan
