### ISSUE TITLE
Fatalf for encoding errors is too aggressive

### ISSUE THREAD

**Issue by dhowden** [grpc/grpc-go#900]
It is relatively easy to get errors from the Protobuf encoder (i.e. via putting nil into repeated fields see https://github.com/golang/protobuf/blob/master/proto/encode.go#L65).  Currently any encoder errors cause the gRPC server process to be killed via a Fatal error: https://github.com/grpc/grpc-go/blob/8d57dd3404d3e59c8102bbd4ed9822253dfacffb/server.go#L521

The use of `Fatal` in this case is based on the assumption that encoding errors only occur in very bad situations (i.e. memory corruption etc) as detailed in the comment https://github.com/grpc/grpc-go/blob/8d57dd3404d3e59c8102bbd4ed9822253dfacffb/server.go#L514.

The Codec interface should probably be updated to mention that returning errors from the Marshal method will trigger a Fatal error (and hence kill the server), at least until the Fatal call is removed or a good alternative can be decided.

**Comment by puellanivis** [comment]
The question need be asked, is this an error in the encoders, decoders, or gRPC not taking into account something beyond their control?

In house at Google, generally something like this wasn't viewed to be a big issue, because everyone is sending good traffic (or they should prepare to write a postmortem), so “crash the server when you can't report an error” is entirely valid behavior.

But outside of Google, yeah, that assumption doesn't necessarily hold. But I'm curious as to what the server could do other than ignore the request… or send an error response of “bad input”.

**Comment by dhowden** [comment]
I think that the only way to properly get around this would be add a way for an encoder to expose the severity of the error, which could then separate unrecoverable errors (i.e. where the server should be killed), from less serious errors (i.e. when the current response should be aborted).

For instance, adding something simple to the API:

```go
// CodecError is an interface which defines behaviour to allow codec errors
// to expose their severity.  By default any errors returned from Codec.Marshal
// result in a Fatal error which kills the server process.  When an error returned from
// Code.Marshal implements CodeError and Recoverable() returns true, then the server
// will only fail the current request.
type CodecError interface {
    // Recoverable returns true if the Codec can continue to be used
    // despite the error. 
    Recoverable() bool
}
```

**Comment by dhowden** [comment]
Looks like this was fixed in https://github.com/grpc/grpc-go/pull/1276, so closing for now.
