### ISSUE TITLE
Which branch to use?

### ISSUE THREAD

**Issue by aybabtme** [grpc/grpc-go#907]
Ohai! Should we be using `v1.0.1-GA` or can we safely follow `master`? I know in the past some APIs were introduced to master that were later removed and/or modified (but marked as EXPERIMENTAL in the godocs). Is there any sort of API guaranty that comes from following `v1.0.1-GA` and future tags/versioned commits?

In particular, we'd like to avoid using experimental APIs by mistake, so if one of those two methods involves only stable APIs, that'd be great.

**Comment by iamqizhao** [comment]
v1.0.1-GA is a tag instead of a branch. We guarantee the non-experimental API stability in all the commits after v1.0.1-GA tag (except in very rare cases we have to change. In those cases, we will have some deprecation period for the old APIs). Therefore, you should probably always use the master

We will tag all the experimental API revisions too so that if you use some experimental APIs it is convenient to upgrade..

**Comment by aybabtme** [comment]
Cool sounds good to me!
